prisma-push:
	yarn prisma format
	yarn prisma generate
	yarn prisma db push

import-symbols:
	yarn prisma format
	yarn prisma generate
	yarn ts-node ./scripts/import/stock/symbols.ts

import-history:
	yarn prisma format
	yarn prisma generate
	yarn ts-node ./scripts/import/stock/history.ts
