import * as vscode from 'vscode';
import { KnowledgeGraph } from './graphData';
import { GraphView } from './graphView';
import {
  WikiLinkCompletionProvider,
  WikiLinkDefinitionProvider,
  WikiLinkHoverProvider,
  WikiLinkDocumentLinkProvider,
} from './wikiLinkProvider';

let graph: KnowledgeGraph;
let graphView: GraphView;

export function activate(context: vscode.ExtensionContext) {
  graph = new KnowledgeGraph();
  graphView = new GraphView();

  context.subscriptions.push(
    vscode.languages.registerCompletionItemProvider(
      'markdown',
      new WikiLinkCompletionProvider(),
      '['
    ),
    vscode.languages.registerDefinitionProvider(
      'markdown',
      new WikiLinkDefinitionProvider()
    ),
    vscode.languages.registerHoverProvider(
      'markdown',
      new WikiLinkHoverProvider()
    ),
    vscode.languages.registerDocumentLinkProvider(
      'markdown',
      new WikiLinkDocumentLinkProvider()
    ),

    vscode.commands.registerCommand('obsidianFlow.showGraph', async () => {
      const data = await graph.refresh();
      if (data) {
        await graphView.show(data);
      }
    }),

    vscode.commands.registerCommand(
      'obsidianFlow.loadGraphFromFile',
      async () => {
        const uris = await vscode.window.showOpenDialog({
          canSelectMany: false,
          filters: { 'Graph JSON': ['json'] },
          title:
            'Select graph JSON file generated by hieudoanm docsify obsidian',
        });
        if (!uris || uris.length === 0) return;
        const data = await graph.loadFromFile(uris[0].fsPath);
        if (data) {
          await graphView.show(data);
        }
      }
    ),

    graph
  );
}

export function deactivate() {
  graph?.dispose();
}
