import Foundation

/**
 * Assigns own enumerable string keyed properties of source objects to the destination object.
 */
public func assign(_ obj: inout [String: Any], _ sources: [String: Any]...) -> [String: Any] {
    for source in sources {
        for (key, value) in source {
            obj[key] = value
        }
    }
    return obj
}

/**
 * Creates an object composed of the picked object properties.
 */
public func pick(_ obj: [String: Any], _ paths: [String]) -> [String: Any] {
    var result = [String: Any]()
    for path in paths {
        if let value = obj[path] {
            result[path] = value
        }
    }
    return result
}

/**
 * The opposite of _.pick; this method creates an object composed of the own and inherited enumerable property paths of object that are not omitted.
 */
public func omit(_ obj: [String: Any], _ paths: [String]) -> [String: Any] {
    var result = obj
    for path in paths {
        result.removeValue(forKey: path)
    }
    return result
}

/**
 * Gets the value at path of object. If the resolved value is undefined, the defaultValue is returned in its place.
 */
public func get(_ obj: [String: Any]?, _ path: String, _ defaultValue: Any? = nil) -> Any? {
    guard let obj = obj else { return defaultValue }
    let parts = path.components(separatedBy: ".")
    var current: Any? = obj
    for part in parts {
        if let dict = current as? [String: Any] {
            current = dict[part]
        } else {
            return defaultValue
        }
    }
    return current ?? defaultValue
}

/**
 * Checks if path is a direct property of object.
 */
public func has(_ obj: [String: Any]?, _ path: String) -> Bool {
    guard let obj = obj else { return false }
    let parts = path.components(separatedBy: ".")
    var current: Any? = obj
    for part in parts {
        if let dict = current as? [String: Any] {
            if dict[part] == nil { return false }
            current = dict[part]
        } else {
            return false
        }
    }
    return true
}

/**
 * Creates an array of the own enumerable property names of object.
 */
public func keys(_ obj: [String: Any]) -> [String] {
    return Array(obj.keys)
}

/**
 * Creates an array of the own enumerable string keyed property values of object.
 */
public func values(_ obj: [String: Any]) -> [Any] {
    return Array(obj.values)
}

/**
 * Creates an object with the same values as object and keys generated by running each own enumerable string keyed property of object thru iteratee.
 */
public func mapKeys(_ obj: [String: Any], _ iteratee: (Any, String) -> String) -> [String: Any] {
    var result = [String: Any]()
    for (key, value) in obj {
        result[iteratee(value, key)] = value
    }
    return result
}

/**
 * Creates an object with the same keys as object and values generated by running each own enumerable string keyed property of object thru iteratee.
 */
public func mapValues(_ obj: [String: Any], _ iteratee: (Any) -> Any) -> [String: Any] {
    var result = [String: Any]()
    for (key, value) in obj {
        result[key] = iteratee(value)
    }
    return result
}

/**
 * Assigns own and inherited enumerable string keyed properties of source objects to the destination object for all destination properties that resolve to undefined.
 */
public func defaults(_ obj: inout [String: Any], _ sources: [String: Any]...) -> [String: Any] {
    for source in sources {
        for (key, value) in source {
            if obj[key] == nil {
                obj[key] = value
            }
        }
    }
    return obj
}

/**
 * This method is like _.find except that it returns the key of the first element predicate returns truthy for instead of the element itself.
 */
public func findKey(_ obj: [String: Any], _ predicate: (Any) -> Bool) -> String? {
    return obj.first(where: { predicate($0.value) })?.key
}

/**
 * Iterates over own and inherited enumerable string keyed properties of an object and invokes iteratee for each property.
 */
public func forIn(_ obj: [String: Any], _ iteratee: (Any, String) -> Void) {
    for (key, value) in obj {
        iteratee(value, key)
    }
}

/**
 * Iterates over own enumerable string keyed properties of an object and invokes iteratee for each property.
 */
public func forOwn(_ obj: [String: Any], _ iteratee: (Any, String) -> Void) {
    forIn(obj, iteratee)
}

/**
 * Creates an object composed of the inverted keys and values of object.
 */
public func invert(_ obj: [String: Any]) -> [String: String] {
    var result = [String: String]()
    for (key, value) in obj {
        result["\(value)"] = key
    }
    return result
}

/**
 * This method is like _.invert except that the inverted object is generated from the results of running each element of object thru iteratee.
 */
public func invertBy(_ obj: [String: Any], _ iteratee: (Any) -> String) -> [String: String] {
    var result = [String: String]()
    for (key, value) in obj {
        result[iteratee(value)] = key
    }
    return result
}

/**
 * Sets the value at path of object. If a portion of path doesn't exist, it's created.
 */
public func set(_ obj: inout [String: Any], _ path: String, _ value: Any) -> [String: Any] {
    let parts = path.components(separatedBy: ".")
    var current = obj
    // Deep set logic is complex in Swift due to value semantics.
    // Simplifying for now or assuming single level for basic implementation.
    if parts.count == 1 {
        obj[path] = value
    } else {
        // Deep set would require more complex nesting logic with casting.
        var dicts: [[String: Any]] = []
        var temp = obj
        for i in 0..<parts.count-1 {
            dicts.append(temp)
            if let next = temp[parts[i]] as? [String: Any] {
                temp = next
            } else {
                temp = [:]
            }
        }
        
        var lastDict = temp
        lastDict[parts.last!] = value
        
        var result = lastDict
        for i in (0..<parts.count-1).reversed() {
            var parent = dicts[i]
            parent[parts[i]] = result
            result = parent
        }
        obj = result
    }
    return obj
}

/**
 * Removes the property at path of object.
 */
public func unset(_ obj: inout [String: Any], _ path: String) -> Bool {
    if obj[path] != nil {
        obj.removeValue(forKey: path)
        return true
    }
    // Deep unset is skipped for brevity in this MVP
    return false
}
