import-languages:
	yarn ts-node ./scripts/import/languages

import-quotes:
	yarn ts-node ./scripts/import/quotes

import-tarot-cards:
	yarn ts-node ./scripts/import/tarot-cards

import-words:
	yarn ts-node ./scripts/import/words-api
	yarn ts-node ./scripts/import/words-txt

import-words-api:
	yarn ts-node ./scripts/import/words-api

import-words-txt:
	yarn ts-node ./scripts/import/words-txt
