version: '3.9'

volumes:
  postgresql_data:
    driver: local

services:
  hieudoanm-postgresql:
    restart: unless-stopped
    image: postgres:16.1
    container_name: hieudoanm-postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  hieudoanm-redis:
    restart: unless-stopped
    image: redis:7.2.4
    container_name: hieudoanm-redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
