packages:
  - packages/**
allowBuilds:
  '@prisma/engines': true
  '@vscode/vsce-sign': true
  keytar: true
  prisma: true
  protobufjs: true
  sharp: true
  spawn-sync: true
  tesseract.js: true
  unrs-resolver: true
