packages:
  - packages/**
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  '@vscode/vsce-sign': true
  canvas: true
  core-js: true
  esbuild: true
  keytar: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  spawn-sync: true
  tesseract.js: true
  unrs-resolver: true
minimumReleaseAge: 0
