packages:
  - packages/**
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  '@vscode/vsce-sign': true
  canvas: true
  core-js: true
  esbuild: true
  keytar: true
  prisma: true
  protobufjs: true
  sharp: true
  spawn-sync: true
  tesseract.js: true
  unrs-resolver: true
patchedDependencies:
  '@solidjs/start@2.0.0-alpha.2': patches/@solidjs__start@2.0.0-alpha.2.patch
