import { FC } from 'react';
import { TheoryTemplate } from '@/components/templates/TheoryTemplate';

const MegPage: FC = () => (
  <TheoryTemplate
    title="Magnetoencephalography (MEG)"
    subtitle="Millisecond-resolution magnetic fields from cortical currents — exquisite timing, and the magnetic skull is effectively transparent."
    parentLink={{ href: '/neuroscience', label: 'Neuroscience' }}
    sections={[
      {
        title: 'What it measures',
        body: (
          <div className="flex flex-col gap-3">
            <p>
              MEG sensors detect the magnetic field generated by the same
              intracellular postsynaptic currents that produce scalp EEG, but
              from a different component of the current geometry. Cerebral blood
              flow, skull movement, and other slow sources contribute
              negligibly, so the signal is{' '}
              <strong>essentially pure neurophysiology</strong> rather than a
              mixture requiring as much physiological noise modelling.
            </p>
            <p>
              The amplitude is the whole problem. Typical brain fields are{' '}
              <strong>10&ndash;500 femtotesla</strong> &mdash; roughly a million
              times smaller than the Earth's magnetic field and near the noise
              floor of the room itself. A shielded room, a degaussing system,
              and cryogenic hardware are not optional extras; they are what
              makes the measurement possible at all.
            </p>
          </div>
        ),
      },
      {
        title: 'Why the skull does not blur it',
        body: (
          <div className="flex flex-col gap-3">
            <p>
              This is MEG's central advantage. Electrical potentials are{' '}
              <em>volume-conducted</em>: they smear as they pass through
              low-conductivity skull and high-conductivity CSF, which is why
              scalp EEG has no principled inverse solution. Magnetic fields are
              affected by{' '}
              <strong>magnetic permeability, not conductivity</strong>, and
              bone, CSF, and brain are all nearly identical to air in that
              respect.
            </p>
            <p>
              The consequence: the field measured outside the head is a faithful
              sum of the sources inside, with far less spatial distortion.
              Combined with the fact that a dipole field decays as the inverse{' '}
              <em>cube</em> of distance, MEG is markedly more sensitive to
              <strong>deep</strong> sources than EEG &mdash; thalamic and
              hippocampal generators are detectable in MEG but heavily
              attenuated at the scalp.
            </p>
          </div>
        ),
      },
      {
        title: 'Sensors and instrumentation',
        body: (
          <div className="flex flex-col gap-3">
            <p>
              Conventional systems use <strong>SQUID</strong> (superconducting
              quantum interference device) flux transformers, cooled to around
              4&nbsp;K in a liquid-helium cryostat. Their weakness is geometry:
              a helmet-sized dewar of liquid helium must be refilled regularly,
              and the subject must keep still, because the sensors cannot follow
              the head.
            </p>
            <p>
              The reason SQUID works so well is <strong>gradiometry</strong>.
              Each sensor measures the <em>difference</em> in field between two
              points ~4&nbsp;cm apart, so uniform ambient field &mdash; the
              Earth, the building, the building's elevators &mdash; cancels
              exactly. One reference channel is also measured inside the shield
              to model and subtract whatever common-mode field remains.
            </p>
            <p>
              Modern systems run 300+ channels, sample above{' '}
              <strong>1&nbsp;kHz</strong>, and restrict analysis to a usable
              band of roughly 0.01&ndash;200&nbsp;Hz. That band is not a
              hardware limit but a noise limit: ambient field and thermal noise
              rise sharply at low frequency.
            </p>
          </div>
        ),
      },
      {
        title: 'Reference-free reconstruction',
        body: (
          <div className="flex flex-col gap-3">
            <p>
              Because whole-head coverage makes an intact-helmet assumption
              possible, MEG can be reconstructed{' '}
              <strong>without choosing a reference at all</strong>. This removes
              the arbitrary montage decision that complicates scalp EEG, though
              the cost is a distributed, spatially smeared point-spread function
              whose extent grows with depth &mdash; a trade, not a free win.
            </p>
            <p>
              The practical families: <strong>beamforming</strong> (LCMV, DICS)
              works well for well-separated sources but is biased when sources
              overlap; <strong>beamformers constrained by MRI</strong> (sLORETA,
              eLORETA, MNE) improve spatial precision; and{' '}
              <strong>beamforming with parametric empirical Bayes</strong> is
              the current accuracy leader for evoked responses. Combining MEG
              with scalp EEG, which has complementary sensitivity to different
              source orientations, is standard in modern pipelines.
            </p>
          </div>
        ),
      },
      {
        title: 'Strengths and limits',
        body: (
          <ul className="ml-5 flex list-disc flex-col gap-2">
            <li>
              <strong>Direct, single-neuron temporal resolution.</strong> The
              only non-invasive method resolving sub-10&nbsp;ms dynamics, which
              is what makes it the instrument of choice for latency-ordered
              processing chains.
            </li>
            <li>
              <strong>Less spatial blurring than EEG,</strong> and genuine depth
              sensitivity because of the inverse-cube falloff.
            </li>
            <li>
              <strong>Minimal physiological noise,</strong> so artefact
              rejection is less interpretive than in EEG.
            </li>
            <li>
              <strong>Enormous cost and fixed geometry.</strong> Multi-million
              dollar installations, a shielded room the size of a small studio,
              periodic helium refills, and participants who must hold still
              because the sensors cannot follow a moving head. MEG is a
              laboratory instrument, not a clinical or wearable one.
            </li>
          </ul>
        ),
      },
    ]}
    links={[
      {
        href: '/neuroscience/meg/interactive',
        label: 'MEG / EEG Forward Model',
        description:
          'Send one cortical dipole into a helmet: compare the undistorted magnetic field with the volume-conducted scalp potential.',
      },
    ]}
    references={[
      {
        href: 'https://mitpress.mit.edu/9780262621619/electric-fields-of-the-brain/',
        label: 'Nunez & Srinivasan — Electric Fields of the Brain, MIT Press',
        description:
          'The definitive treatment of the bioelectric and biomagnetic forward problems, including why magnetic permeability makes MEG the less distorted of the two.',
      },
      {
        href: 'https://doi.org/10.1016/j.neuroimage.2017.05.068',
        label: 'Niso et al. (2018) — NeuroImage',
        description:
          'Recommended open processing environment for MEG/EEG forward modelling and source reconstruction, with practical guidance on depth bias.',
      },
      {
        href: 'https://doi.org/10.1038/s41583-018-0070-8',
        label: 'Baillet (2017) — Nature Reviews Neuroscience',
        description:
          'Comprehensive review of MEG theory, hardware, source reconstruction, and artefact handling.',
      },
    ]}
  />
);

export default MegPage;
