import type { ChannelAnalysis } from '@/lib/image/histogram';
import type { ChannelState, ImageRaster, ViewTransform } from '@/types/image';
import type { ViewerSize } from '@/hooks/useImageViewer';
import type { Annotation, AnnotationLayer, ViewTool } from '@/types/annotation';
import type { AnalysisStatus } from '@/hooks/useAnalysis';
import type { ImageAnalysis } from '@/lib/analysis/analyze';
import type { BatchResult } from '@/lib/analysis/batch';

export interface ViewerTemplateProps {
  raster: ImageRaster | null;
  name: string | null;
  channels: ChannelState[];
  analyses: ChannelAnalysis[] | null;
  transform: ViewTransform;
  size: ViewerSize;
  onOpenDemo: () => void;
  onSetSize: (size: ViewerSize) => void;
  onFitView: () => void;
  onZoomIn: () => void;
  onZoomOut: () => void;
  onTransformChange: (transform: ViewTransform) => void;
  onToggleChannel: (id: string, visible: boolean) => void;
  onSetChannelOpacity: (id: string, opacity: number) => void;
  onSaveProject: () => void;
  layers: AnnotationLayer[];
  activeLayer: AnnotationLayer | null;
  tool: ViewTool;
  canUndo: boolean;
  canRedo: boolean;
  onToolChange: (tool: ViewTool) => void;
  onAddLayer: () => void;
  onRemoveLayer: (id: string) => void;
  onToggleLayerVisibility: (id: string, visible: boolean) => void;
  onSetLayerColor: (id: string, color: string) => void;
  onSetActiveLayer: (id: string) => void;
  onAddAnnotation: (annotation: Annotation) => void;
  onUndo: () => void;
  onRedo: () => void;
  analysisStatus: AnalysisStatus;
  analysisProgress: number;
  analysisError: string | null;
  k: number;
  analysisResult: ImageAnalysis | null;
  batchResult: BatchResult | null;
  onSetK: (k: number) => void;
  onRunSingle: () => void;
  onBatchFiles: (files: File[]) => void;
  onExportCsv: () => void;
  onExportJson: () => void;
  onExportPng: () => void;
  onOpenReport: () => void;
  reportOpen: boolean;
  reportTitle: string;
  reportHtml: string;
  onCloseReport: () => void;
}
