'use client';

import {
  PiStrategy,
  PiGlobe,
  PiUsersThree,
  PiArrowsLeftRight,
  PiTarget,
  PiShield,
  PiHandshake,
  PiLightbulb,
  PiChartLineDown,
  PiSquaresFour,
  PiFeather,
  PiFlowArrow,
  PiTestTube,
  PiClockCountdown,
  PiChartLine,
  PiBank,
  PiChartLineUp,
  PiGraph,
  PiArrowLineUp,
  PiArrowsCounterClockwise,
  PiWind,
  PiWarning,
  PiBuildingOffice,
  PiChartPie,
  PiGlobeHemisphereWest,
  PiBrain,
  PiMegaphone,
  PiUsers,
  PiPiggyBank,
  PiCoins,
  PiBriefcase,
  PiTrendDown,
  PiRepeat,
  PiTreeStructure,
  PiHandCoins,
  PiGridFour,
  PiDna,
  PiGameController,
  PiStack,
  PiTag,
  PiShoppingCart,
  PiFactory,
  PiEquals,
  PiClock,
  PiWarningCircle,
  PiChartBar,
  PiIntersect,
  PiTrendUp,
  PiWaveSine,
  PiMoney,
  PiCrosshair,
  PiUserMinus,
  PiChartScatter,
  PiGauge,
  PiSmileySad,
  PiBoundingBox,
  PiArrowsClockwise,
  PiWallet,
  PiGift,
  PiHeart,
  PiCrown,
  PiGraduationCap,
  PiSneaker,
  PiAirplane,
} from 'react-icons/pi';
import { HomeTemplate } from '@/components/templates/HomeTemplate';
import { NextPage } from 'next';

const ITEMS = [
  {
    label: "Prisoner's Dilemma",
    description: 'Iterated game theory against AI strategies',
    icon: PiStrategy,
    href: '/prisoners-dilemma/',
    badge: 'Nobel 1994',
    category: 'Game Theory',
  },
  {
    label: 'Nash Equilibrium',
    description: 'The stable point where no one wants to deviate alone',
    icon: PiTarget,
    href: '/nash-equilibrium/',
    badge: 'Nobel 1994',
    category: 'Game Theory',
  },
  {
    label: 'Tragedy of the Commons',
    description: 'Why shared resources get overused',
    icon: PiGlobe,
    href: '/tragedy-of-the-commons/',
    badge: 'Nobel 2009',
    category: 'Public & Macro',
  },
  {
    label: 'Public Goods Dilemma',
    description: 'How free-riding undermines shared goods',
    icon: PiUsersThree,
    href: '/public-goods-dilemma/',
    category: 'Public & Macro',
  },
  {
    label: 'Opportunity Cost',
    description: 'The real cost of every choice and trade',
    icon: PiArrowsLeftRight,
    href: '/opportunity-cost/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Moral Hazard',
    description: 'When insurance changes behavior—and someone else pays',
    icon: PiShield,
    href: '/moral-hazard/',
    badge: 'Nobel 2001',
    category: 'Information & Risk',
  },
  {
    label: 'Auction Theory',
    description: 'How bidding rules shape who wins and what they pay',
    icon: PiHandshake,
    href: '/auction-theory/',
    badge: 'Nobel 1996 · 2020',
    category: 'Game Theory',
  },
  {
    label: 'Bayesian Updating',
    description: 'How rational agents revise beliefs with new evidence',
    icon: PiLightbulb,
    href: '/bayesian-updating/',
    category: 'Behavioral',
  },
  {
    label: 'Prospect Theory',
    description: 'Why losses loom larger than gains in every decision',
    icon: PiChartLineDown,
    href: '/prospect-theory/',
    badge: 'Nobel 2002',
    category: 'Behavioral',
  },
  {
    label: 'Mechanism Design',
    description:
      'Designing rules so self-interested players produce good outcomes',
    icon: PiSquaresFour,
    href: '/mechanism-design/',
    badge: 'Nobel 2007',
    category: 'Game Theory',
  },
  {
    label: 'Nudge & Behavioral Econ',
    description:
      'How choice architecture steers decisions without forcing them',
    icon: PiFeather,
    href: '/nudge-and-behavioral-economics/',
    badge: 'Nobel 2017',
    category: 'Behavioral',
  },
  {
    label: 'Causal Inference',
    description: 'Moving beyond correlation to find true cause and effect',
    icon: PiFlowArrow,
    href: '/causal-inference/',
    badge: 'Nobel 2021',
    category: 'Information & Risk',
  },
  {
    label: 'Development RCTs',
    description: 'Randomized experiments to discover what reduces poverty',
    icon: PiTestTube,
    href: '/development-rcts/',
    badge: 'Nobel 2019',
    category: 'Development & Growth',
  },
  {
    label: 'Time Inconsistency',
    description: 'Why commitments made today often fail tomorrow',
    icon: PiClockCountdown,
    href: '/time-inconsistency/',
    badge: 'Nobel 2004',
    category: 'Behavioral',
  },
  {
    label: 'Market Microstructure',
    description: 'How the mechanics of trading shape prices and liquidity',
    icon: PiChartLine,
    href: '/market-microstructure/',
    category: 'Information & Risk',
  },
  {
    label: 'Institutions & Growth',
    description: 'Why the rules of society decide national prosperity',
    icon: PiBank,
    href: '/institutions-and-growth/',
    badge: 'Nobel 1993 · 2024',
    category: 'Development & Growth',
  },
  {
    label: 'Supply & Demand',
    description: 'The two forces that set nearly every market price',
    icon: PiChartLineUp,
    href: '/supply-and-demand/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Elasticity',
    description: 'How strongly buyers and sellers respond to price changes',
    icon: PiGraph,
    href: '/elasticity/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Marginal Utility',
    description: 'Why the next unit is worth a little less than the last',
    icon: PiArrowLineUp,
    href: '/marginal-utility/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Zero-Sum Games',
    description: "Games where one player's gain is another's loss",
    icon: PiArrowsCounterClockwise,
    href: '/zero-sum-games/',
    category: 'Game Theory',
  },
  {
    label: 'Externalities',
    description: 'When your actions affect strangers—for better or worse',
    icon: PiWind,
    href: '/externalities/',
    category: 'Public & Macro',
  },
  {
    label: 'Adverse Selection',
    description: 'Hidden information that can collapse a market',
    icon: PiWarning,
    href: '/adverse-selection/',
    category: 'Information & Risk',
  },
  {
    label: 'Monopoly & Market Power',
    description: 'When one seller controls the market',
    icon: PiBuildingOffice,
    href: '/monopoly-and-market-power/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Oligopoly',
    description: 'A few big firms, each watching the others',
    icon: PiChartPie,
    href: '/oligopoly/',
    category: 'Game Theory',
  },
  {
    label: 'Trade & Tariffs',
    description: 'Why trade helps—and what tariffs really cost',
    icon: PiGlobeHemisphereWest,
    href: '/trade-and-tariffs/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Behavioral Heuristics',
    description: 'The mental shortcuts that help—and sometimes mislead',
    icon: PiBrain,
    href: '/behavioral-heuristics/',
    category: 'Behavioral',
  },
  {
    label: 'Signaling',
    description: 'Proving about yourself what others cannot see',
    icon: PiMegaphone,
    href: '/signaling/',
    category: 'Information & Risk',
  },
  {
    label: 'Public Choice',
    description: 'The economics of politics and self-interested policymakers',
    icon: PiUsers,
    href: '/public-choice/',
    category: 'Public & Macro',
  },
  {
    label: 'Keynesian Economics',
    description: 'Why recessions can get stuck—and how government responds',
    icon: PiPiggyBank,
    href: '/keynesian-economics/',
    category: 'Public & Macro',
  },
  {
    label: 'Monetary Policy',
    description: 'How central banks steer money, rates, and inflation',
    icon: PiCoins,
    href: '/monetary-policy/',
    category: 'Public & Macro',
  },
  {
    label: 'Labor Markets',
    description: 'How wages and jobs are set—and the minimum-wage debate',
    icon: PiBriefcase,
    href: '/labor-markets/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Economic Inequality',
    description: 'How income and wealth are distributed across a population',
    icon: PiTrendDown,
    href: '/economic-inequality/',
    category: 'Development & Growth',
  },
  {
    label: 'Repeated Games & Tit-for-Tat',
    description:
      'How cooperation emerges when the same game is played again and again',
    icon: PiRepeat,
    href: '/repeated-games/',
    category: 'Game Theory',
  },
  {
    label: 'Backward Induction',
    description: 'Solving games by reasoning from the last move to the first',
    icon: PiTreeStructure,
    href: '/backward-induction/',
    category: 'Game Theory',
  },
  {
    label: 'Bargaining Theory',
    description:
      'How threats, patience, and outside options shape negotiated splits',
    icon: PiHandCoins,
    href: '/bargaining-theory/',
    category: 'Game Theory',
  },
  {
    label: 'Coordination Games',
    description: 'When everyone must match on an action—and anything works',
    icon: PiGridFour,
    href: '/coordination-games/',
    category: 'Game Theory',
  },
  {
    label: 'Evolutionary Game Theory',
    description:
      'How strategies spread through a population by fitness, not choice',
    icon: PiDna,
    href: '/evolutionary-game-theory/',
    category: 'Game Theory',
  },
  {
    label: 'Game Theory Basics',
    description: 'The language of strategy, payoffs, and rational play',
    icon: PiGameController,
    href: '/game-theory-basics/',
    category: 'Game Theory',
  },
  {
    label: 'Imperfect Competition',
    description: 'When firms have some price power—but face rivals',
    icon: PiStack,
    href: '/imperfect-competition/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Price Discrimination',
    description: 'Charging different people different prices for the same good',
    icon: PiTag,
    href: '/price-discrimination/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Consumer Theory',
    description: 'How rational consumers choose between goods within a budget',
    icon: PiShoppingCart,
    href: '/consumer-theory/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Production & Costs',
    description:
      'How firms turn inputs into output—and the shape of their costs',
    icon: PiFactory,
    href: '/production-and-costs/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Perfect Competition',
    description: 'The idealized market where no one can influence price',
    icon: PiEquals,
    href: '/perfect-competition/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Time Value of Money',
    description: 'Why a dollar today is worth more than a dollar tomorrow',
    icon: PiClock,
    href: '/time-value-of-money/',
    category: 'Markets & Pricing',
  },
  {
    label: 'Market Failures',
    description:
      'When free markets alone produce socially inefficient outcomes',
    icon: PiWarningCircle,
    href: '/market-failures/',
    category: 'Public & Macro',
  },
  {
    label: 'GDP & National Accounts',
    description: 'How economists measure the size and growth of an economy',
    icon: PiChartBar,
    href: '/gdp-and-national-accounts/',
    category: 'Public & Macro',
  },
  {
    label: 'Aggregate Demand & Supply',
    description: 'The economy-wide version of supply and demand',
    icon: PiIntersect,
    href: '/aggregate-demand-supply/',
    category: 'Public & Macro',
  },
  {
    label: 'The Phillips Curve',
    description: 'Does lower unemployment always mean higher inflation?',
    icon: PiTrendUp,
    href: '/phillips-curve/',
    category: 'Public & Macro',
  },
  {
    label: 'Business Cycles',
    description: 'The recurring pattern of expansion and contraction',
    icon: PiWaveSine,
    href: '/business-cycles/',
    category: 'Public & Macro',
  },
  {
    label: 'Fiscal Policy',
    description: 'How government spending and taxation steer the economy',
    icon: PiMoney,
    href: '/fiscal-policy/',
    category: 'Public & Macro',
  },
  {
    label: 'The IS-LM Model',
    description: 'How goods and money markets interact to set output and rates',
    icon: PiCrosshair,
    href: '/is-lm-model/',
    category: 'Public & Macro',
  },
  {
    label: "Unemployment & Okun's Law",
    description:
      'Why people are out of work—and how joblessness moves with growth',
    icon: PiUserMinus,
    href: '/unemployment-okuns-law/',
    category: 'Public & Macro',
  },
  {
    label: 'Efficient Market Hypothesis',
    description:
      'The theory that prices instantly reflect all available information',
    icon: PiChartScatter,
    href: '/efficient-market-hypothesis/',
    category: 'Finance',
  },
  {
    label: 'CAPM & Risk',
    description:
      'Putting a price on risk through beta and the security market line',
    icon: PiGauge,
    href: '/capm-and-risk/',
    category: 'Finance',
  },
  {
    label: 'Behavioral Finance',
    description: 'How psychology creates mispricing and market anomalies',
    icon: PiSmileySad,
    href: '/behavioral-finance/',
    category: 'Finance',
  },
  {
    label: 'Portfolio Theory',
    description: 'How diversification is the only free lunch in investing',
    icon: PiBoundingBox,
    href: '/portfolio-theory/',
    category: 'Finance',
  },
  {
    label: 'Arbitrage',
    description: 'Buying cheap and selling dear at the same moment',
    icon: PiArrowsClockwise,
    href: '/arbitrage/',
    category: 'Finance',
  },
  {
    label: 'Mental Accounting',
    description: 'Treating money differently depending on where it comes from',
    icon: PiWallet,
    href: '/mental-accounting/',
    category: 'Behavioral',
  },
  {
    label: 'The Endowment Effect',
    description:
      'Why people demand more to give up what they own than to get it',
    icon: PiGift,
    href: '/endowment-effect/',
    category: 'Behavioral',
  },
  {
    label: 'Social Preferences',
    description:
      'People care about fairness and others—not just their own payoff',
    icon: PiHeart,
    href: '/social-preferences/',
    category: 'Behavioral',
  },
  {
    label: 'Overconfidence Bias',
    description:
      'Systematically overestimating your skills, forecasts, and control',
    icon: PiCrown,
    href: '/overconfidence-bias/',
    category: 'Behavioral',
  },
  {
    label: 'Human Capital',
    description: 'Investing in people as a driver of productivity and growth',
    icon: PiGraduationCap,
    href: '/human-capital/',
    category: 'Development & Growth',
  },
  {
    label: 'Poverty Traps',
    description: 'The self-reinforcing cycles that keep the poor poor',
    icon: PiSneaker,
    href: '/poverty-traps/',
    category: 'Development & Growth',
  },
  {
    label: 'Migration Economics',
    description:
      'Why people move, what they gain, and how it reshapes economies',
    icon: PiAirplane,
    href: '/migration-economics/',
    category: 'Development & Growth',
  },
];

const HomePage: NextPage = () => {
  return (
    <HomeTemplate
      appName="Economics"
      description="Explore game theory and economic concepts."
      items={ITEMS}
    />
  );
};

export default HomePage;
