'use client';

import { HomeTemplate } from '@/components/templates/HomeTemplate';
import { NextPage } from 'next';
import { IconType } from 'react-icons';
import {
  PiAirplane,
  PiArrowLineUp,
  PiArrowsClockwise,
  PiArrowsCounterClockwise,
  PiArrowsLeftRight,
  PiBank,
  PiBoundingBox,
  PiBrain,
  PiBriefcase,
  PiBuildingOffice,
  PiChartBar,
  PiChartLine,
  PiChartLineDown,
  PiChartLineUp,
  PiChartPie,
  PiChartScatter,
  PiClock,
  PiClockCountdown,
  PiCoins,
  PiCrosshair,
  PiCrown,
  PiDna,
  PiEquals,
  PiFactory,
  PiFeather,
  PiFlowArrow,
  PiGameController,
  PiGauge,
  PiGift,
  PiGlobe,
  PiGlobeHemisphereWest,
  PiGraduationCap,
  PiGraph,
  PiGridFour,
  PiHandCoins,
  PiHandshake,
  PiHeart,
  PiIntersect,
  PiLightbulb,
  PiMegaphone,
  PiMoney,
  PiPiggyBank,
  PiRepeat,
  PiShield,
  PiShoppingCart,
  PiSmileySad,
  PiSneaker,
  PiSquaresFour,
  PiStack,
  PiStrategy,
  PiTag,
  PiTarget,
  PiTestTube,
  PiTreeStructure,
  PiTrendDown,
  PiTrendUp,
  PiUserMinus,
  PiUsers,
  PiUsersThree,
  PiWallet,
  PiWarning,
  PiWarningCircle,
  PiWaveSine,
  PiWind,
} from 'react-icons/pi';

type Item = {
  label: string;
  description: string;
  icon: IconType;
  href: string;
  gameHref?: string;
  badge?: string;
  category: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
};

const ITEMS: Item[] = [
  {
    label: "Prisoner's Dilemma",
    description: 'Iterated game theory against AI strategies',
    icon: PiStrategy,
    href: '/prisoners-dilemma/',
    badge: 'Nobel 1994',
    category: 'Game Theory',
    difficulty: 'Beginner',
  },
  {
    label: 'Nash Equilibrium',
    description: 'The stable point where no one wants to deviate alone',
    icon: PiTarget,
    href: '/nash-equilibrium/',
    badge: 'Nobel 1994',
    category: 'Game Theory',
    difficulty: 'Intermediate',
  },
  {
    label: 'Tragedy of the Commons',
    description: 'Why shared resources get overused',
    icon: PiGlobe,
    href: '/tragedy-of-the-commons/',
    badge: 'Nobel 2009',
    category: 'Public & Macro',
    difficulty: 'Beginner',
  },
  {
    label: 'Public Goods Dilemma',
    description: 'How free-riding undermines shared goods',
    icon: PiUsersThree,
    href: '/public-goods-dilemma/',
    category: 'Public & Macro',
    difficulty: 'Beginner',
  },
  {
    label: 'Opportunity Cost',
    description: 'The real cost of every choice and trade',
    icon: PiArrowsLeftRight,
    href: '/opportunity-cost/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Moral Hazard',
    description: 'When insurance changes behavior—and someone else pays',
    icon: PiShield,
    href: '/moral-hazard/',
    badge: 'Nobel 2001',
    category: 'Information & Risk',
    difficulty: 'Intermediate',
  },
  {
    label: 'Auction Theory',
    description: 'How bidding rules shape who wins and what they pay',
    icon: PiHandshake,
    href: '/auction-theory/',
    badge: 'Nobel 1996 · 2020',
    category: 'Game Theory',
    difficulty: 'Advanced',
  },
  {
    label: 'Bayesian Updating',
    description: 'How rational agents revise beliefs with new evidence',
    icon: PiLightbulb,
    href: '/bayesian-updating/',
    category: 'Behavioral',
    difficulty: 'Intermediate',
  },
  {
    label: 'Prospect Theory',
    description: 'Why losses loom larger than gains in every decision',
    icon: PiChartLineDown,
    href: '/prospect-theory/',
    badge: 'Nobel 2002',
    category: 'Behavioral',
    difficulty: 'Intermediate',
  },
  {
    label: 'Mechanism Design',
    description:
      'Designing rules so self-interested players produce good outcomes',
    icon: PiSquaresFour,
    href: '/mechanism-design/',
    badge: 'Nobel 2007',
    category: 'Game Theory',
    difficulty: 'Advanced',
  },
  {
    label: 'Nudge & Behavioral Econ',
    description:
      'How choice architecture steers decisions without forcing them',
    icon: PiFeather,
    href: '/nudge-and-behavioral-economics/',
    badge: 'Nobel 2017',
    category: 'Behavioral',
    difficulty: 'Beginner',
  },
  {
    label: 'Causal Inference',
    description: 'Moving beyond correlation to find true cause and effect',
    icon: PiFlowArrow,
    href: '/causal-inference/',
    badge: 'Nobel 2021',
    category: 'Information & Risk',
    difficulty: 'Advanced',
  },
  {
    label: 'Development RCTs',
    description: 'Randomized experiments to discover what reduces poverty',
    icon: PiTestTube,
    href: '/development-rcts/',
    badge: 'Nobel 2019',
    category: 'Development & Growth',
    difficulty: 'Advanced',
  },
  {
    label: 'Time Inconsistency',
    description: 'Why commitments made today often fail tomorrow',
    icon: PiClockCountdown,
    href: '/time-inconsistency/',
    badge: 'Nobel 2004',
    category: 'Behavioral',
    difficulty: 'Intermediate',
  },
  {
    label: 'Market Microstructure',
    description: 'How the mechanics of trading shape prices and liquidity',
    icon: PiChartLine,
    href: '/market-microstructure/',
    category: 'Information & Risk',
    difficulty: 'Advanced',
  },
  {
    label: 'Institutions & Growth',
    description: 'Why the rules of society decide national prosperity',
    icon: PiBank,
    href: '/institutions-and-growth/',
    badge: 'Nobel 1993 · 2024',
    category: 'Development & Growth',
    difficulty: 'Intermediate',
  },
  {
    label: 'Supply & Demand',
    description: 'The two forces that set nearly every market price',
    icon: PiChartLineUp,
    href: '/supply-and-demand/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Elasticity',
    description: 'How strongly buyers and sellers respond to price changes',
    icon: PiGraph,
    href: '/elasticity/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Marginal Utility',
    description: 'Why the next unit is worth a little less than the last',
    icon: PiArrowLineUp,
    href: '/marginal-utility/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Zero-Sum Games',
    description: "Games where one player's gain is another's loss",
    icon: PiArrowsCounterClockwise,
    href: '/zero-sum-games/',
    category: 'Game Theory',
    difficulty: 'Beginner',
  },
  {
    label: 'Externalities',
    description: 'When your actions affect strangers—for better or worse',
    icon: PiWind,
    href: '/externalities/',
    category: 'Public & Macro',
    difficulty: 'Beginner',
  },
  {
    label: 'Adverse Selection',
    description: 'Hidden information that can collapse a market',
    icon: PiWarning,
    href: '/adverse-selection/',
    category: 'Information & Risk',
    difficulty: 'Intermediate',
  },
  {
    label: 'Monopoly & Market Power',
    description: 'When one seller controls the market',
    icon: PiBuildingOffice,
    href: '/monopoly-and-market-power/',
    category: 'Markets & Pricing',
    difficulty: 'Intermediate',
  },
  {
    label: 'Oligopoly',
    description: 'A few big firms, each watching the others',
    icon: PiChartPie,
    href: '/oligopoly/',
    category: 'Game Theory',
    difficulty: 'Intermediate',
  },
  {
    label: 'Trade & Tariffs',
    description: 'Why trade helps—and what tariffs really cost',
    icon: PiGlobeHemisphereWest,
    href: '/trade-and-tariffs/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Behavioral Heuristics',
    description: 'The mental shortcuts that help—and sometimes mislead',
    icon: PiBrain,
    href: '/behavioral-heuristics/',
    category: 'Behavioral',
    difficulty: 'Beginner',
  },
  {
    label: 'Signaling',
    description: 'Proving about yourself what others cannot see',
    icon: PiMegaphone,
    href: '/signaling/',
    category: 'Information & Risk',
    difficulty: 'Intermediate',
  },
  {
    label: 'Public Choice',
    description: 'The economics of politics and self-interested policymakers',
    icon: PiUsers,
    href: '/public-choice/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'Keynesian Economics',
    description: 'Why recessions can get stuck—and how government responds',
    icon: PiPiggyBank,
    href: '/keynesian-economics/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'Monetary Policy',
    description: 'How central banks steer money, rates, and inflation',
    icon: PiCoins,
    href: '/monetary-policy/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'Labor Markets',
    description: 'How wages and jobs are set—and the minimum-wage debate',
    icon: PiBriefcase,
    href: '/labor-markets/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Economic Inequality',
    description: 'How income and wealth are distributed across a population',
    icon: PiTrendDown,
    href: '/economic-inequality/',
    category: 'Development & Growth',
    difficulty: 'Beginner',
  },
  {
    label: 'Repeated Games & Tit-for-Tat',
    description:
      'How cooperation emerges when the same game is played again and again',
    icon: PiRepeat,
    href: '/repeated-games/',
    category: 'Game Theory',
    difficulty: 'Intermediate',
  },
  {
    label: 'Backward Induction',
    description: 'Solving games by reasoning from the last move to the first',
    icon: PiTreeStructure,
    href: '/backward-induction/',
    category: 'Game Theory',
    difficulty: 'Intermediate',
  },
  {
    label: 'Bargaining Theory',
    description:
      'How threats, patience, and outside options shape negotiated splits',
    icon: PiHandCoins,
    href: '/bargaining-theory/',
    category: 'Game Theory',
    difficulty: 'Advanced',
  },
  {
    label: 'Coordination Games',
    description: 'When everyone must match on an action—and anything works',
    icon: PiGridFour,
    href: '/coordination-games/',
    category: 'Game Theory',
    difficulty: 'Beginner',
  },
  {
    label: 'Evolutionary Game Theory',
    description:
      'How strategies spread through a population by fitness, not choice',
    icon: PiDna,
    href: '/evolutionary-game-theory/',
    category: 'Game Theory',
    difficulty: 'Advanced',
  },
  {
    label: 'Game Theory Basics',
    description: 'The language of strategy, payoffs, and rational play',
    icon: PiGameController,
    href: '/game-theory-basics/',
    category: 'Game Theory',
    difficulty: 'Beginner',
  },
  {
    label: 'Imperfect Competition',
    description: 'When firms have some price power—but face rivals',
    icon: PiStack,
    href: '/imperfect-competition/',
    category: 'Markets & Pricing',
    difficulty: 'Advanced',
  },
  {
    label: 'Price Discrimination',
    description: 'Charging different people different prices for the same good',
    icon: PiTag,
    href: '/price-discrimination/',
    category: 'Markets & Pricing',
    difficulty: 'Intermediate',
  },
  {
    label: 'Consumer Theory',
    description: 'How rational consumers choose between goods within a budget',
    icon: PiShoppingCart,
    href: '/consumer-theory/',
    category: 'Markets & Pricing',
    difficulty: 'Intermediate',
  },
  {
    label: 'Production & Costs',
    description:
      'How firms turn inputs into output—and the shape of their costs',
    icon: PiFactory,
    href: '/production-and-costs/',
    category: 'Markets & Pricing',
    difficulty: 'Intermediate',
  },
  {
    label: 'Perfect Competition',
    description: 'The idealized market where no one can influence price',
    icon: PiEquals,
    href: '/perfect-competition/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Time Value of Money',
    description: 'Why a dollar today is worth more than a dollar tomorrow',
    icon: PiClock,
    href: '/time-value-of-money/',
    category: 'Markets & Pricing',
    difficulty: 'Beginner',
  },
  {
    label: 'Market Failures',
    description:
      'When free markets alone produce socially inefficient outcomes',
    icon: PiWarningCircle,
    href: '/market-failures/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'GDP & National Accounts',
    description: 'How economists measure the size and growth of an economy',
    icon: PiChartBar,
    href: '/gdp-and-national-accounts/',
    category: 'Public & Macro',
    difficulty: 'Beginner',
  },
  {
    label: 'Aggregate Demand & Supply',
    description: 'The economy-wide version of supply and demand',
    icon: PiIntersect,
    href: '/aggregate-demand-supply/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'The Phillips Curve',
    description: 'Does lower unemployment always mean higher inflation?',
    icon: PiTrendUp,
    href: '/phillips-curve/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'Business Cycles',
    description: 'The recurring pattern of expansion and contraction',
    icon: PiWaveSine,
    href: '/business-cycles/',
    category: 'Public & Macro',
    difficulty: 'Beginner',
  },
  {
    label: 'Fiscal Policy',
    description: 'How government spending and taxation steer the economy',
    icon: PiMoney,
    href: '/fiscal-policy/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'The IS-LM Model',
    description: 'How goods and money markets interact to set output and rates',
    icon: PiCrosshair,
    href: '/is-lm-model/',
    category: 'Public & Macro',
    difficulty: 'Advanced',
  },
  {
    label: "Unemployment & Okun's Law",
    description:
      'Why people are out of work—and how joblessness moves with growth',
    icon: PiUserMinus,
    href: '/unemployment-okuns-law/',
    category: 'Public & Macro',
    difficulty: 'Intermediate',
  },
  {
    label: 'Efficient Market Hypothesis',
    description:
      'The theory that prices instantly reflect all available information',
    icon: PiChartScatter,
    href: '/efficient-market-hypothesis/',
    category: 'Finance',
    difficulty: 'Advanced',
  },
  {
    label: 'CAPM & Risk',
    description:
      'Putting a price on risk through beta and the security market line',
    icon: PiGauge,
    href: '/capm-and-risk/',
    category: 'Finance',
    difficulty: 'Advanced',
  },
  {
    label: 'Behavioral Finance',
    description: 'How psychology creates mispricing and market anomalies',
    icon: PiSmileySad,
    href: '/behavioral-finance/',
    category: 'Finance',
    difficulty: 'Intermediate',
  },
  {
    label: 'Portfolio Theory',
    description: 'How diversification is the only free lunch in investing',
    icon: PiBoundingBox,
    href: '/portfolio-theory/',
    category: 'Finance',
    difficulty: 'Advanced',
  },
  {
    label: 'Arbitrage',
    description: 'Buying cheap and selling dear at the same moment',
    icon: PiArrowsClockwise,
    href: '/arbitrage/',
    category: 'Finance',
    difficulty: 'Intermediate',
  },
  {
    label: 'Mental Accounting',
    description: 'Treating money differently depending on where it comes from',
    icon: PiWallet,
    href: '/mental-accounting/',
    category: 'Behavioral',
    difficulty: 'Beginner',
  },
  {
    label: 'The Endowment Effect',
    description:
      'Why people demand more to give up what they own than to get it',
    icon: PiGift,
    href: '/endowment-effect/',
    category: 'Behavioral',
    difficulty: 'Beginner',
  },
  {
    label: 'Social Preferences',
    description:
      'People care about fairness and others—not just their own payoff',
    icon: PiHeart,
    href: '/social-preferences/',
    category: 'Behavioral',
    difficulty: 'Intermediate',
  },
  {
    label: 'Overconfidence Bias',
    description:
      'Systematically overestimating your skills, forecasts, and control',
    icon: PiCrown,
    href: '/overconfidence-bias/',
    category: 'Behavioral',
    difficulty: 'Beginner',
  },
  {
    label: 'Human Capital',
    description: 'Investing in people as a driver of productivity and growth',
    icon: PiGraduationCap,
    href: '/human-capital/',
    category: 'Development & Growth',
    difficulty: 'Beginner',
  },
  {
    label: 'Poverty Traps',
    description: 'The self-reinforcing cycles that keep the poor poor',
    icon: PiSneaker,
    href: '/poverty-traps/',
    category: 'Development & Growth',
    difficulty: 'Intermediate',
  },
  {
    label: 'Migration Economics',
    description:
      'Why people move, what they gain, and how it reshapes economies',
    icon: PiAirplane,
    href: '/migration-economics/',
    category: 'Development & Growth',
    difficulty: 'Intermediate',
  },
];

const GAMES: Record<string, string> = {
  '/prisoners-dilemma/': '/prisoners-dilemma/versus',
  '/nash-equilibrium/': '/nash-equilibrium/solve',
  '/tragedy-of-the-commons/': '/tragedy-of-the-commons/harvest',
  '/public-goods-dilemma/': '/public-goods-dilemma/contribute',
  '/opportunity-cost/': '/opportunity-cost/trade-offs',
  '/moral-hazard/': '/moral-hazard/insurance',
  '/auction-theory/': '/auction-theory/auction',
  '/bayesian-updating/': '/bayesian-updating/monty-hall',
  '/prospect-theory/': '/prospect-theory/framing',
  '/mechanism-design/': '/mechanism-design/reveal',
  '/nudge-and-behavioral-economics/': '/nudge-and-behavioral-economics/choice',
  '/causal-inference/': '/causal-inference/experiments',
  '/development-rcts/': '/development-rcts/experiment',
  '/time-inconsistency/': '/time-inconsistency/savings',
  '/market-microstructure/': '/market-microstructure/order-book',
  '/institutions-and-growth/': '/institutions-and-growth/lab',
  '/supply-and-demand/': '/supply-and-demand/price-lab',
  '/elasticity/': '/elasticity/pricing',
  '/marginal-utility/': '/marginal-utility/lab',
  '/zero-sum-games/': '/zero-sum-games/rps',
  '/externalities/': '/externalities/pigou',
  '/adverse-selection/': '/adverse-selection/lemons',
  '/monopoly-and-market-power/': '/monopoly-and-market-power/pricing',
  '/oligopoly/': '/oligopoly/cournot',
  '/trade-and-tariffs/': '/trade-and-tariffs/lab',
  '/behavioral-heuristics/': '/behavioral-heuristics/lab',
  '/signaling/': '/signaling/job-market',
  '/public-choice/': '/public-choice/voting',
  '/keynesian-economics/': '/keynesian-economics/cross',
  '/monetary-policy/': '/monetary-policy/interest',
  '/labor-markets/': '/labor-markets/wage',
  '/economic-inequality/': '/economic-inequality/lorenz',
  '/repeated-games/': '/repeated-games/tournament',
  '/backward-induction/': '/backward-induction/rollback',
  '/bargaining-theory/': '/bargaining-theory/ultimatum',
  '/coordination-games/': '/coordination-games/stag-hunt',
  '/evolutionary-game-theory/': '/evolutionary-game-theory/replicator',
  '/game-theory-basics/': '/game-theory-basics/matrix',
  '/imperfect-competition/': '/imperfect-competition/lab',
  '/price-discrimination/': '/price-discrimination/split',
  '/consumer-theory/': '/consumer-theory/utility',
  '/production-and-costs/': '/production-and-costs/lab',
  '/perfect-competition/': '/perfect-competition/firm',
  '/time-value-of-money/': '/time-value-of-money/lab',
  '/market-failures/': '/market-failures/policies',
  '/gdp-and-national-accounts/': '/gdp-and-national-accounts/aggregate',
  '/aggregate-demand-supply/': '/aggregate-demand-supply/shocks',
  '/phillips-curve/': '/phillips-curve/tradeoff',
  '/business-cycles/': '/business-cycles/predict',
  '/fiscal-policy/': '/fiscal-policy/stimulus',
  '/is-lm-model/': '/is-lm-model/equilibrium',
  '/unemployment-okuns-law/': '/unemployment-okuns-law/lab',
  '/efficient-market-hypothesis/': '/efficient-market-hypothesis/random-walk',
  '/capm-and-risk/': '/capm-and-risk/portfolio',
  '/behavioral-finance/': '/behavioral-finance/bubble',
  '/portfolio-theory/': '/portfolio-theory/frontier',
  '/arbitrage/': '/arbitrage/triangular',
  '/mental-accounting/': '/mental-accounting/scenarios',
  '/endowment-effect/': '/endowment-effect/trade',
  '/social-preferences/': '/social-preferences/dictator',
  '/overconfidence-bias/': '/overconfidence-bias/calibration',
  '/human-capital/': '/human-capital/decision',
  '/poverty-traps/': '/poverty-traps/escape',
  '/migration-economics/': '/migration-economics/moves',
};

const HomePage: NextPage = () => {
  return (
    <HomeTemplate
      appName="Economics"
      description="Explore game theory and economic concepts."
      items={ITEMS.map((item) => ({
        ...item,
        ...(GAMES[item.href] ? { gameHref: GAMES[item.href] } : {}),
      }))}
    />
  );
};

export default HomePage;
