import-countries:
	yarn ts-node ./scripts/import/countries

import-games:
	yarn ts-node ./scripts/import/games

import-openings:
	yarn ts-node ./scripts/import/openings

import-pgn:
	yarn ts-node ./scripts/import/pgn

import-players:
	yarn ts-node ./scripts/import/players
