export const borders: Record<string, string[]> = {
  Afghanistan: [
    'Pakistan',
    'Iran',
    'Turkmenistan',
    'Uzbekistan',
    'Tajikistan',
    'China',
  ],
  Albania: ['Greece', 'North Macedonia', 'Kosovo', 'Montenegro'],
  Algeria: [
    'Tunisia',
    'Libya',
    'Niger',
    'Mali',
    'Mauritania',
    'Morocco',
    'Western Sahara',
  ],
  Angola: ['Namibia', 'Zambia', 'DR Congo', 'Republic of the Congo'],
  Argentina: ['Chile', 'Bolivia', 'Paraguay', 'Brazil', 'Uruguay'],
  Armenia: ['Turkey', 'Georgia', 'Azerbaijan', 'Iran'],
  Australia: [],
  Austria: [
    'Germany',
    'Czech Republic',
    'Slovakia',
    'Hungary',
    'Slovenia',
    'Italy',
    'Switzerland',
    'Liechtenstein',
  ],
  Azerbaijan: ['Russia', 'Georgia', 'Armenia', 'Iran', 'Turkey'],
  Bangladesh: ['India', 'Myanmar'],
  Belarus: ['Poland', 'Lithuania', 'Latvia', 'Russia', 'Ukraine'],
  Belgium: ['France', 'Netherlands', 'Germany', 'Luxembourg'],
  Belize: ['Mexico', 'Guatemala'],
  Benin: ['Niger', 'Burkina Faso', 'Togo', 'Nigeria'],
  Bhutan: ['China', 'India'],
  Bolivia: ['Brazil', 'Paraguay', 'Argentina', 'Chile', 'Peru'],
  'Bosnia and Herzegovina': ['Croatia', 'Serbia', 'Montenegro'],
  Botswana: ['Namibia', 'Zambia', 'Zimbabwe', 'South Africa'],
  Brazil: [
    'Argentina',
    'Bolivia',
    'Colombia',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
    'France',
  ],
  Brunei: ['Malaysia'],
  Bulgaria: ['Romania', 'Serbia', 'North Macedonia', 'Greece', 'Turkey'],
  'Burkina Faso': ['Mali', 'Niger', 'Benin', 'Togo', 'Ghana', 'Ivory Coast'],
  Burundi: ['Rwanda', 'Tanzania', 'DR Congo'],
  Cambodia: ['Thailand', 'Laos', 'Vietnam'],
  Cameroon: [
    'Nigeria',
    'Chad',
    'Central African Republic',
    'Republic of the Congo',
    'Gabon',
    'Equatorial Guinea',
  ],
  Canada: ['United States'],
  'Central African Republic': [
    'Chad',
    'Sudan',
    'South Sudan',
    'DR Congo',
    'Republic of the Congo',
    'Cameroon',
  ],
  Chad: [
    'Libya',
    'Niger',
    'Nigeria',
    'Cameroon',
    'Central African Republic',
    'Sudan',
  ],
  Chile: ['Argentina', 'Bolivia', 'Peru'],
  China: [
    'Afghanistan',
    'Bhutan',
    'Myanmar',
    'India',
    'Kazakhstan',
    'Kyrgyzstan',
    'Laos',
    'Mongolia',
    'Nepal',
    'North Korea',
    'Pakistan',
    'Russia',
    'Tajikistan',
    'Vietnam',
  ],
  Colombia: ['Venezuela', 'Brazil', 'Peru', 'Ecuador', 'Panama'],
  'Republic of the Congo': [
    'Cameroon',
    'Central African Republic',
    'DR Congo',
    'Gabon',
    'Angola',
  ],
  'Costa Rica': ['Nicaragua', 'Panama'],
  Croatia: [
    'Slovenia',
    'Hungary',
    'Serbia',
    'Bosnia and Herzegovina',
    'Montenegro',
  ],
  Cuba: [],
  'Czech Republic': ['Germany', 'Poland', 'Slovakia', 'Austria'],
  Denmark: ['Germany'],
  Djibouti: ['Ethiopia', 'Eritrea', 'Somalia'],
  'Dominican Republic': ['Haiti'],
  'DR Congo': [
    'Republic of the Congo',
    'Central African Republic',
    'South Sudan',
    'Uganda',
    'Rwanda',
    'Burundi',
    'Tanzania',
    'Zambia',
    'Angola',
  ],
  Ecuador: ['Colombia', 'Peru'],
  Egypt: ['Libya', 'Sudan', 'Palestine', 'Israel'],
  'El Salvador': ['Guatemala', 'Honduras'],
  'Equatorial Guinea': ['Cameroon', 'Gabon'],
  Eritrea: ['Ethiopia', 'Djibouti', 'Sudan'],
  Estonia: ['Latvia', 'Russia'],
  Eswatini: ['South Africa', 'Mozambique'],
  Ethiopia: ['Eritrea', 'Djibouti', 'Somalia', 'Kenya', 'South Sudan', 'Sudan'],
  Fiji: [],
  Finland: ['Norway', 'Sweden', 'Russia'],
  France: [
    'Belgium',
    'Luxembourg',
    'Germany',
    'Switzerland',
    'Italy',
    'Spain',
    'Andorra',
    'Monaco',
  ],
  Gabon: ['Equatorial Guinea', 'Cameroon', 'Republic of the Congo'],
  Gambia: ['Senegal'],
  Georgia: ['Russia', 'Turkey', 'Armenia', 'Azerbaijan'],
  Germany: [
    'Denmark',
    'Poland',
    'Czech Republic',
    'Austria',
    'Switzerland',
    'France',
    'Luxembourg',
    'Belgium',
    'Netherlands',
  ],
  Ghana: ['Ivory Coast', 'Burkina Faso', 'Togo'],
  Greece: ['Albania', 'North Macedonia', 'Bulgaria', 'Turkey'],
  Guatemala: ['Mexico', 'Belize', 'Honduras', 'El Salvador'],
  Guinea: [
    'Guinea-Bissau',
    'Senegal',
    'Mali',
    'Ivory Coast',
    'Liberia',
    'Sierra Leone',
  ],
  'Guinea-Bissau': ['Senegal', 'Guinea'],
  Guyana: ['Venezuela', 'Brazil', 'Suriname'],
  Haiti: ['Dominican Republic'],
  Honduras: ['Guatemala', 'El Salvador', 'Nicaragua'],
  Hungary: [
    'Slovakia',
    'Ukraine',
    'Romania',
    'Serbia',
    'Croatia',
    'Slovenia',
    'Austria',
  ],
  Iceland: [],
  India: ['Pakistan', 'China', 'Nepal', 'Bhutan', 'Bangladesh', 'Myanmar'],
  Indonesia: ['Malaysia', 'Papua New Guinea', 'Timor'],
  Iran: [
    'Iraq',
    'Turkey',
    'Armenia',
    'Azerbaijan',
    'Turkmenistan',
    'Afghanistan',
    'Pakistan',
  ],
  Iraq: ['Turkey', 'Syria', 'Jordan', 'Saudi Arabia', 'Kuwait', 'Iran'],
  Ireland: ['United Kingdom'],
  Israel: ['Egypt', 'Jordan', 'Syria', 'Lebanon', 'Palestine'],
  Italy: [
    'France',
    'Switzerland',
    'Austria',
    'Slovenia',
    'San Marino',
    'Vatican',
  ],
  'Ivory Coast': ['Liberia', 'Guinea', 'Mali', 'Burkina Faso', 'Ghana'],
  Jamaica: [],
  Japan: [],
  Jordan: ['Iraq', 'Syria', 'Saudi Arabia', 'Israel', 'Palestine'],
  Kazakhstan: ['Russia', 'China', 'Kyrgyzstan', 'Uzbekistan', 'Turkmenistan'],
  Kenya: ['Ethiopia', 'Somalia', 'South Sudan', 'Uganda', 'Tanzania'],
  Kosovo: ['Serbia', 'North Macedonia', 'Albania', 'Montenegro'],
  Kuwait: ['Iraq', 'Saudi Arabia'],
  Kyrgyzstan: ['Kazakhstan', 'China', 'Kyrgyzstan', 'Uzbekistan'],
  Laos: ['China', 'Myanmar', 'Thailand', 'Cambodia', 'Vietnam'],
  Latvia: ['Estonia', 'Lithuania', 'Belarus', 'Russia'],
  Lebanon: ['Syria', 'Israel'],
  Lesotho: ['South Africa'],
  Liberia: ['Sierra Leone', 'Guinea', 'Ivory Coast'],
  Libya: ['Tunisia', 'Algeria', 'Niger', 'Chad', 'Sudan', 'Egypt'],
  Liechtenstein: ['Austria', 'Switzerland'],
  Lithuania: ['Latvia', 'Belarus', 'Poland', 'Russia'],
  Luxembourg: ['Belgium', 'Germany', 'France'],
  Madagascar: [],
  Malawi: ['Mozambique', 'Tanzania', 'Zambia'],
  Malaysia: ['Thailand', 'Indonesia', 'Brunei'],
  Mali: [
    'Algeria',
    'Niger',
    'Burkina Faso',
    'Ivory Coast',
    'Guinea',
    'Senegal',
    'Mauritania',
  ],
  Mauritania: ['Algeria', 'Mali', 'Senegal', 'Western Sahara', 'Morocco'],
  Mexico: ['United States', 'Guatemala', 'Belize'],
  Moldova: ['Romania', 'Ukraine'],
  Monaco: ['France'],
  Mongolia: ['Russia', 'China'],
  Montenegro: [
    'Croatia',
    'Bosnia and Herzegovina',
    'Serbia',
    'Kosovo',
    'Albania',
  ],
  Morocco: ['Algeria', 'Western Sahara', 'Mauritania'],
  Mozambique: [
    'Tanzania',
    'Malawi',
    'Zambia',
    'Zimbabwe',
    'South Africa',
    'Eswatini',
  ],
  Myanmar: ['India', 'Bangladesh', 'China', 'Laos', 'Thailand'],
  Namibia: ['Angola', 'Zambia', 'Zimbabwe', 'Botswana', 'South Africa'],
  Nepal: ['China', 'India'],
  Netherlands: ['Belgium', 'Germany'],
  'New Zealand': [],
  Nicaragua: ['Honduras', 'Costa Rica'],
  Niger: [
    'Algeria',
    'Libya',
    'Chad',
    'Nigeria',
    'Benin',
    'Burkina Faso',
    'Mali',
  ],
  Nigeria: ['Niger', 'Chad', 'Cameroon', 'Benin'],
  'North Korea': ['China', 'South Korea', 'Russia'],
  'North Macedonia': ['Kosovo', 'Serbia', 'Bulgaria', 'Greece', 'Albania'],
  Norway: ['Sweden', 'Finland', 'Russia'],
  Oman: ['Yemen', 'Saudi Arabia', 'United Arab Emirates'],
  Pakistan: ['India', 'China', 'Afghanistan', 'Iran'],
  Palestine: ['Israel', 'Egypt', 'Jordan'],
  Panama: ['Colombia', 'Costa Rica'],
  'Papua New Guinea': ['Indonesia'],
  Paraguay: ['Bolivia', 'Brazil', 'Argentina'],
  Peru: ['Ecuador', 'Colombia', 'Brazil', 'Bolivia', 'Chile'],
  Philippines: [],
  Poland: [
    'Germany',
    'Czech Republic',
    'Slovakia',
    'Ukraine',
    'Belarus',
    'Lithuania',
    'Russia',
  ],
  Portugal: ['Spain'],
  Qatar: ['Saudi Arabia'],
  Romania: ['Hungary', 'Serbia', 'Bulgaria', 'Moldova', 'Ukraine'],
  Russia: [
    'Norway',
    'Finland',
    'Estonia',
    'Latvia',
    'Lithuania',
    'Poland',
    'Belarus',
    'Ukraine',
    'Georgia',
    'Azerbaijan',
    'Kazakhstan',
    'China',
    'Mongolia',
    'North Korea',
  ],
  Rwanda: ['Uganda', 'Tanzania', 'Burundi', 'DR Congo'],
  'Saudi Arabia': [
    'Iraq',
    'Jordan',
    'Yemen',
    'Oman',
    'United Arab Emirates',
    'Qatar',
    'Kuwait',
  ],
  Senegal: ['Mauritania', 'Mali', 'Guinea', 'Guinea-Bissau', 'Gambia'],
  Serbia: [
    'Hungary',
    'Romania',
    'Bulgaria',
    'North Macedonia',
    'Kosovo',
    'Montenegro',
    'Bosnia and Herzegovina',
    'Croatia',
  ],
  'Sierra Leone': ['Guinea', 'Liberia'],
  Singapore: [],
  Slovakia: ['Czech Republic', 'Poland', 'Ukraine', 'Hungary', 'Austria'],
  Slovenia: ['Italy', 'Austria', 'Hungary', 'Croatia'],
  Somalia: ['Ethiopia', 'Djibouti', 'Kenya'],
  'South Africa': [
    'Namibia',
    'Botswana',
    'Zimbabwe',
    'Mozambique',
    'Eswatini',
    'Lesotho',
  ],
  'South Korea': ['North Korea'],
  'South Sudan': [
    'Sudan',
    'Ethiopia',
    'Kenya',
    'Uganda',
    'DR Congo',
    'Central African Republic',
  ],
  Spain: ['Portugal', 'France', 'Andorra', 'Morocco'],
  'Sri Lanka': [],
  Sudan: [
    'Egypt',
    'Libya',
    'Chad',
    'Central African Republic',
    'South Sudan',
    'Ethiopia',
    'Eritrea',
  ],
  Suriname: ['Guyana', 'Brazil', 'France'],
  Sweden: ['Norway', 'Finland'],
  Switzerland: ['Germany', 'France', 'Italy', 'Austria', 'Liechtenstein'],
  Syria: ['Turkey', 'Iraq', 'Jordan', 'Israel', 'Lebanon'],
  Tajikistan: ['Afghanistan', 'China', 'Kyrgyzstan', 'Uzbekistan'],
  Tanzania: [
    'Kenya',
    'Uganda',
    'Rwanda',
    'Burundi',
    'DR Congo',
    'Zambia',
    'Malawi',
    'Mozambique',
  ],
  Thailand: ['Myanmar', 'Laos', 'Cambodia', 'Malaysia'],
  Timor: ['Indonesia'],
  Togo: ['Ghana', 'Burkina Faso', 'Benin'],
  'Trinidad and Tobago': [],
  Tunisia: ['Algeria', 'Libya'],
  Turkey: [
    'Greece',
    'Bulgaria',
    'Georgia',
    'Armenia',
    'Azerbaijan',
    'Iran',
    'Iraq',
    'Syria',
  ],
  Turkmenistan: ['Kazakhstan', 'Uzbekistan', 'Afghanistan', 'Iran'],
  Uganda: ['South Sudan', 'Kenya', 'Tanzania', 'Rwanda', 'DR Congo'],
  Ukraine: [
    'Poland',
    'Slovakia',
    'Hungary',
    'Romania',
    'Moldova',
    'Belarus',
    'Russia',
  ],
  'United Arab Emirates': ['Saudi Arabia', 'Oman'],
  'United Kingdom': ['Ireland'],
  'United States': ['Canada', 'Mexico'],
  Uruguay: ['Brazil', 'Argentina'],
  Uzbekistan: [
    'Kazakhstan',
    'Kyrgyzstan',
    'Tajikistan',
    'Afghanistan',
    'Turkmenistan',
  ],
  Venezuela: ['Colombia', 'Brazil', 'Guyana'],
  Vietnam: ['China', 'Laos', 'Cambodia'],
  'Western Sahara': ['Morocco', 'Algeria', 'Mauritania'],
  Yemen: ['Saudi Arabia', 'Oman'],
  Zambia: [
    'DR Congo',
    'Tanzania',
    'Malawi',
    'Mozambique',
    'Zimbabwe',
    'Botswana',
    'Namibia',
    'Angola',
  ],
  Zimbabwe: ['Zambia', 'Mozambique', 'South Africa', 'Botswana'],
};
