import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Adjust',
    description: 'Brightness/Contrast',
    tags: ['image', 'effect', 'filter', 'photo'],
    emoji: '⚙️',
    onClick: open('image-adjust'),
  },
  {
    label: 'Blur Background',
    description: 'Image Effect',
    tags: [
      'filter',
      'photo',
      'bg',
      'backdrop',
      'background-removal',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '🌫️',
    onClick: open('image-blur-background'),
  },
  {
    label: 'Image Pixelate Face',
    description: '',
    tags: [],
    emoji: '🔧',
    onClick: open('image-pixelate-face'),
  },
  {
    label: 'Morphing',
    description: 'Grid-based morph',
    tags: ['image', 'effect', 'morph', 'warp', 'animation'],
    emoji: '🫠',
    onClick: open('image-morphing'),
  },
  {
    label: 'Photo Filters',
    description: 'Apply Filters',
    tags: ['image', 'effect'],
    emoji: '📸',
    onClick: open('image-photo-filters'),
  },
  {
    label: 'Shadow',
    description: 'Add Shadow',
    tags: ['image', 'effect', 'filter', 'photo'],
    emoji: '👤',
    onClick: open('image-shadow'),
  },
  {
    label: 'Side by Side',
    description: 'Combine',
    tags: ['image', 'effect', 'filter', 'photo'],
    emoji: '🔗',
    onClick: open('image-combiner-side-by-side'),
  },
  {
    label: 'Stacked',
    description: 'Combine',
    tags: ['image', 'effect', 'filter', 'photo'],
    emoji: '🔗',
    onClick: open('image-combiner-stacked'),
  },
  {
    label: 'Text',
    description: 'Add Text',
    tags: ['image', 'effect', 'filter', 'photo'],
    emoji: '✏️',
    onClick: open('image-text'),
  },
  {
    label: 'Transparent BG',
    description: 'Make Transparent',
    tags: ['image', 'effect', 'filter', 'photo'],
    emoji: '✨',
    onClick: open('image-transparent-bg'),
  },
  {
    label: 'Vignette',
    description: 'Vignette Effect',
    tags: ['image', 'filter', 'photo'],
    emoji: '🌑',
    onClick: open('image-vignette'),
  },
  {
    label: 'Watermark',
    description: 'Add Watermark',
    tags: ['image', 'effect', 'filter', 'photo', 'watermark-removal', 'logo'],
    emoji: '💧',
    onClick: open('image-watermark'),
  },
];
