import {
  PiArrowsClockwise,
  PiCircle,
  PiImage,
  PiPackage,
  PiRuler,
  PiScissors,
  PiSnowflake,
  PiStarFour,
} from 'react-icons/pi';
import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'B&W',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiCircle,
    onClick: open('image-bw'),
  },
  {
    label: 'Border',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiImage,
    onClick: open('image-border'),
  },
  {
    label: 'Compress',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'zip',
      'archive',
      'minify',
      'reduce-size',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiPackage,
    onClick: open('image-compress'),
  },
  {
    label: 'Crop',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'trim',
      'cut',
      'clip-image',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiScissors,
    onClick: open('image-crop'),
  },
  {
    label: 'Flip',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiArrowsClockwise,
    onClick: open('image-flip'),
  },
  {
    label: 'Pixelate',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiSnowflake,
    onClick: open('image-pixelate'),
  },
  {
    label: 'Resize',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'scale',
      'resize-image',
      'dimensions',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiRuler,
    onClick: open('image-resize'),
  },
  {
    label: 'Rotate',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'flip',
      'orientation',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiArrowsClockwise,
    onClick: open('image-rotate'),
  },
  {
    label: 'Round',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiCircle,
    onClick: open('image-round'),
  },
  {
    label: 'Sharpen',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    icon: PiStarFour,
    onClick: open('image-sharpen'),
  },
  {
    label: 'Split',
    description: 'Image Splitter',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
      'divide',
      'separate',
    ],
    icon: PiScissors,
    onClick: open('image-split'),
  },
];
