import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'B&W',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '⚫',
    onClick: open('image-bw'),
  },
  {
    label: 'Border',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '🖼️',
    onClick: open('image-border'),
  },
  {
    label: 'Compress',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'zip',
      'archive',
      'minify',
      'reduce-size',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '📦',
    onClick: open('image-compress'),
  },
  {
    label: 'Crop',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'trim',
      'cut',
      'clip-image',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '✂️',
    onClick: open('image-crop'),
  },
  {
    label: 'Flip',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '🔄',
    onClick: open('image-flip'),
  },
  {
    label: 'Pixelate',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '🧊',
    onClick: open('image-pixelate'),
  },
  {
    label: 'Resize',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'scale',
      'resize-image',
      'dimensions',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '📐',
    onClick: open('image-resize'),
  },
  {
    label: 'Rotate',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'flip',
      'orientation',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '🔄',
    onClick: open('image-rotate'),
  },
  {
    label: 'Round',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '⭕',
    onClick: open('image-round'),
  },
  {
    label: 'Sharpen',
    description: 'Image',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '💫',
    onClick: open('image-sharpen'),
  },
  {
    label: 'Split',
    description: 'Image Splitter',
    tags: [
      'edit',
      'photo-editor',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
      'divide',
      'separate',
    ],
    emoji: '✂️',
    onClick: open('image-split'),
  },
];
