import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Facebook',
    description: 'Video',
    tags: [
      'download',
      'media',
      'fb',
      'social',
      'meta',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    emoji: '⬇️',
    onClick: open('video-download-facebook'),
  },
  {
    label: 'Instagram',
    description: 'Video',
    tags: [
      'download',
      'media',
      'ig',
      'social',
      'photo',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    emoji: '⬇️',
    onClick: open('video-download-instagram'),
  },
  {
    label: 'TikTok',
    description: 'Video',
    tags: [
      'download',
      'media',
      'social',
      'short-video',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    emoji: '⬇️',
    onClick: open('video-download-tiktok'),
  },
  {
    label: 'Twitter/X',
    description: 'Video',
    tags: [
      'download',
      'media',
      'social',
      'tweet',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    emoji: '⬇️',
    onClick: open('video-download-twitter'),
  },
  {
    label: 'YouTube to Text',
    description: 'Video',
    tags: ['download', 'media', 'yt', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '⬇️',
    onClick: open('video-youtube-text'),
  },
  {
    label: 'YouTube Transcript',
    description: 'Video',
    tags: ['download', 'media', 'yt', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '⬇️',
    onClick: open('video-youtube-transcript'),
  },
];
