import { PiScissors } from 'react-icons/pi';
import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Compress',
    description: 'Video',
    tags: [
      'edit',
      'media',
      'zip',
      'archive',
      'minify',
      'reduce-size',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    icon: PiScissors,
    onClick: open('video-compress'),
  },
  {
    label: 'Crop',
    description: 'Video',
    tags: [
      'edit',
      'media',
      'trim',
      'cut',
      'clip-image',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    icon: PiScissors,
    onClick: open('video-crop'),
  },
  {
    label: 'Extract Audio',
    description: 'Video',
    tags: [
      'edit',
      'media',
      'sound',
      'music',
      'mp3',
      'wav',
      'ogg',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    icon: PiScissors,
    onClick: open('video-extract-audio'),
  },
  {
    label: 'Extract Frames',
    description: 'Video',
    tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
    icon: PiScissors,
    onClick: open('video-extract-frames'),
  },
  {
    label: 'Merge',
    description: 'Video',
    tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
    icon: PiScissors,
    onClick: open('video-merge'),
  },
  {
    label: 'Mute',
    description: 'Video',
    tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
    icon: PiScissors,
    onClick: open('video-mute'),
  },
  {
    label: 'Resize',
    description: 'Video',
    tags: [
      'edit',
      'media',
      'scale',
      'resize-image',
      'dimensions',
      'mp4',
      'movie',
      'clip',
      'footage',
    ],
    icon: PiScissors,
    onClick: open('video-resize'),
  },
  {
    label: 'Speed',
    description: 'Video',
    tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
    icon: PiScissors,
    onClick: open('video-speed'),
  },
  {
    label: 'Stabilize',
    description: 'Video',
    tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
    icon: PiScissors,
    onClick: open('video-stabilize'),
  },
  {
    label: 'Trim',
    description: 'Video',
    tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
    icon: PiScissors,
    onClick: open('video-trim'),
  },
];
