import {
  PiCamera,
  PiChartBar,
  PiHospital,
  PiImage,
  PiLock,
  PiMaskHappy,
  PiSquare,
  PiTestTube,
  PiUser,
} from 'react-icons/pi';
import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Base64',
    description: 'Decode/Encode',
    tags: ['image', 'create', 'photo', 'generator', 'base-64'],
    icon: PiLock,
    onClick: open('base64'),
  },
  {
    label: 'Breaking Bad',
    description: 'Element',
    tags: ['image', 'create', 'photo', 'generator'],
    icon: PiTestTube,
    onClick: open('breaking-bad'),
  },
  {
    label: 'Camera',
    description: 'Composition',
    tags: ['image', 'create', 'photo', 'generator'],
    icon: PiCamera,
    onClick: open('camera'),
  },
  {
    label: 'Chart Maker',
    description: 'Create Chart',
    tags: ['image', 'photo', 'generator'],
    icon: PiChartBar,
    onClick: open('chart-maker'),
  },
  {
    label: 'Collage',
    description: 'Photo Collage',
    tags: ['image', 'create', 'generator'],
    icon: PiImage,
    onClick: open('collage-maker'),
  },
  {
    label: 'House',
    description: 'M.D.',
    tags: ['image', 'create', 'photo', 'generator'],
    icon: PiHospital,
    onClick: open('house'),
  },
  {
    label: 'InstaSize',
    description: 'Square Fit',
    tags: ['image', 'create', 'photo', 'generator'],
    icon: PiCamera,
    onClick: open('instasize'),
  },
  {
    label: 'Meme Maker',
    description: 'Create Meme',
    tags: ['image', 'photo', 'generator', 'funny'],
    icon: PiMaskHappy,
    onClick: open('meme-maker'),
  },
  {
    label: 'Pixel',
    description: 'Art Grid',
    tags: ['image', 'create', 'photo', 'generator'],
    icon: PiSquare,
    onClick: open('pixel'),
  },
  {
    label: 'Profile',
    description: 'Photo Maker',
    tags: ['image', 'create', 'generator'],
    icon: PiUser,
    onClick: open('image-profile'),
  },
  {
    label: 'Social Preview',
    description: 'GitHub',
    tags: ['image', 'create', 'photo', 'generator'],
    icon: PiCamera,
    onClick: open('github-social-preview'),
  },
  {
    label: 'Thumbnails',
    description: 'YouTube',
    tags: ['image', 'create', 'photo', 'generator', 'yt', 'video', 'download'],
    icon: PiCamera,
    onClick: open('youtube-thumbnails'),
  },
];
