import { APP_NAME } from '@sunil/common/constants/app.constants';
import { Container } from '@sunil/shared/components/Container';
import { Footer } from '@sunil/shared/components/Footer';
import { Navbar } from '@sunil/shared/components/Navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: APP_NAME,
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" data-theme="light">
      <body
        style={{ background: 'transparent' }}
        className={`${inter.className} text-black`}>
        <Providers>
          <div className="flex h-screen flex-col">
            <Navbar />
            <div className="grow">
              <Container className="h-full">
                <div className="p-4 md:p-8 h-full">{children}</div>
              </Container>
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
