export interface ImageToolConfig {
  id: string;
  title: string;
  emoji: string;
  description: string;
  category: 'ai' | 'color' | 'convert' | 'create' | 'edit' | 'effect' | 'scan';
  inputFormat?: string;
  outputFormat?: string;
  outputExt?: string;
  mimeType?: string;
  accept?: string;
  isSvg?: boolean;
}

export const CATEGORIES: { key: string; label: string; emoji: string }[] = [
  { key: 'ai', label: 'AI', emoji: '🤖' },
  { key: 'color', label: 'Color', emoji: '🎨' },
  { key: 'convert', label: 'Convert', emoji: '🔄' },
  { key: 'create', label: 'Create', emoji: '✨' },
  { key: 'edit', label: 'Edit', emoji: '✏️' },
  { key: 'effect', label: 'Effect', emoji: '💫' },
  { key: 'scan', label: 'Scan', emoji: '📷' },
];

export const TOOLS: ImageToolConfig[] = [
  // ── AI ──────────────────────────────────────────────
  {
    id: 'ai-generate',
    title: 'Generate',
    emoji: '✨',
    description: 'AI Image Generation',
    category: 'ai',
  },
  {
    id: 'ai-remove-bg',
    title: 'Remove BG',
    emoji: '🖼️',
    description: 'Remove background from image',
    category: 'ai',
    accept: 'image/*',
  },
  {
    id: 'ai-remove-object',
    title: 'Remove Object',
    emoji: '🎯',
    description: 'Remove unwanted objects from images',
    category: 'ai',
    accept: 'image/*',
  },
  {
    id: 'ai-remove-person',
    title: 'Remove Person',
    emoji: '🚶',
    description: 'Remove people from images',
    category: 'ai',
    accept: 'image/*',
  },
  {
    id: 'ai-remove-watermark',
    title: 'Remove Watermark',
    emoji: '💧',
    description: 'Remove watermarks from images',
    category: 'ai',
    accept: 'image/*',
  },
  {
    id: 'ai-restore',
    title: 'Restore',
    emoji: '🔄',
    description: 'AI photo restoration',
    category: 'ai',
    accept: 'image/*',
  },
  {
    id: 'ai-unblur',
    title: 'Unblur',
    emoji: '👁️',
    description: 'Deblur and sharpen images',
    category: 'ai',
    accept: 'image/*',
  },
  {
    id: 'ai-upscale',
    title: 'Upscale',
    emoji: '🔍',
    description: 'Enlarge images with AI upscaling',
    category: 'ai',
    accept: 'image/*',
  },
  {
    id: 'ai-colorize',
    title: 'AI Colorize',
    emoji: '🎨',
    description: 'Add color to black & white photos',
    category: 'ai',
    accept: 'image/*',
  },

  // ── Color ────────────────────────────────────────────
  {
    id: 'colors',
    title: 'Colors',
    emoji: '🌈',
    description: 'Color picker and palette explorer',
    category: 'color',
  },
  {
    id: 'contrast-checker',
    title: 'Contrast Checker',
    emoji: '👁️',
    description: 'Check WCAG contrast ratios',
    category: 'color',
  },
  {
    id: 'gradient-generator',
    title: 'Gradient Generator',
    emoji: '🎨',
    description: 'Create custom CSS gradients',
    category: 'color',
  },
  {
    id: 'image-colorize',
    title: 'Image Colorize',
    emoji: '🎭',
    description: 'Apply color overlay to images',
    category: 'color',
    accept: 'image/*',
  },
  {
    id: 'image-dominant-color',
    title: 'Dominant Color',
    emoji: '🎯',
    description: 'Extract dominant colors from images',
    category: 'color',
    accept: 'image/*',
  },

  // ── Convert ──────────────────────────────────────────
  {
    id: 'image-convert-gif-to-jpg',
    title: 'GIF to JPG',
    emoji: '🔄',
    description: 'Convert GIF to JPG',
    category: 'convert',
    accept: '.gif,image/gif',
    outputFormat: 'image/jpeg',
    outputExt: 'jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: 'image-convert-gif-to-png',
    title: 'GIF to PNG',
    emoji: '🔄',
    description: 'Convert GIF to PNG',
    category: 'convert',
    accept: '.gif,image/gif',
    outputFormat: 'image/png',
    outputExt: 'png',
    mimeType: 'image/png',
  },
  {
    id: 'image-convert-heic-to-avif',
    title: 'HEIC to AVIF',
    emoji: '🔄',
    description: 'Convert HEIC to AVIF',
    category: 'convert',
    accept: '.heic',
    outputFormat: 'image/avif',
    outputExt: 'avif',
    mimeType: 'image/avif',
  },
  {
    id: 'image-convert-heic-to-jpg',
    title: 'HEIC to JPG',
    emoji: '🔄',
    description: 'Convert HEIC to JPG',
    category: 'convert',
    accept: '.heic',
    outputFormat: 'image/jpeg',
    outputExt: 'jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: 'image-convert-heic-to-png',
    title: 'HEIC to PNG',
    emoji: '🔄',
    description: 'Convert HEIC to PNG',
    category: 'convert',
    accept: '.heic',
    outputFormat: 'image/png',
    outputExt: 'png',
    mimeType: 'image/png',
  },
  {
    id: 'image-convert-jpg-to-avif',
    title: 'JPG to AVIF',
    emoji: '🔄',
    description: 'Convert JPG to AVIF',
    category: 'convert',
    accept: '.jpg,.jpeg,image/jpeg',
    outputFormat: 'image/avif',
    outputExt: 'avif',
    mimeType: 'image/avif',
  },
  {
    id: 'image-convert-jpg-to-gif',
    title: 'JPG to GIF',
    emoji: '🔄',
    description: 'Convert JPG to GIF',
    category: 'convert',
    accept: '.jpg,.jpeg,image/jpeg',
    outputFormat: 'image/gif',
    outputExt: 'gif',
    mimeType: 'image/gif',
  },
  {
    id: 'image-convert-jpg-to-png',
    title: 'JPG to PNG',
    emoji: '🔄',
    description: 'Convert JPG to PNG',
    category: 'convert',
    accept: '.jpg,.jpeg,image/jpeg',
    outputFormat: 'image/png',
    outputExt: 'png',
    mimeType: 'image/png',
  },
  {
    id: 'image-convert-jpg-to-svg',
    title: 'JPG to SVG',
    emoji: '🔄',
    description: 'Convert JPG to SVG',
    category: 'convert',
    accept: '.jpg,.jpeg,image/jpeg',
    outputFormat: 'image/svg+xml',
    outputExt: 'svg',
    mimeType: 'image/svg+xml',
    isSvg: true,
  },
  {
    id: 'image-convert-jpg-to-tiff',
    title: 'JPG to TIFF',
    emoji: '🔄',
    description: 'Convert JPG to TIFF',
    category: 'convert',
    accept: '.jpg,.jpeg,image/jpeg',
    outputFormat: 'image/tiff',
    outputExt: 'tiff',
    mimeType: 'image/tiff',
  },
  {
    id: 'image-convert-jpg-to-webp',
    title: 'JPG to WebP',
    emoji: '🔄',
    description: 'Convert JPG to WebP',
    category: 'convert',
    accept: '.jpg,.jpeg,image/jpeg',
    outputFormat: 'image/webp',
    outputExt: 'webp',
    mimeType: 'image/webp',
  },
  {
    id: 'image-convert-png-to-avif',
    title: 'PNG to AVIF',
    emoji: '🔄',
    description: 'Convert PNG to AVIF',
    category: 'convert',
    accept: '.png,image/png',
    outputFormat: 'image/avif',
    outputExt: 'avif',
    mimeType: 'image/avif',
  },
  {
    id: 'image-convert-png-to-eps',
    title: 'PNG to EPS',
    emoji: '🔄',
    description: 'Convert PNG to EPS (downloads as PNG)',
    category: 'convert',
    accept: '.png,image/png',
    outputFormat: 'image/png',
    outputExt: 'eps',
    mimeType: 'image/png',
  },
  {
    id: 'image-convert-png-to-gif',
    title: 'PNG to GIF',
    emoji: '🔄',
    description: 'Convert PNG to GIF',
    category: 'convert',
    accept: '.png,image/png',
    outputFormat: 'image/gif',
    outputExt: 'gif',
    mimeType: 'image/gif',
  },
  {
    id: 'image-convert-png-to-jpg',
    title: 'PNG to JPG',
    emoji: '🔄',
    description: 'Convert PNG to JPG',
    category: 'convert',
    accept: '.png,image/png',
    outputFormat: 'image/jpeg',
    outputExt: 'jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: 'image-convert-png-to-svg',
    title: 'PNG to SVG',
    emoji: '🔄',
    description: 'Convert PNG to SVG',
    category: 'convert',
    accept: '.png,image/png',
    outputFormat: 'image/svg+xml',
    outputExt: 'svg',
    mimeType: 'image/svg+xml',
    isSvg: true,
  },
  {
    id: 'image-convert-png-to-tiff',
    title: 'PNG to TIFF',
    emoji: '🔄',
    description: 'Convert PNG to TIFF',
    category: 'convert',
    accept: '.png,image/png',
    outputFormat: 'image/tiff',
    outputExt: 'tiff',
    mimeType: 'image/tiff',
  },
  {
    id: 'image-convert-png-to-webp',
    title: 'PNG to WebP',
    emoji: '🔄',
    description: 'Convert PNG to WebP',
    category: 'convert',
    accept: '.png,image/png',
    outputFormat: 'image/webp',
    outputExt: 'webp',
    mimeType: 'image/webp',
  },
  {
    id: 'image-convert-psd-to-jpg',
    title: 'PSD to JPG',
    emoji: '🔄',
    description: 'Convert PSD to JPG',
    category: 'convert',
    accept: '.psd',
    outputFormat: 'image/jpeg',
    outputExt: 'jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: 'image-convert-psd-to-png',
    title: 'PSD to PNG',
    emoji: '🔄',
    description: 'Convert PSD to PNG',
    category: 'convert',
    accept: '.psd',
    outputFormat: 'image/png',
    outputExt: 'png',
    mimeType: 'image/png',
  },
  {
    id: 'image-convert-svg-to-png',
    title: 'SVG to PNG',
    emoji: '🔄',
    description: 'Convert SVG to PNG',
    category: 'convert',
    accept: '.svg,image/svg+xml',
    outputFormat: 'image/png',
    outputExt: 'png',
    mimeType: 'image/png',
  },
  {
    id: 'image-convert-tiff-to-jpg',
    title: 'TIFF to JPG',
    emoji: '🔄',
    description: 'Convert TIFF to JPG',
    category: 'convert',
    accept: '.tiff,.tif,image/tiff',
    outputFormat: 'image/jpeg',
    outputExt: 'jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: 'image-convert-tiff-to-png',
    title: 'TIFF to PNG',
    emoji: '🔄',
    description: 'Convert TIFF to PNG',
    category: 'convert',
    accept: '.tiff,.tif,image/tiff',
    outputFormat: 'image/png',
    outputExt: 'png',
    mimeType: 'image/png',
  },
  {
    id: 'image-convert-webp-to-avif',
    title: 'WebP to AVIF',
    emoji: '🔄',
    description: 'Convert WebP to AVIF',
    category: 'convert',
    accept: '.webp,image/webp',
    outputFormat: 'image/avif',
    outputExt: 'avif',
    mimeType: 'image/avif',
  },
  {
    id: 'image-convert-webp-to-gif',
    title: 'WebP to GIF',
    emoji: '🔄',
    description: 'Convert WebP to GIF',
    category: 'convert',
    accept: '.webp,image/webp',
    outputFormat: 'image/gif',
    outputExt: 'gif',
    mimeType: 'image/gif',
  },
  {
    id: 'image-convert-webp-to-jpg',
    title: 'WebP to JPG',
    emoji: '🔄',
    description: 'Convert WebP to JPG',
    category: 'convert',
    accept: '.webp,image/webp',
    outputFormat: 'image/jpeg',
    outputExt: 'jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: 'image-convert-webp-to-png',
    title: 'WebP to PNG',
    emoji: '🔄',
    description: 'Convert WebP to PNG',
    category: 'convert',
    accept: '.webp,image/webp',
    outputFormat: 'image/png',
    outputExt: 'png',
    mimeType: 'image/png',
  },

  // ── Create ───────────────────────────────────────────
  {
    id: 'base64',
    title: 'Base64',
    emoji: '🔤',
    description: 'Encode/decode Base64',
    category: 'create',
  },
  {
    id: 'breaking-bad',
    title: 'Breaking Bad',
    emoji: '🧪',
    description: 'Breaking Bad text styler',
    category: 'create',
  },
  {
    id: 'camera',
    title: 'Camera',
    emoji: '📸',
    description: 'Take photos with your camera',
    category: 'create',
  },
  {
    id: 'chart-maker',
    title: 'Chart Maker',
    emoji: '📊',
    description: 'Create custom charts and graphs',
    category: 'create',
  },
  {
    id: 'collage-maker',
    title: 'Collage Maker',
    emoji: '🖼️',
    description: 'Create photo collages',
    category: 'create',
    accept: 'image/*',
  },
  {
    id: 'github-social-preview',
    title: 'GitHub Preview',
    emoji: '🐙',
    description: 'Generate GitHub social preview images',
    category: 'create',
  },
  {
    id: 'house',
    title: 'House',
    emoji: '🏠',
    description: 'Design a simple house',
    category: 'create',
  },
  {
    id: 'image-profile',
    title: 'Profile Pic',
    emoji: '👤',
    description: 'Resize images for social media profiles',
    category: 'create',
    accept: 'image/*',
  },
  {
    id: 'instasize',
    title: 'InstaSize',
    emoji: '📱',
    description: 'Resize images for Instagram',
    category: 'create',
    accept: 'image/*',
  },
  {
    id: 'meme-maker',
    title: 'Meme Maker',
    emoji: '😂',
    description: 'Create custom memes',
    category: 'create',
    accept: 'image/*',
  },
  {
    id: 'pixel',
    title: 'Pixel Art',
    emoji: '🎮',
    description: 'Convert images to pixel art',
    category: 'create',
    accept: 'image/*',
  },
  {
    id: 'youtube-thumbnails',
    title: 'YouTube Thumbnails',
    emoji: '▶️',
    description: 'Download YouTube video thumbnails',
    category: 'create',
  },

  // ── Edit ─────────────────────────────────────────────
  {
    id: 'image-border',
    title: 'Border',
    emoji: '🖼️',
    description: 'Add border to images',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-bw',
    title: 'Black & White',
    emoji: '⚫',
    description: 'Convert images to grayscale',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-compress',
    title: 'Compress',
    emoji: '📦',
    description: 'Reduce image file size',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-crop',
    title: 'Crop',
    emoji: '✂️',
    description: 'Crop images to custom dimensions',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-flip',
    title: 'Flip',
    emoji: '🔄',
    description: 'Flip images horizontally or vertically',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-pixelate',
    title: 'Pixelate',
    emoji: '🔲',
    description: 'Pixelate images',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-resize',
    title: 'Resize',
    emoji: '📐',
    description: 'Resize image dimensions',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-rotate',
    title: 'Rotate',
    emoji: '🔄',
    description: 'Rotate images by angle',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-round',
    title: 'Round',
    emoji: '⭕',
    description: 'Round image corners',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-sharpen',
    title: 'Sharpen',
    emoji: '🔪',
    description: 'Sharpen blurry images',
    category: 'edit',
    accept: 'image/*',
  },
  {
    id: 'image-split',
    title: 'Split',
    emoji: '✂️',
    description: 'Split images into tiles',
    category: 'edit',
    accept: 'image/*',
  },

  // ── Effect ───────────────────────────────────────────
  {
    id: 'image-adjust',
    title: 'Adjust',
    emoji: '🎛️',
    description: 'Adjust brightness, contrast, saturation',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-blur-background',
    title: 'Blur BG',
    emoji: '🌫️',
    description: 'Blur image background',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-combiner-side-by-side',
    title: 'Side by Side',
    emoji: '↔️',
    description: 'Combine images side by side',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-combiner-stacked',
    title: 'Stacked',
    emoji: '⬆️',
    description: 'Stack images vertically',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-morphing',
    title: 'Morphing',
    emoji: '🌀',
    description: 'Morph between two images',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-photo-filters',
    title: 'Photo Filters',
    emoji: '🎞️',
    description: 'Apply vintage and artistic filters',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-pixelate-face',
    title: 'Pixelate Face',
    emoji: '😶',
    description: 'Pixelate faces in images',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-shadow',
    title: 'Shadow',
    emoji: '👤',
    description: 'Add drop shadow to images',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-text',
    title: 'Text Overlay',
    emoji: '🔤',
    description: 'Add text overlay to images',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-transparent-bg',
    title: 'Transparent BG',
    emoji: '🪟',
    description: 'Make image background transparent',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-vignette',
    title: 'Vignette',
    emoji: '🌑',
    description: 'Add vignette effect to images',
    category: 'effect',
    accept: 'image/*',
  },
  {
    id: 'image-watermark',
    title: 'Watermark',
    emoji: '💧',
    description: 'Add watermark to images',
    category: 'effect',
    accept: 'image/*',
  },

  // ── Scan ─────────────────────────────────────────────
  {
    id: 'barcode',
    title: 'Barcode',
    emoji: '📊',
    description: 'Generate barcodes',
    category: 'scan',
  },
  {
    id: 'barcode-read',
    title: 'Read Barcode',
    emoji: '📖',
    description: 'Read barcodes from images',
    category: 'scan',
    accept: 'image/*',
  },
  {
    id: 'image-ocr',
    title: 'OCR',
    emoji: '🔍',
    description: 'Extract text from images',
    category: 'scan',
    accept: 'image/*',
  },
  {
    id: 'image-translate',
    title: 'Translate',
    emoji: '🌍',
    description: 'Translate text from images',
    category: 'scan',
    accept: 'image/*',
  },
  {
    id: 'invoice-parser',
    title: 'Invoice Parser',
    emoji: '🧾',
    description: 'Extract data from invoice images',
    category: 'scan',
    accept: 'image/*',
  },
  {
    id: 'qr',
    title: 'QR Code',
    emoji: '📱',
    description: 'Generate QR codes',
    category: 'scan',
  },
  {
    id: 'qr-read',
    title: 'Read QR',
    emoji: '📖',
    description: 'Read QR codes from images',
    category: 'scan',
    accept: 'image/*',
  },
];

export const CATEGORY_TOOLS: Record<string, string[]> = {};
for (const t of TOOLS) {
  (CATEGORY_TOOLS[t.category] ??= []).push(t.id);
}

let preselectedToolId: string | null = null;

export const preselectImageTool = (id: string | null) => {
  preselectedToolId = id;
};

export const popPreselectedImageTool = (): string | null => {
  const id = preselectedToolId;
  preselectedToolId = null;
  return id;
};
