import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Generate',
    description: 'AI Image Gen',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'generation',
      'create',
      'ai-art',
      'text-to-image',
      'stable-diffusion',
      'dalle',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
    ],
    emoji: '✨',
    color: '#3b82f6',
    onClick: open('ai-generate'),
  },
  {
    label: 'Remove BG',
    description: 'AI Background',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'delete',
      'erase',
      'clear',
      'removal',
      'backdrop',
      'background-removal',
    ],
    emoji: '🖼️',
    color: '#3b82f6',
    onClick: open('ai-remove-bg'),
  },
  {
    label: 'Remove Object',
    description: 'AI Cleanup',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'delete',
      'erase',
      'clear',
      'removal',
    ],
    emoji: '🎯',
    color: '#3b82f6',
    onClick: open('ai-remove-object'),
  },
  {
    label: 'Remove Person',
    description: 'AI Object Removal',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'delete',
      'erase',
      'clear',
    ],
    emoji: '🚶',
    color: '#3b82f6',
    onClick: open('ai-remove-person'),
  },
  {
    label: 'Remove Watermark',
    description: 'AI Clean',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'delete',
      'erase',
      'clear',
      'removal',
      'watermark-removal',
      'logo',
    ],
    emoji: '💧',
    color: '#3b82f6',
    onClick: open('ai-remove-watermark'),
  },
  {
    label: 'Restore',
    description: 'AI Photo Restore',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'restoration',
      'recover',
      'repair',
      'fix',
      'old-photo',
    ],
    emoji: '🔄',
    color: '#3b82f6',
    onClick: open('ai-restore'),
  },
  {
    label: 'Unblur',
    description: 'AI Deblur',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'sharpen',
      'focus',
      'blurry',
    ],
    emoji: '👁️',
    color: '#3b82f6',
    onClick: open('ai-unblur'),
  },
  {
    label: 'Upscale',
    description: 'AI Enlarge',
    tags: [
      'artificial-intelligence',
      'machine-learning',
      'blow-up',
      'super-resolution',
      'hd',
      '4k',
    ],
    emoji: '🔍',
    color: '#3b82f6',
    onClick: open('ai-upscale'),
  },
];
