import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Calculator',
    description: 'Math',
    tags: ['converter', 'unit-converter', 'arithmetic'],
    emoji: '➗',
    color: '#8b5cf6',
    onClick: open('calculator'),
  },
  {
    label: 'Angle',
    description: 'Converter',
    tags: ['unit-converter', 'transform', 'change'],
    emoji: '📐',
    color: '#8b5cf6',
    onClick: open('angle'),
  },
  {
    label: 'Base',
    description: 'Converter',
    tags: ['unit-converter', 'transform', 'change'],
    emoji: '💻',
    color: '#8b5cf6',
    onClick: open('base'),
  },
  {
    label: 'Data',
    description: 'Converter',
    tags: ['unit-converter', 'transform', 'change'],
    emoji: '💾',
    color: '#8b5cf6',
    onClick: open('data'),
  },
  {
    label: 'Roman',
    description: 'Converter',
    tags: ['unit-converter', 'transform', 'change'],
    emoji: '🏛️',
    color: '#8b5cf6',
    onClick: open('roman'),
  },
  {
    label: 'Length',
    description: 'Converter',
    tags: ['unit-converter', 'transform', 'change'],
    emoji: '📏',
    color: '#8b5cf6',
    onClick: open('length'),
  },
  {
    label: 'Weight',
    description: 'Converter',
    tags: ['unit-converter', 'transform', 'change'],
    emoji: '⚖️',
    color: '#8b5cf6',
    onClick: open('weight'),
  },
  {
    label: 'Temperature',
    description: 'Converter',
    tags: ['unit-converter', 'transform', 'change'],
    emoji: '🌡️',
    color: '#8b5cf6',
    onClick: open('temperature'),
  },
  {
    label: 'Time',
    description: 'Converter',
    tags: [
      'unit-converter',
      'timezone',
      'world-clock',
      'time-converter',
      'clock',
      'transform',
      'change',
    ],
    emoji: '⏰',
    color: '#8b5cf6',
    onClick: open('time'),
  },
];
