import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Figlet',
    description: 'Text art',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    emoji: '📝',
    color: '#8b5cf6',
    onClick: open('figlet'),
  },
  {
    label: 'IP',
    description: 'Inspector',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    emoji: '🌐',
    color: '#f59e0b',
    onClick: open('ip'),
  },
  {
    label: 'Proxy',
    description: 'CORS Proxy',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    emoji: '🔗',
    color: '#3b82f6',
    onClick: open('proxy'),
  },
  {
    label: 'Shopify Detect',
    description: 'Detect Shopify',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    emoji: '🔍',
    color: '#06b6d4',
    onClick: open('shopify-detect'),
  },
  {
    label: 'SVG',
    description: 'Editor',
    tags: ['developer', 'programming', 'code', 'dev-tools', 'modify', 'change'],
    emoji: '🎨',
    color: '#8b5cf6',
    onClick: open('svg'),
  },
  {
    label: 'UUID',
    description: 'Generator',
    tags: [
      'developer',
      'programming',
      'code',
      'dev-tools',
      'guid',
      'unique-id',
      'identifier',
      'create',
      'maker',
      'builder',
    ],
    emoji: '🔑',
    color: '#a855f7',
    onClick: open('uuid'),
  },
  {
    label: 'Diff',
    description: 'Text Comparison',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    emoji: '📝',
    color: '#3b82f6',
    onClick: open('text-diff'),
  },
  {
    label: 'Case',
    description: 'Converter',
    tags: [
      'developer',
      'programming',
      'code',
      'dev-tools',
      'transform',
      'change',
    ],
    emoji: '🔤',
    color: '#3b82f6',
    onClick: open('text-case'),
  },
  {
    label: 'URL Tracer',
    description: 'Redirect Tracker',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    emoji: '🔗',
    color: '#3b82f6',
    onClick: open('text-url-tracer'),
  },
  {
    label: 'Sheets',
    description: 'SQLite Browser',
    tags: [
      'developer',
      'programming',
      'code',
      'dev-tools',
      'spreadsheet',
      'excel',
      'google-sheets',
    ],
    emoji: '🗄️',
    color: '#3b82f6',
    onClick: open('sheets'),
  },
];
