import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: '2048',
    description: 'Merge tiles',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '🔢',
    color: '#f59e0b',
    onClick: open('game2048'),
  },
  {
    label: 'Palindrome',
    description: 'Palindrome',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '🔁',
    color: '#f59e0b',
    onClick: open('palindrome'),
  },
  {
    label: 'PD',
    description: "Prisoner's Dilemma",
    tags: ['game', 'fun', 'entertainment'],
    emoji: '⚖️',
    color: '#f59e0b',
    onClick: open('pd'),
  },
  {
    label: 'Sudoku',
    description: '4×4 & 9×9',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '🧩',
    color: '#f59e0b',
    onClick: open('sudoku'),
  },
  {
    label: 'Snake',
    description: '12×12 grid',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '🐍',
    color: '#f59e0b',
    onClick: open('snake'),
  },
  {
    label: 'Pokedex',
    description: 'Pokemon',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '📕',
    color: '#f59e0b',
    onClick: open('pokedex'),
  },
  {
    label: 'RPS',
    description: 'Rock Paper Scissors',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '✂️',
    color: '#f59e0b',
    onClick: open('rps'),
  },
  {
    label: 'T3',
    description: 'Tic-Tac-Toe',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '❌',
    color: '#f59e0b',
    onClick: open('t3'),
  },
  {
    label: 'Towers',
    description: 'Towers of Hanoi',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '🗼',
    color: '#f59e0b',
    onClick: open('towers'),
  },
  {
    label: 'Typoglycemia',
    description: 'Scrambled text',
    tags: ['game', 'fun', 'entertainment'],
    emoji: '🔀',
    color: '#f59e0b',
    onClick: open('typoglycemia'),
  },
  {
    label: 'Wordle',
    description: 'Guess the word',
    tags: ['game', 'fun', 'entertainment', 'docx', 'doc', 'microsoft-word'],
    emoji: '🟩',
    color: '#f59e0b',
    onClick: open('wordle'),
  },
];
