import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Barcode',
    description: 'Generator',
    tags: [
      'image',
      'scan',
      'ocr',
      'photo',
      'code128',
      'ean',
      'upc',
      'create',
      'maker',
      'builder',
    ],
    emoji: '▌',
    color: '#22d3ee',
    onClick: open('barcode'),
  },
  {
    label: 'QR Code',
    description: 'Generator',
    tags: [
      'image',
      'scan',
      'ocr',
      'photo',
      'qrcode',
      'barcode',
      'create',
      'maker',
      'builder',
    ],
    emoji: '▦',
    color: '#22d3ee',
    onClick: open('qr'),
  },
  {
    label: 'QR Read',
    description: 'QR Scanner',
    tags: ['image', 'ocr', 'photo', 'qrcode', 'barcode', 'code'],
    emoji: '📱',
    color: '#3b82f6',
    onClick: open('qr-read'),
  },
  {
    label: 'Barcode Read',
    description: 'Barcode Scanner',
    tags: ['image', 'ocr', 'photo', 'code128', 'ean', 'upc'],
    emoji: '📋',
    color: '#3b82f6',
    onClick: open('barcode-read'),
  },
  {
    label: 'OCR',
    description: 'Text Extraction',
    tags: ['image', 'scan', 'photo'],
    emoji: '🔍',
    color: '#3b82f6',
    onClick: open('image-ocr'),
  },
  {
    label: 'Dominant Color',
    description: 'Extract Color',
    tags: [
      'image',
      'scan',
      'ocr',
      'photo',
      'colour',
      'hex',
      'rgb',
      'hsl',
      'picker',
    ],
    emoji: '🎯',
    color: '#3b82f6',
    onClick: open('image-dominant-color'),
  },
  {
    label: 'Invoice Parser',
    description: 'OCR',
    tags: ['image', 'scan', 'photo'],
    emoji: '📄',
    color: '#ef4444',
    onClick: open('invoice-parser'),
  },
  {
    label: 'Image Translate',
    description: 'OCR + Translate',
    tags: [
      'scan',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
      'translation',
      'language',
      'i18n',
    ],
    emoji: '🌐',
    color: '#10b981',
    onClick: open('image-translate'),
  },
];
