import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Chart Maker',
    description: 'Create Chart',
    tags: ['image', 'photo', 'generator'],
    emoji: '📊',
    color: '#3b82f6',
    onClick: open('chart-maker'),
  },
  {
    label: 'Meme Maker',
    description: 'Create Meme',
    tags: ['image', 'photo', 'generator', 'funny'],
    emoji: '🎭',
    color: '#3b82f6',
    onClick: open('meme-maker'),
  },
  {
    label: 'Collage',
    description: 'Photo Collage',
    tags: ['image', 'create', 'generator'],
    emoji: '🖼️',
    color: '#3b82f6',
    onClick: open('collage-maker'),
  },
  {
    label: 'Profile',
    description: 'Photo Maker',
    tags: ['image', 'create', 'generator'],
    emoji: '👤',
    color: '#3b82f6',
    onClick: open('image-profile'),
  },
  {
    label: 'Pixel',
    description: 'Art Grid',
    tags: ['image', 'create', 'photo', 'generator'],
    emoji: '▪️',
    color: '#8b5cf6',
    onClick: open('pixel'),
  },
  {
    label: 'InstaSize',
    description: 'Square Fit',
    tags: ['image', 'create', 'photo', 'generator'],
    emoji: '📸',
    color: '#3b82f6',
    onClick: open('instasize'),
  },
  {
    label: 'Social Preview',
    description: 'GitHub',
    tags: ['image', 'create', 'photo', 'generator'],
    emoji: '📸',
    color: '#10b981',
    onClick: open('github-social-preview'),
  },
  {
    label: 'Thumbnails',
    description: 'YouTube',
    tags: ['image', 'create', 'photo', 'generator', 'yt', 'video', 'download'],
    emoji: '📸',
    color: '#22d3ee',
    onClick: open('youtube-thumbnails'),
  },
  {
    label: 'House',
    description: 'M.D.',
    tags: ['image', 'create', 'photo', 'generator'],
    emoji: '🏥',
    color: '#ef4444',
    onClick: open('house'),
  },
  {
    label: 'Camera',
    description: 'Composition',
    tags: ['image', 'create', 'photo', 'generator'],
    emoji: '📸',
    color: '#ef4444',
    onClick: open('camera'),
  },
  {
    label: 'Breaking Bad',
    description: 'Element',
    tags: ['image', 'create', 'photo', 'generator'],
    emoji: '🧪',
    color: '#eab308',
    onClick: open('breaking-bad'),
  },
  {
    label: 'Base64',
    description: 'Decode/Encode',
    tags: ['image', 'create', 'photo', 'generator', 'base-64'],
    emoji: '🔐',
    color: '#3b82f6',
    onClick: open('base64'),
  },
];
