import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'GIF to JPG',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-gif-to-jpg'),
  },
  {
    label: 'GIF to PNG',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-gif-to-png'),
  },
  {
    label: 'HEIC to AVIF',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-heic-to-avif'),
  },
  {
    label: 'PSD to JPG',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-psd-to-jpg'),
  },
  {
    label: 'PSD to PNG',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-psd-to-png'),
  },
  {
    label: 'SVG to PNG',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-svg-to-png'),
  },
  {
    label: 'TIFF to JPG',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-tiff-to-jpg'),
  },
  {
    label: 'TIFF to PNG',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-tiff-to-png'),
  },
  {
    label: 'WebP to AVIF',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-webp-to-avif'),
  },
  {
    label: 'WebP to GIF',
    description: 'Convert',
    tags: ['image', 'pro', 'photo'],
    emoji: '🔄',
    color: '#06b6d4',
    onClick: open('image-convert-webp-to-gif'),
  },
];
