import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Annotate',
    description: 'PDF',
    tags: ['edit', 'document', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-annotate'),
  },
  {
    label: 'Compress',
    description: 'PDF',
    tags: [
      'edit',
      'document',
      'zip',
      'archive',
      'minify',
      'reduce-size',
      'adobe',
      'acrobat',
    ],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-compress'),
  },
  {
    label: 'Crop Pages',
    description: 'PDF',
    tags: ['edit', 'document', 'trim', 'cut', 'clip-image', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-crop'),
  },
  {
    label: 'Delete Pages',
    description: 'PDF',
    tags: ['edit', 'document', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-delete-pages'),
  },
  {
    label: 'Merge',
    description: 'PDF',
    tags: ['edit', 'document', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-merge'),
  },
  {
    label: 'Page Numbers',
    description: 'PDF',
    tags: ['edit', 'document', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-page-numbers'),
  },
  {
    label: 'Rearrange',
    description: 'PDF',
    tags: ['edit', 'document', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-rearrange'),
  },
  {
    label: 'Redact',
    description: 'PDF',
    tags: ['edit', 'document', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-redact'),
  },
  {
    label: 'Rotate',
    description: 'PDF',
    tags: ['edit', 'document', 'flip', 'orientation', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-rotate'),
  },
  {
    label: 'Split',
    description: 'PDF',
    tags: ['edit', 'document', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-split'),
  },
  {
    label: 'Watermark',
    description: 'PDF',
    tags: ['edit', 'document', 'watermark-removal', 'logo', 'adobe', 'acrobat'],
    emoji: '📄',
    color: '#3b82f6',
    onClick: open('pdf-watermark'),
  },
];
