import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Chat',
    description: 'AI Assistant',
    tags: ['utility', 'tool', 'productivity'],
    emoji: '💬',
    color: '#3b82f6',
    onClick: open('chat'),
  },
  {
    label: 'Clipboard',
    description: 'Clipboard',
    tags: [
      'utility',
      'tool',
      'productivity',
      'copy',
      'paste',
      'clipboard-manager',
    ],
    emoji: '📋',
    color: '#3b82f6',
    onClick: open('clipboard'),
  },
  {
    label: 'Create ZIP',
    description: 'Data',
    tags: ['utility', 'tool'],
    emoji: '🗜️',
    color: '#10b981',
    onClick: open('create-zip'),
  },
  {
    label: 'Emojis',
    description: 'Explorer',
    tags: ['utility', 'tool', 'productivity'],
    emoji: '😀',
    color: '#f59e0b',
    onClick: open('emojis'),
  },
  {
    label: 'Kaprekar',
    description: 'Routine',
    tags: ['utility', 'tool', 'productivity'],
    emoji: '🔢',
    color: '#f59e0b',
    onClick: open('kaprekar'),
  },
  {
    label: 'No Sleep',
    description: 'Timer',
    tags: [
      'utility',
      'tool',
      'productivity',
      'countdown',
      'stopwatch',
      'alarm',
    ],
    emoji: '😴',
    color: '#3b82f6',
    onClick: open('no-sleep'),
  },
  {
    label: 'Password',
    description: 'Generator',
    tags: [
      'utility',
      'tool',
      'productivity',
      'secret',
      'strong',
      'create',
      'maker',
      'builder',
    ],
    emoji: '🔐',
    color: '#3b82f6',
    onClick: open('text-password'),
  },
  {
    label: 'Screen Recorder',
    description: 'Record & Download',
    tags: ['utility', 'tool', 'productivity'],
    emoji: '🎥',
    color: '#3b82f6',
    onClick: open('screen-recorder'),
  },
  {
    label: 'Word Count',
    description: 'Counter',
    tags: [
      'utility',
      'tool',
      'productivity',
      'docx',
      'doc',
      'microsoft-word',
      'tally',
    ],
    emoji: '📊',
    color: '#3b82f6',
    onClick: open('text-word-count'),
  },
];
