import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'AVI to GIF',
    description: 'Video',
    tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-avi-to-gif'),
  },
  {
    label: 'AVI to MP3',
    description: 'Video',
    tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-avi-to-mp3'),
  },
  {
    label: 'AVI to MP4',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-avi-to-mp4'),
  },
  {
    label: 'FLV to MP4',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-flv-to-mp4'),
  },
  {
    label: 'GIF to MOV',
    description: 'Video',
    tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-gif-to-mov'),
  },
  {
    label: 'GIF to MP4',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-gif-to-mp4'),
  },
  {
    label: 'GIF to WebM',
    description: 'Video',
    tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-gif-to-webm'),
  },
  {
    label: 'MKV to MP4',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mkv-to-mp4'),
  },
  {
    label: 'MOV to MP4',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mov-to-mp4'),
  },
  {
    label: 'MP4 to AVI',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mp4-to-avi'),
  },
  {
    label: 'MP4 to MOV',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mp4-to-mov'),
  },
  {
    label: 'WMV to MP4',
    description: 'Video',
    tags: ['convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-wmv-to-mp4'),
  },
];
