import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'AAC to MP3',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-aac-to-mp3'),
  },
  {
    label: 'AAC to MP4',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-aac-to-mp4'),
  },
  {
    label: 'AAC to WAV',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-aac-to-wav'),
  },
  {
    label: 'M4A to MP3',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-m4a-to-mp3'),
  },
  {
    label: 'M4A to MP4',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-m4a-to-mp4'),
  },
  {
    label: 'M4A to WAV',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-m4a-to-wav'),
  },
  {
    label: 'MOV to MP3',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mov-to-mp3'),
  },
  {
    label: 'MOV to WAV',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mov-to-wav'),
  },
  {
    label: 'MP4 to MP3',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mp4-to-mp3'),
  },
  {
    label: 'MP4 to WAV',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-mp4-to-wav'),
  },
  {
    label: 'OGG to MP3',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-ogg-to-mp3'),
  },
  {
    label: 'OGG to WAV',
    description: 'Video',
    tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
    emoji: '🎬',
    color: '#ef4444',
    onClick: open('video-ogg-to-wav'),
  },
];
