services:
  nothing-openapi-to-postmanv2:
    container_name: nothing-openapi-to-postmanv2
    build: .
    ports:
      - '10000:10000'
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 512M
