package lodash

/**
 * Assigns own enumerable string keyed properties of source objects to the destination object.
 * Source objects are applied from left to right. Subsequent sources overwrite property assignments of previous sources.
 */
fun assign(obj: MutableMap<String, Any?>, vararg sources: Map<String, Any?>): MutableMap<String, Any?> {
    sources.forEach { obj.putAll(it) }
    return obj
}

/**
 * Creates an object composed of the picked object properties.
 */
fun pick(obj: Map<String, Any?>, paths: Iterable<String>): Map<String, Any?> {
    return obj.filterKeys { it in paths }
}

/**
 * The opposite of _.pick; this method creates an object composed of the own and inherited enumerable property paths of object that are not omitted.
 */
fun omit(obj: Map<String, Any?>, paths: Iterable<String>): Map<String, Any?> {
    return obj.filterKeys { it !in paths }
}

/**
 * Gets the value at path of object. If the resolved value is undefined, the defaultValue is returned in its place.
 */
fun get(obj: Map<String, Any?>?, path: String, defaultValue: Any? = null): Any? {
    if (obj == null) return defaultValue
    val parts = path.split(".")
    var current: Any? = obj
    for (part in parts) {
        if (current is Map<*, *>) {
            current = (current as Map<String, Any?>)[part]
        } else {
            return defaultValue
        }
    }
    return current ?: defaultValue
}

/**
 * Checks if path is a direct property of object.
 */
fun has(obj: Map<String, Any?>?, path: String): Boolean {
    if (obj == null) return false
    val parts = path.split(".")
    var current: Any? = obj
    for (part in parts) {
        if (current is Map<*, *>) {
            val map = current as Map<String, Any?>
            if (!map.containsKey(part)) return false
            current = map[part]
        } else {
            return false
        }
    }
    return true
}

/**
 * Creates an array of the own enumerable property names of object.
 */
fun keys(obj: Map<String, Any?>): List<String> = obj.keys.toList()

/**
 * Creates an array of the own enumerable string keyed property values of object.
 */
fun values(obj: Map<String, Any?>): List<Any?> = obj.values.toList()

/**
 * Creates an object with the same values as object and keys generated by running each own enumerable string keyed property of object thru iteratee.
 */
fun mapKeys(obj: Map<String, Any?>, iteratee: (Any?, String) -> String): Map<String, Any?> {
    return obj.mapKeys { (key, value) -> iteratee(value, key) }
}

/**
 * Creates an object with the same keys as object and values generated by running each own enumerable string keyed property of object thru iteratee.
 */
fun mapValues(obj: Map<String, Any?>, iteratee: (Any?) -> Any?): Map<String, Any?> {
    return obj.mapValues { (_, value) -> iteratee(value) }
}

/**
 * Assigns own and inherited enumerable string keyed properties of source objects to the destination object for all destination properties that resolve to undefined.
 * Source objects are applied from left to right. Once a property is set, additional values of the same property are ignored.
 */
fun defaults(obj: MutableMap<String, Any?>, vararg sources: Map<String, Any?>): MutableMap<String, Any?> {
    sources.forEach { source ->
        source.forEach { (key, value) ->
            if (!obj.containsKey(key)) {
                obj[key] = value
            }
        }
    }
    return obj
}

/**
 * This method is like _.find except that it returns the key of the first element predicate returns truthy for instead of the element itself.
 */
fun findKey(obj: Map<String, Any?>, predicate: (Any?) -> Boolean): String? {
    return obj.entries.find { predicate(it.value) }?.key
}

/**
 * Iterates over own and inherited enumerable string keyed properties of an object and invokes iteratee for each property.
 */
fun forIn(obj: Map<String, Any?>, iteratee: (Any?, String) -> Unit) {
    obj.forEach { (key, value) -> iteratee(value, key) }
}

/**
 * Iterates over own enumerable string keyed properties of an object and invokes iteratee for each property.
 */
fun forOwn(obj: Map<String, Any?>, iteratee: (Any?, String) -> Unit) {
    forIn(obj, iteratee)
}

/**
 * Creates an object composed of the inverted keys and values of object.
 * If object contains duplicate values, subsequent values overwrite property assignments of previous values.
 */
fun invert(obj: Map<String, Any?>): Map<String, String> {
    return obj.entries.associate { it.value.toString() to it.key }
}

/**
 * This method is like _.invert except that the inverted object is generated from the results of running each element of object thru iteratee.
 */
fun invertBy(obj: Map<String, Any?>, iteratee: (Any?) -> String): Map<String, String> {
    return obj.entries.associate { iteratee(it.value) to it.key }
}

/**
 * Sets the value at path of object. If a portion of path doesn't exist, it's created.
 */
fun set(obj: MutableMap<String, Any?>, path: String, value: Any?): MutableMap<String, Any?> {
    val parts = path.split(".")
    var current = obj
    for (i in 0 until parts.size - 1) {
        val part = parts[i]
        if (!current.containsKey(part) || current[part] !is MutableMap<*, *>) {
            current[part] = mutableMapOf<String, Any?>()
        }
        current = current[part] as MutableMap<String, Any?>
    }
    current[parts.last()] = value
    return obj
}

/**
 * Removes the property at path of object.
 */
fun unset(obj: MutableMap<String, Any?>, path: String): Boolean {
    val parts = path.split(".")
    var current = obj
    for (i in 0 until parts.size - 1) {
        val part = parts[i]
        if (current[part] is MutableMap<*, *>) {
            current = current[part] as MutableMap<String, Any?>
        } else {
            return false
        }
    }
    return current.remove(parts.last()) != null
}
