import type { MenuItem, MenuState, Order, Restaurant } from '@/types/menu';

const SEED_DATE = '2025-01-01T09:00:00.000Z';

const restaurants: Restaurant[] = [
  {
    id: 'seed-rest-trattoria',
    name: 'Trattoria Lumière',
    description: 'Wood-fired Italian classics in the heart of town.',
    accent: 'primary',
    tableCount: 12,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-rest-umami',
    name: 'Umami Ramen Bar',
    description: 'Slow-simmered broths and hand-pulled noodles.',
    accent: 'warning',
    tableCount: 8,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-rest-mornings',
    name: "Mornings Café",
    description: 'All-day breakfast and specialty coffee.',
    accent: 'success',
    tableCount: 6,
    createdAt: SEED_DATE,
  },
];

const items: MenuItem[] = [
  {
    id: 'seed-item-margherita',
    restaurantId: 'seed-rest-trattoria',
    name: 'Margherita',
    description: 'San Marzano tomato, fior di latte, fresh basil.',
    price: 1450,
    category: 'food',
    emoji: '🍕',
    available: true,
    sortOrder: 1,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-carbonara',
    restaurantId: 'seed-rest-trattoria',
    name: 'Carbonara',
    description: 'Guanciale, pecorino, egg yolk, black pepper.',
    price: 1690,
    category: 'food',
    emoji: '🍝',
    available: true,
    sortOrder: 2,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-caprese',
    restaurantId: 'seed-rest-trattoria',
    name: 'Caprese',
    description: 'Heirloom tomato, buffalo mozzarella, basil oil.',
    price: 1190,
    category: 'food',
    emoji: '🥗',
    available: true,
    sortOrder: 3,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-tiramisu',
    restaurantId: 'seed-rest-trattoria',
    name: 'Tiramisu',
    description: 'Espresso-soaked savoiardi, mascarpone cream.',
    price: 890,
    category: 'food',
    emoji: '🍰',
    available: true,
    sortOrder: 4,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-limonata',
    restaurantId: 'seed-rest-trattoria',
    name: 'Limonata',
    description: 'House lemonade with sparkling water.',
    price: 450,
    category: 'drink',
    emoji: '🍋',
    available: true,
    sortOrder: 5,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-espresso',
    restaurantId: 'seed-rest-trattoria',
    name: 'Espresso',
    description: 'Double shot of our house blend.',
    price: 350,
    category: 'drink',
    emoji: '☕',
    available: true,
    sortOrder: 6,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-ramen',
    restaurantId: 'seed-rest-umami',
    name: 'Tonkotsu Ramen',
    description: 'Pork broth, chashu, soft egg, scallions.',
    price: 1590,
    category: 'food',
    emoji: '🍜',
    available: true,
    sortOrder: 1,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-gyoza',
    restaurantId: 'seed-rest-umami',
    name: 'Gyoza',
    description: 'Pan-fried pork dumplings, ponzu dipping sauce.',
    price: 790,
    category: 'food',
    emoji: '🥟',
    available: true,
    sortOrder: 2,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-karaage',
    restaurantId: 'seed-rest-umami',
    name: 'Karaage',
    description: 'Crispy fried chicken, yuzu kosho mayo.',
    price: 890,
    category: 'food',
    emoji: '🍗',
    available: true,
    sortOrder: 3,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-miso',
    restaurantId: 'seed-rest-umami',
    name: 'Spicy Miso',
    description: 'Miso broth, ground pork, bean sprouts, chili oil.',
    price: 1490,
    category: 'food',
    emoji: '🌶️',
    available: true,
    sortOrder: 4,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-matcha',
    restaurantId: 'seed-rest-umami',
    name: 'Matcha Latte',
    description: 'Ceremonial matcha, oat milk, honey.',
    price: 550,
    category: 'drink',
    emoji: '🍵',
    available: true,
    sortOrder: 5,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-yuzu',
    restaurantId: 'seed-rest-umami',
    name: 'Yuzu Soda',
    description: 'House yuzu soda with a bright citrus finish.',
    price: 490,
    category: 'drink',
    emoji: '🥤',
    available: true,
    sortOrder: 6,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-avocado',
    restaurantId: 'seed-rest-mornings',
    name: 'Avocado Toast',
    description: 'Sourdough, smashed avocado, chili flakes, poached egg.',
    price: 1090,
    category: 'food',
    emoji: '🥑',
    available: true,
    sortOrder: 1,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-pancakes',
    restaurantId: 'seed-rest-mornings',
    name: 'Fluffy Pancakes',
    description: 'Maple syrup, whipped butter, fresh berries.',
    price: 990,
    category: 'food',
    emoji: '🥞',
    available: true,
    sortOrder: 2,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-burrito',
    restaurantId: 'seed-rest-mornings',
    name: 'Breakfast Burrito',
    description: 'Scrambled eggs, cheddar, salsa, crispy potato.',
    price: 1190,
    category: 'food',
    emoji: '🌯',
    available: true,
    sortOrder: 3,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-flatwhite',
    restaurantId: 'seed-rest-mornings',
    name: 'Flat White',
    description: 'Double ristretto, velvety steamed milk.',
    price: 490,
    category: 'drink',
    emoji: '☕',
    available: true,
    sortOrder: 4,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-coldbrew',
    restaurantId: 'seed-rest-mornings',
    name: 'Cold Brew',
    description: '18-hour steep, smooth and low-acid.',
    price: 520,
    category: 'drink',
    emoji: '🧊',
    available: true,
    sortOrder: 5,
    createdAt: SEED_DATE,
  },
  {
    id: 'seed-item-oj',
    restaurantId: 'seed-rest-mornings',
    name: 'Fresh OJ',
    description: 'Squeezed-to-order Valencia oranges.',
    price: 590,
    category: 'drink',
    emoji: '🍊',
    available: true,
    sortOrder: 6,
    createdAt: SEED_DATE,
  },
];

const orders: Order[] = [
  {
    id: 'seed-order-1',
    restaurantId: 'seed-rest-trattoria',
    tableNumber: '4',
    note: 'No chili flakes on the carbonara, please.',
    lines: [
      { itemId: 'seed-item-margherita', name: 'Margherita', emoji: '🍕', price: 1450, quantity: 2 },
      { itemId: 'seed-item-limonata', name: 'Limonata', emoji: '🍋', price: 450, quantity: 2 },
    ],
    subtotal: 3800,
    createdAt: '2025-01-01T12:30:00.000Z',
    status: 'served',
  },
  {
    id: 'seed-order-2',
    restaurantId: 'seed-rest-umami',
    tableNumber: '2',
    customerName: 'Alex',
    lines: [
      { itemId: 'seed-item-ramen', name: 'Tonkotsu Ramen', emoji: '🍜', price: 1590, quantity: 1 },
      { itemId: 'seed-item-gyoza', name: 'Gyoza', emoji: '🥟', price: 790, quantity: 2 },
      { itemId: 'seed-item-yuzu', name: 'Yuzu Soda', emoji: '🥤', price: 490, quantity: 1 },
    ],
    subtotal: 3660,
    createdAt: '2025-01-01T13:00:00.000Z',
    status: 'placed',
  },
];

export const seedMenuData = (): MenuState => ({
  restaurants,
  items,
  orders,
});
