import { ComponentType } from 'react';

const ALL_IMAGE_IDS = [
  'image',
  'ai-colorize',
  'ai-generate',
  'ai-remove-bg',
  'ai-remove-object',
  'ai-remove-person',
  'ai-remove-watermark',
  'ai-restore',
  'ai-unblur',
  'ai-upscale',
  'barcode',
  'barcode-read',
  'base64',
  'breaking-bad',
  'camera',
  'chart-maker',
  'collage-maker',
  'colors',
  'contrast-checker',
  'github-social-preview',
  'gradient-generator',
  'house',
  'image-adjust',
  'image-ai',
  'image-blur-background',
  'image-border',
  'image-bw',
  'image-colorize',
  'image-combiner-side-by-side',
  'image-combiner-stacked',
  'image-compress',
  'image-convert-gif-to-jpg',
  'image-convert-gif-to-png',
  'image-convert-heic-to-avif',
  'image-convert-heic-to-jpg',
  'image-convert-heic-to-png',
  'image-convert-jpg-to-avif',
  'image-convert-jpg-to-gif',
  'image-convert-jpg-to-png',
  'image-convert-jpg-to-svg',
  'image-convert-jpg-to-tiff',
  'image-convert-jpg-to-webp',
  'image-convert-png-to-avif',
  'image-convert-png-to-eps',
  'image-convert-png-to-gif',
  'image-convert-png-to-jpg',
  'image-convert-png-to-svg',
  'image-convert-png-to-tiff',
  'image-convert-png-to-webp',
  'image-convert-psd-to-jpg',
  'image-convert-psd-to-png',
  'image-convert-svg-to-png',
  'image-convert-tiff-to-jpg',
  'image-convert-tiff-to-png',
  'image-convert-webp-to-avif',
  'image-convert-webp-to-gif',
  'image-convert-webp-to-jpg',
  'image-convert-webp-to-png',
  'image-create',
  'image-crop',
  'image-dominant-color',
  'image-edit',
  'image-effect',
  'image-filter',
  'image-flip',
  'image-morphing',
  'image-ocr',
  'image-photo-filters',
  'image-pixelate',
  'image-pixelate-face',
  'image-profile',
  'image-resize',
  'image-rotate',
  'image-round',
  'image-shadow',
  'image-sharpen',
  'image-split',
  'image-text',
  'image-translate',
  'image-transparent-bg',
  'image-vignette',
  'image-watermark',
  'instasize',
  'invoice-parser',
  'meme-maker',
  'pixel',
  'qr',
  'qr-read',
  'youtube-thumbnails',
];

const loadImage = () =>
  import('@hieudoanm.github.io/components/pages/start/apps/image').then(
    (m) => ({ default: m.ImageModal })
  );

export const loaders: Record<
  string,
  () => Promise<{ default: ComponentType<{ onClose: () => void }> }>
> = Object.fromEntries(ALL_IMAGE_IDS.map((id) => [id, loadImage]));
