import { Tool } from '@hieudoanm.github.io/components/pages/start/components/cards/ToolCard';

export const TOOL_SECTION_LABELS: Record<string, string> = {
  'calculator-convert': 'Calculator - Convert',
  'calculator-finance': 'Calculator - Finance',
  clocks: 'Clocks',
  'data-csv': 'Data - CSV',
  'data-excel': 'Data - Excel',
  'data-json': 'Data - JSON',
  'data-xml': 'Data - XML',
  developer: 'Developer',
  editors: 'Editors',
  education: 'Education',
  'games-arcade': 'Game - Arcade',
  'games-casino': 'Game - Casino',
  'games-chess': 'Game - Chess',
  'games-memory': 'Game - Memory',
  'games-puzzle': 'Game - Puzzle',
  'games-trivia': 'Game - Trivia',
  'games-word': 'Game - Word',
  'health-vision': 'Health - Vision',
  'image-ai': 'Image - AI',
  'image-color': 'Image - Color',
  'image-convert-gif': 'Image - GIF Convert',
  'image-convert-heic': 'Image - HEIC Convert',
  'image-convert-jpg': 'Image - JPG Convert',
  'image-convert-png': 'Image - PNG Convert',
  'image-convert-psd': 'Image - PSD Convert',
  'image-convert-svg': 'Image - SVG Convert',
  'image-convert-tiff': 'Image - TIFF Convert',
  'image-convert-webp': 'Image - WebP Convert',
  'image-create': 'Image - Create',
  'image-edit': 'Image - Edit',
  'image-effect': 'Image - Effect',
  'image-scan': 'Image - Scan',
  markdown: 'Markdown',
  'pdf-convert': 'PDF - Convert',
  'pdf-create': 'PDF - Create',
  'pdf-ebook': 'PDF - Ebook',
  'pdf-edit': 'PDF - Edit',
  'pdf-extract': 'PDF - Extract',
  'pdf-misc': 'PDF - Misc',
  'text-convert': 'Text - Convert',
  utilities: 'Utilities',
  'video-audio': 'Video - Audio',
  'video-convert-aac': 'Video - AAC Convert',
  'video-convert-avi': 'Video - AVI Convert',
  'video-convert-flv': 'Video - FLV Convert',
  'video-convert-gif': 'Video - GIF Convert',
  'video-convert-m4a': 'Video - M4A Convert',
  'video-convert-mkv': 'Video - MKV Convert',
  'video-convert-mov': 'Video - MOV Convert',
  'video-convert-mp4': 'Video - MP4 Convert',
  'video-convert-ogg': 'Video - OGG Convert',
  'video-convert-webm': 'Video - WebM Convert',
  'video-convert-wmv': 'Video - WMV Convert',
  'video-download': 'Video - Download',
  'video-edit': 'Video - Edit',
  visualization: 'Visualization',
  'write-article': 'Write - Article',
  'write-business': 'Write - Business',
  'write-content': 'Write - Content',
  'write-edit': 'Write - Edit',
  'write-misc': 'Write - Misc',
  'write-real-estate': 'Write - Real Estate',
  'write-social': 'Write - Social',
};

export const getToolSectionDefs = (
  toolSections: Record<string, Tool[]>
): { label: string; items: Tool[] }[] =>
  Object.entries(TOOL_SECTION_LABELS).map(([key, label]) => ({
    label,
    items: toolSections[key] ?? [],
  }));
