import {
  PiArrowsClockwise,
  PiDatabase,
  PiGlobe,
  PiKey,
  PiLink,
  PiMagnifyingGlass,
  PiNotePencil,
  PiPaintBrush,
} from 'react-icons/pi';
import { Tool } from '@hieudoanm.github.io/components/pages/start/components/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Diff',
    description: 'Text Comparison',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    icon: PiNotePencil,
    onClick: open('text-diff'),
  },
  {
    label: 'Figlet',
    description: 'Text art',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    icon: PiNotePencil,
    onClick: open('figlet'),
  },
  {
    label: 'IP',
    description: 'Inspector',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    icon: PiGlobe,
    onClick: open('ip'),
  },
  {
    label: 'OpenAPI',
    description: 'to Postman',
    tags: [
      'developer',
      'programming',
      'code',
      'dev-tools',
      'rest',
      'swagger',
      'specification',
    ],
    icon: PiArrowsClockwise,
    onClick: open('openapi'),
  },
  {
    label: 'Proxy',
    description: 'CORS Proxy',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    icon: PiLink,
    onClick: open('proxy'),
  },
  {
    label: 'Sheets',
    description: 'SQLite Browser',
    tags: [
      'developer',
      'programming',
      'code',
      'dev-tools',
      'spreadsheet',
      'excel',
      'google-sheets',
    ],
    icon: PiDatabase,
    onClick: open('sheets'),
  },
  {
    label: 'Shopify Detect',
    description: 'Detect Shopify',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    icon: PiMagnifyingGlass,
    onClick: open('shopify-detect'),
  },
  {
    label: 'SVG',
    description: 'Editor',
    tags: ['developer', 'programming', 'code', 'dev-tools', 'modify', 'change'],
    icon: PiPaintBrush,
    onClick: open('svg'),
  },
  {
    label: 'URL Tracer',
    description: 'Redirect Tracker',
    tags: ['developer', 'programming', 'code', 'dev-tools'],
    icon: PiLink,
    onClick: open('text-url-tracer'),
  },
  {
    label: 'UUID',
    description: 'Generator',
    tags: [
      'developer',
      'programming',
      'code',
      'dev-tools',
      'guid',
      'unique-id',
      'identifier',
      'create',
      'maker',
      'builder',
    ],
    icon: PiKey,
    onClick: open('uuid'),
  },
];
