import {
  PiClipboard,
  PiDeviceMobile,
  PiFileText,
  PiGlobe,
  PiGridFour,
  PiMagnifyingGlass,
  PiSidebar,
} from 'react-icons/pi';
import { Tool } from '@hieudoanm.github.io/components/pages/start/components/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Barcode',
    description: 'Generator',
    tags: [
      'image',
      'scan',
      'ocr',
      'photo',
      'code128',
      'ean',
      'upc',
      'create',
      'maker',
      'builder',
    ],
    icon: PiSidebar,
    onClick: open('barcode'),
  },
  {
    label: 'Barcode Read',
    description: 'Barcode Scanner',
    tags: ['image', 'ocr', 'photo', 'code128', 'ean', 'upc'],
    icon: PiClipboard,
    onClick: open('barcode-read'),
  },
  {
    label: 'Image Translate',
    description: 'OCR + Translate',
    tags: [
      'scan',
      'photo',
      'picture',
      'img',
      'png',
      'jpg',
      'jpeg',
      'gif',
      'translation',
      'language',
      'i18n',
    ],
    icon: PiGlobe,
    onClick: open('image-translate'),
  },
  {
    label: 'Invoice Parser',
    description: 'OCR',
    tags: ['image', 'scan', 'photo'],
    icon: PiFileText,
    onClick: open('invoice-parser'),
  },
  {
    label: 'OCR',
    description: 'Text Extraction',
    tags: ['image', 'scan', 'photo'],
    icon: PiMagnifyingGlass,
    onClick: open('image-ocr'),
  },
  {
    label: 'QR Code',
    description: 'Generator',
    tags: [
      'image',
      'scan',
      'ocr',
      'photo',
      'qrcode',
      'barcode',
      'create',
      'maker',
      'builder',
    ],
    icon: PiGridFour,
    onClick: open('qr'),
  },
  {
    label: 'QR Read',
    description: 'QR Scanner',
    tags: ['image', 'ocr', 'photo', 'qrcode', 'barcode', 'code'],
    icon: PiDeviceMobile,
    onClick: open('qr-read'),
  },
];
