import {
  PiChartBar,
  PiChatCircle,
  PiClipboard,
  PiFilmStrip,
  PiLock,
  PiMoon,
  PiNotePencil,
  PiNumberSquareOne,
  PiPackage,
  PiSmiley,
} from 'react-icons/pi';
import { Tool } from '@hieudoanm.github.io/components/pages/start/components/cards/ToolCard';
import { ModalId } from '../types';

export const make = (open: (id: ModalId) => () => void): Tool[] => [
  {
    label: 'Chat',
    description: 'AI Assistant',
    tags: ['utility', 'tool', 'productivity'],
    icon: PiChatCircle,
    onClick: open('chat'),
  },
  {
    label: 'Clipboard',
    description: 'Clipboard',
    tags: [
      'utility',
      'tool',
      'productivity',
      'copy',
      'paste',
      'clipboard-manager',
    ],
    icon: PiClipboard,
    onClick: open('clipboard'),
  },
  {
    label: 'Create ZIP',
    description: 'Data',
    tags: ['utility', 'tool'],
    icon: PiPackage,
    onClick: open('create-zip'),
  },
  {
    label: 'Emojis',
    description: 'Explorer',
    tags: ['utility', 'tool', 'productivity'],
    icon: PiSmiley,
    onClick: open('emojis'),
  },
  {
    label: 'Kaprekar',
    description: 'Routine',
    tags: ['utility', 'tool', 'productivity'],
    icon: PiNumberSquareOne,
    onClick: open('kaprekar'),
  },
  {
    label: 'Lorem Ipsum',
    description: 'Dummy text',
    tags: [
      'utility',
      'converter',
      'data',
      'placeholder',
      'dummy-text',
      'filler',
    ],
    icon: PiNotePencil,
    onClick: open('lorem-ipsum'),
  },
  {
    label: 'No Sleep',
    description: 'Timer',
    tags: [
      'utility',
      'tool',
      'productivity',
      'countdown',
      'stopwatch',
      'alarm',
    ],
    icon: PiMoon,
    onClick: open('no-sleep'),
  },
  {
    label: 'Password',
    description: 'Generator',
    tags: [
      'utility',
      'tool',
      'productivity',
      'secret',
      'strong',
      'create',
      'maker',
      'builder',
    ],
    icon: PiLock,
    onClick: open('text-password'),
  },
  {
    label: 'Screen Recorder',
    description: 'Record & Download',
    tags: ['utility', 'tool', 'productivity'],
    icon: PiFilmStrip,
    onClick: open('screen-recorder'),
  },
  {
    label: 'Word Count',
    description: 'Counter',
    tags: [
      'utility',
      'tool',
      'productivity',
      'docx',
      'doc',
      'microsoft-word',
      'tally',
    ],
    icon: PiChartBar,
    onClick: open('text-word-count'),
  },
];
