import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Proxy | Next.js',
  description: 'Generated by Hono',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
