version: '3'

services:
  stockfish:
    build: .
    container_name: 'stockfish'
    ports:
      - '8000:8000'
    environment:
      DEVELOPMENT: false
      LOG_LEVEL: 'info'
      DOCKER: true
      PORT: '8000'
