#[path = "airvisual.com/airvisual.rs"]
pub mod airvisual;
#[path = "chess.com/chess.rs"]
pub mod chess;
#[path = "coinranking.com/coinranking.rs"]
pub mod coinranking;
#[path = "crossref.org/crossref.rs"]
pub mod crossref;
#[path = "deepseek.com/deepseek.rs"]
pub mod deepseek;
#[path = "fixer.io/fixer.rs"]
pub mod fixer;
#[path = "football-data.org/football-data.rs"]
pub mod football_data;
#[path = "frankfurter.app/frankfurter.rs"]
pub mod frankfurter;
#[path = "lichess.org/lichess.rs"]
pub mod lichess;
#[path = "newsapi.org/newsapi.rs"]
pub mod newsapi;
#[path = "openai.com/openai.rs"]
pub mod openai;
#[path = "openweathermap.org/openweathermap.rs"]
pub mod openweathermap;
#[path = "telegram.org/telegram.rs"]
pub mod telegram;
