[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.2.0", features = [] }

[dependencies]
glib = { version = "=0.20.9" }
serde_json = { version = "=1.0.140" }
serde = { version = "=1.0.219", features = ["derive"] }
log = { version = "=0.4.27" }
tauri = { version = "=2.5.1", features = [] }
tauri-plugin-log = { version = "=2.4.0" }
