services:
  nothing-deepseek:
    container_name: nothing-deepseek
    build: .
    ports:
      - '10000:10000'
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 512M
