import { Tool } from '@hieudoanm.github.io/components/atoms';
import {
  PiAirplane,
  PiAlien,
  PiBriefcase,
  PiCalendar,
  PiCamera,
  PiChartBar,
  PiChatCircle,
  PiCheckCircle,
  PiCodeSimple,
  PiDatabase,
  PiDrop,
  PiEnvelope,
  PiFacebookLogo,
  PiFolder,
  PiGameController,
  PiGithubLogo,
  PiGlobe,
  PiHeart,
  PiInfinity,
  PiLightning,
  PiMagnifyingGlass,
  PiMapPin,
  PiMoon,
  PiMusicNote,
  PiNewspaper,
  PiNotePencil,
  PiPackage,
  PiPlay,
  PiRobot,
  PiSmiley,
  PiSparkle,
  PiStarFour,
  PiThreadsLogo,
  PiTwitterLogo,
  PiWaveform,
  PiWind,
  PiWindowsLogo,
} from 'react-icons/pi';

export interface BookmarkSection {
  label: string;
  items: Tool[];
}

export const BOOKMARK_SECTIONS: BookmarkSection[] = [
  {
    label: 'Agents',
    items: [
      {
        label: 'Claude',
        href: 'https://claude.ai/',
        description: 'Anthropic',
        icon: PiStarFour,
        //color: '#d97757',
        badge: 'Chat',
      },
      {
        label: 'ChatGPT',
        href: 'https://chatgpt.com',
        description: 'OpenAI',
        icon: PiStarFour,
        //color: '#10a37f',
        badge: 'Chat',
      },
      {
        label: 'Qwen',
        href: 'https://qwen.ai',
        description: 'Alibaba Cloud',
        icon: PiStarFour,
        //color: '#615ced',
        badge: 'Chat',
      },
      {
        label: 'Kimi',
        href: 'https://kimi.moonshot.cn',
        description: 'Moonshot AI',
        icon: PiMoon,
        //color: '#39d353',
        badge: 'Chat',
      },
      {
        label: 'Perplexity',
        href: 'https://www.perplexity.ai',
        description: 'AI Search',
        icon: PiMagnifyingGlass,
        //color: '#20b2aa',
        badge: 'Research',
      },
      {
        label: 'Gemini',
        href: 'https://gemini.google.com/app',
        description: 'Google',
        icon: PiSparkle,
        //color: '#4285f4',
      },
      {
        label: 'Grok',
        href: 'https://grok.com',
        description: 'xAI',
        icon: PiLightning,
        //color: '#1d9bf0',
      },
      {
        label: 'Copilot',
        href: 'https://copilot.microsoft.com',
        description: 'Microsoft',
        icon: PiWindowsLogo,
        //color: '#0078d4',
      },
      {
        label: 'DeepSeek',
        href: 'https://chat.deepseek.com',
        description: 'DeepSeek',
        icon: PiDrop,
        //color: '#4d6bfe',
      },
      {
        label: 'Mistral',
        href: 'https://chat.mistral.ai',
        description: 'Mistral AI',
        icon: PiWind,
        //color: '#ff7000',
      },
      {
        label: 'Meta AI',
        href: 'https://www.meta.ai',
        description: 'Meta',
        icon: PiInfinity,
        //color: '#0082fb',
      },
      {
        label: 'HuggingChat',
        href: 'https://huggingface.co/chat',
        description: 'HuggingFace',
        icon: PiSmiley,
        //color: '#ff9d00',
      },
      {
        label: 'Poe',
        href: 'https://poe.com',
        description: 'Quora',
        icon: PiChatCircle,
        //color: '#8b5cf6',
      },
      {
        label: 'Cohere',
        href: 'https://coral.cohere.com',
        description: 'Cohere',
        icon: PiWaveform,
        //color: '#39d353',
      },
    ],
  },
  {
    label: 'Code',
    items: [
      {
        label: 'GitHub',
        href: 'https://github.com',
        description: 'Git',
        icon: PiGithubLogo,
        //color: '#6e40c9',
      },
      {
        label: 'Renovate',
        href: 'https://developer.mend.io',
        description: 'Code',
        icon: PiRobot,
        //color: '#9b59b6',
      },
      {
        label: 'Vercel',
        href: 'https://vercel.com',
        description: 'Deployment',
        icon: PiGlobe,
        //color: '#000000',
      },
      {
        label: 'Supabase',
        href: 'https://supabase.com',
        description: 'Database',
        icon: PiDatabase,
        //color: '#3ECF8E',
      },
    ],
  },
  {
    label: 'Google Workspace',
    items: [
      {
        label: 'Calendar',
        href: 'https://calendar.google.com',
        description: 'Calendar',
        icon: PiCalendar,
        //color: '#4285f4',
      },
      {
        label: 'Docs',
        href: 'https://docs.google.com',
        description: 'Word',
        icon: PiNotePencil,
        //color: '#4285f4',
      },
      {
        label: 'Drive',
        href: 'https://drive.google.com',
        description: 'OneDrive',
        icon: PiFolder,
        //color: '#4285f4',
      },
      {
        label: 'Gmail',
        href: 'https://gmail.com',
        description: 'Email',
        icon: PiEnvelope,
        //color: '#d93025',
      },
      {
        label: 'Maps',
        href: 'https://maps.google.com',
        description: 'Maps',
        icon: PiMapPin,
        //color: '#4285f4',
      },
      {
        label: 'Sheets',
        href: 'https://sheets.google.com',
        description: 'Excel',
        icon: PiChartBar,
        //color: '#0a6847',
      },
      {
        label: 'Slides',
        href: 'https://slides.google.com',
        description: 'PowerPoint',
        icon: PiPlay,
        //color: '#c23728',
      },
      {
        label: 'Tasks',
        href: 'https://tasks.google.com',
        description: 'ToDo',
        icon: PiCheckCircle,
        //color: '#4285f4',
      },
    ],
  },
  {
    label: 'Messaging',
    items: [
      {
        label: 'Discord',
        href: 'https://discord.com',
        description: 'Messaging',
        icon: PiGameController,
        //color: '#5865f2',
      },
      {
        label: 'Messenger',
        href: 'https://www.messenger.com',
        description: 'Messaging',
        icon: PiHeart,
        //color: '#1877F2',
      },
      {
        label: 'Slack',
        href: 'https://slack.com',
        description: 'Messaging',
        icon: PiCodeSimple,
        //color: '#4a154b',
      },
      {
        label: 'Telegram',
        href: 'https://web.telegram.org/',
        description: 'Messaging',
        icon: PiAirplane,
        //color: '#0088cc',
      },
    ],
  },
  {
    label: 'Music',
    items: [
      {
        label: 'Spotify',
        href: 'https://open.spotify.com',
        description: 'Music',
        icon: PiMusicNote,
        //color: '#1DB954',
      },
      {
        label: 'YouTube',
        href: 'https://youtube.com',
        description: 'Videos',
        icon: PiPlay,
        //color: '#ff0000',
      },
    ],
  },
  {
    label: 'Social',
    items: [
      {
        label: 'Facebook',
        href: 'https://facebook.com',
        description: 'Social network',
        icon: PiFacebookLogo,
        //color: '#4267B2',
      },
      {
        label: 'Instagram',
        href: 'https://instagram.com',
        description: 'Photos',
        icon: PiCamera,
        //color: '#e1306c',
      },
      {
        label: 'Reddit',
        href: 'https://reddit.com',
        description: 'Social network',
        icon: PiAlien,
        //color: '#ff4500',
      },
      {
        label: 'Threads',
        href: 'https://threads.net',
        description: 'Social network',
        icon: PiThreadsLogo,
        //color: '#000000',
      },
      {
        label: 'Tiktok',
        href: 'https://www.tiktok.com',
        description: 'Social network',
        icon: PiMusicNote,
        //color: '#000000',
      },
      {
        label: 'X',
        href: 'https://x.com',
        description: 'Social network',
        icon: PiTwitterLogo,
        //color: '#0088cc',
      },
    ],
  },
  {
    label: 'Work',
    items: [
      {
        label: 'LinkedIn',
        href: 'https://linkedin.com',
        description: 'Social network',
        icon: PiBriefcase,
        //color: '#0077b5',
      },
      {
        label: 'Hacker News',
        href: 'https://news.ycombinator.com',
        description: 'News',
        icon: PiNewspaper,
        //color: '#ff6600',
      },
      {
        label: 'Indie Hackers',
        href: 'https://www.indiehackers.com',
        description: 'News',
        icon: PiCodeSimple,
        //color: '#ffa200',
      },
      {
        label: 'Product Hunt',
        href: 'https://www.producthunt.com',
        description: 'News',
        icon: PiPackage,
        //color: '#ffa200',
      },
    ],
  },
];
