'use client';

import Link from 'next/link';
import type { FC, ReactNode } from 'react';
import { useState } from 'react';
import {
  FiActivity,
  FiAlertCircle,
  FiAlertOctagon,
  FiAlertTriangle,
  FiArchive,
  FiBarChart2,
  FiBell,
  FiBook,
  FiBookOpen,
  FiBriefcase,
  FiCalendar,
  FiCheckCircle,
  FiCheckSquare,
  FiChevronDown,
  FiChevronsRight,
  FiChevronsUp,
  FiColumns,
  FiCreditCard,
  FiClock,
  FiClock as FiClock2,
  FiDollarSign,
  FiDroplet,
  FiEdit2,
  FiEdit3,
  FiFileText,
  FiFolder,
  FiGift,
  FiGrid,
  FiHeart,
  FiHelpCircle,
  FiInbox,
  FiInfo,
  FiKey,
  FiLayers,
  FiLink,
  FiLoader,
  FiLock,
  FiLogIn,
  FiMail,
  FiMap,
  FiMapPin,
  FiMessageSquare,
  FiMonitor,
  FiRefreshCw,
  FiSearch,
  FiSend,
  FiSettings,
  FiShield,
  FiShieldOff,
  FiShoppingBag,
  FiShoppingCart,
  FiShuffle,
  FiSmartphone,
  FiStar,
  FiTable,
  FiTag,
  FiTarget,
  FiTerminal,
  FiTrash2,
  FiTruck,
  FiTrendingUp,
  FiUpload,
  FiUser,
  FiUserPlus,
  FiUsers,
  FiZap,
} from 'react-icons/fi';

interface PageEntry {
  label: string;
  href: string;
  template: string;
  icon: ReactNode;
  description?: string;
}

const GROUPS: { title: string; pages: PageEntry[] }[] = [
  {
    title: 'Main',
    pages: [
      {
        label: 'Dashboard',
        href: '/app/dashboard',
        template: 'app/DashboardTemplate',
        icon: <FiGrid />,
        description: 'Overview dashboard',
      },
      {
        label: 'Profile',
        href: '/social/profile',
        template: 'social/ProfileTemplate',
        icon: <FiUser />,
        description: 'User profile',
      },
      {
        label: 'Settings',
        href: '/landing/settings',
        template: 'landing/SettingsTemplate',
        icon: <FiSettings />,
        description: 'App settings & theme picker',
      },
      {
        label: 'Version',
        href: '/landing/version',
        template: 'landing/VersionTemplate',
        icon: <FiClock />,
        description: 'Build version info',
      },
      {
        label: 'Chat',
        href: '/app/chat',
        template: 'app/ChatTemplate',
        icon: <FiBookOpen />,
        description: 'Chat conversations',
      },
      {
        label: 'Onboarding',
        href: '/mail/onboarding',
        template: 'mail/OnboardingTemplate',
        icon: <FiUser />,
        description: 'Multi-step onboarding flow',
      },
      {
        label: 'Search',
        href: '/support/search',
        template: 'support/SearchTemplate',
        icon: <FiSearch />,
        description: 'Search page',
      },
    ],
  },
  {
    title: 'App Workspace',
    pages: [
      {
        label: 'Analytics',
        href: '/app/analytics',
        template: 'app/AnalyticsTemplate',
        icon: <FiTrendingUp />,
        description: 'Usage metrics dashboard',
      },
      {
        label: 'Calendar',
        href: '/app/calendar',
        template: 'app/CalendarTemplate',
        icon: <FiCalendar />,
        description: 'Monthly events calendar',
      },
      {
        label: 'Kanban',
        href: '/app/kanban',
        template: 'app/KanbanTemplate',
        icon: <FiColumns />,
        description: 'Drag-style task board',
      },
      {
        label: 'Inbox',
        href: '/app/inbox',
        template: 'app/InboxTemplate',
        icon: <FiInbox />,
        description: 'Email inbox',
      },
      {
        label: 'Tasks',
        href: '/app/tasks',
        template: 'app/TasksTemplate',
        icon: <FiCheckSquare />,
        description: 'Todo list with filters',
      },
      {
        label: 'Notes',
        href: '/landing/notes',
        template: 'landing/NotesTemplate',
        icon: <FiEdit3 />,
        description: 'Inline editable notes',
      },
      {
        label: 'Files',
        href: '/app/files',
        template: 'app/FilesTemplate',
        icon: <FiFolder />,
        description: 'File browser',
      },
      {
        label: 'Help Center',
        href: '/app/help',
        template: 'app/HelpCenterTemplate',
        icon: <FiHelpCircle />,
        description: 'Searchable FAQ categories',
      },
      {
        label: 'Members',
        href: '/app/members',
        template: 'app/MembersTemplate',
        icon: <FiUsers />,
        description: 'Team member roles',
      },
      {
        label: 'Notifications',
        href: '/app/notifications',
        template: 'app/NotificationsTemplate',
        icon: <FiBell />,
        description: 'Notification feed',
      },
      {
        label: 'Billing',
        href: '/finance/billing',
        template: 'finance/BillingTemplate',
        icon: <FiDollarSign />,
        description: 'Plan & usage summary',
      },
      {
        label: 'Integrations',
        href: '/app/integrations',
        template: 'app/IntegrationsTemplate',
        icon: <FiLink />,
        description: 'Connected services',
      },
      {
        label: 'Activity Log',
        href: '/app/activity',
        template: 'app/ActivityLogTemplate',
        icon: <FiActivity />,
        description: 'Recent user activity',
      },
      {
        label: 'Expenses',
        href: '/finance/expenses',
        template: 'finance/ExpensesTemplate',
        icon: <FiDollarSign />,
        description: 'Expense tracker',
      },
      {
        label: 'Timesheets',
        href: '/mail/timesheets',
        template: 'mail/TimesheetsTemplate',
        icon: <FiClock />,
        description: 'Weekly timesheet entries',
      },
      {
        label: 'Goals',
        href: '/app/goals',
        template: 'app/GoalsTemplate',
        icon: <FiTarget />,
        description: 'Objective & progress tracking',
      },
      {
        label: 'Roadmap',
        href: '/landing/roadmap',
        template: 'landing/RoadmapTemplate',
        icon: <FiMap />,
        description: 'Product roadmap timeline',
      },
      {
        label: 'Sprints',
        href: '/landing/sprints',
        template: 'landing/SprintsTemplate',
        icon: <FiZap />,
        description: 'Sprint board & velocity',
      },
      {
        label: 'Reports',
        href: '/social/reports',
        template: 'social/ReportsTemplate',
        icon: <FiFileText />,
        description: 'Generated report cards',
      },
      {
        label: 'Contacts',
        href: '/app/contacts',
        template: 'app/ContactsTemplate',
        icon: <FiUsers />,
        description: 'Contact list & search',
      },
      {
        label: 'Whiteboard',
        href: '/landing/whiteboard',
        template: 'landing/WhiteboardTemplate',
        icon: <FiEdit3 />,
        description: 'Collaborative whiteboard',
      },
      {
        label: 'Meetings',
        href: '/app/meetings',
        template: 'app/MeetingsTemplate',
        icon: <FiCalendar />,
        description: 'Scheduled meetings',
      },
      {
        label: 'Shortcuts',
        href: '/landing/shortcuts',
        template: 'landing/ShortcutsTemplate',
        icon: <FiTerminal />,
        description: 'Keyboard shortcuts',
      },
      {
        label: 'Import',
        href: '/mail/import',
        template: 'mail/ImportTemplate',
        icon: <FiUpload />,
        description: 'Data import flow',
      },
      {
        label: 'Webhooks',
        href: '/developer/webhooks',
        template: 'developer/WebhooksTemplate',
        icon: <FiLink />,
        description: 'Webhook endpoints',
      },
      {
        label: 'Permissions',
        href: '/auth/permissions',
        template: 'auth/PermissionsTemplate',
        icon: <FiLock />,
        description: 'Role permissions matrix',
      },
    ],
  },
  {
    title: 'Data & UI Showcase',
    pages: [
      {
        label: 'Data Table',
        href: '/hr/data-table',
        template: 'hr/DataTableTemplate',
        icon: <FiTable />,
        description: 'Sortable data grid',
      },
      {
        label: 'Forms',
        href: '/hr/forms',
        template: 'hr/FormsShowcaseTemplate',
        icon: <FiEdit2 />,
        description: 'Form control gallery',
      },
      {
        label: 'Charts',
        href: '/hr/charts',
        template: 'hr/ChartsGalleryTemplate',
        icon: <FiBarChart2 />,
        description: 'Chart gallery',
      },
      {
        label: 'Modals',
        href: '/hr/modals',
        template: 'hr/ModalsTemplate',
        icon: <FiLayers />,
        description: 'Modal & dialog examples',
      },
      {
        label: 'Forbidden',
        href: '/auth/forbidden',
        template: 'auth/ForbiddenTemplate',
        icon: <FiAlertOctagon />,
        description: '403 access denied page',
      },
      {
        label: 'Accordion',
        href: '/hr/accordion',
        template: 'hr/AccordionTemplate',
        icon: <FiChevronDown />,
        description: 'Collapsible accordion',
      },
      {
        label: 'Alerts',
        href: '/hr/alerts',
        template: 'hr/AlertsTemplate',
        icon: <FiAlertCircle />,
        description: 'Alert banner variants',
      },
      {
        label: 'Tabs',
        href: '/hr/tabs',
        template: 'hr/TabsTemplate',
        icon: <FiLayers />,
        description: 'Tab navigation examples',
      },
      {
        label: 'Pagination',
        href: '/support/pagination',
        template: 'support/PaginationTemplate',
        icon: <FiChevronsRight />,
        description: 'Paginated list',
      },
      {
        label: 'Tooltips',
        href: '/support/tooltips',
        template: 'support/TooltipsTemplate',
        icon: <FiMessageSquare />,
        description: 'Tooltip examples',
      },
      {
        label: 'Stepper',
        href: '/support/stepper',
        template: 'support/StepperTemplate',
        icon: <FiChevronsUp />,
        description: 'Multi-step stepper',
      },
      {
        label: 'Upload',
        href: '/support/upload',
        template: 'support/UploadTemplate',
        icon: <FiUpload />,
        description: 'File upload dropzone',
      },
      {
        label: 'Empty States',
        href: '/hr/empty-states',
        template: 'hr/EmptyStatesTemplate',
        icon: <FiInbox />,
        description: 'Empty state placeholders',
      },
    ],
  },
  {
    title: 'Loading',
    pages: [
      {
        label: 'App Loading',
        href: '/support/loading-app',
        template: 'support/LoadingTemplate',
        icon: <FiLoader />,
        description: 'App workspace skeleton',
      },
      {
        label: 'Auth Loading',
        href: '/support/loading-auth',
        template: 'support/LoadingTemplate',
        icon: <FiLoader />,
        description: 'Sign-in skeleton',
      },
      {
        label: 'Blog Loading',
        href: '/support/loading-blog',
        template: 'support/LoadingTemplate',
        icon: <FiLoader />,
        description: 'Article grid skeleton',
      },
      {
        label: 'Store Loading',
        href: '/support/loading-store',
        template: 'support/LoadingTemplate',
        icon: <FiLoader />,
        description: 'Product grid skeleton',
      },
    ],
  },
  {
    title: 'System',
    pages: [
      {
        label: 'Not Found',
        href: '/auth/not-found',
        template: 'auth/ErrorTemplate',
        icon: <FiAlertCircle />,
        description: '404 page',
      },
      {
        label: 'Error',
        href: '/auth/error',
        template: 'auth/ErrorTemplate',
        icon: <FiAlertTriangle />,
        description: '500 error page',
      },
      {
        label: 'Global Error',
        href: '/auth/global-error',
        template: 'auth/GlobalErrorTemplate',
        icon: <FiAlertOctagon />,
        description: 'Root error boundary',
      },
      {
        label: 'Cookie Consent',
        href: '/support/cookie-consent',
        template: 'support/CookieConsentTemplate',
        icon: <FiShield />,
        description: 'Cookie consent banner',
      },
    ],
  },
  {
    title: 'Auth',
    pages: [
      {
        label: 'Sign In',
        href: '/auth/sign-in',
        template: 'auth/SignInTemplate',
        icon: <FiLogIn />,
        description: 'Sign in page',
      },
      {
        label: 'Sign Up',
        href: '/auth/sign-up',
        template: 'auth/SignUpTemplate',
        icon: <FiUserPlus />,
        description: 'Create account',
      },
      {
        label: 'Forgot Password',
        href: '/auth/forgot-password',
        template: 'auth/PasswordResetTemplate',
        icon: <FiKey />,
        description: 'Password reset request',
      },
      {
        label: 'Reset Password',
        href: '/auth/reset-password',
        template: 'auth/PasswordResetTemplate',
        icon: <FiShield />,
        description: 'Set new password',
      },
      {
        label: 'Verify Email',
        href: '/auth/verify-email',
        template: 'auth/VerifyEmailTemplate',
        icon: <FiMail />,
        description: 'Email verification prompt',
      },
      {
        label: 'Two-Factor',
        href: '/auth/two-factor',
        template: 'auth/TwoFactorTemplate',
        icon: <FiSmartphone />,
        description: '2FA code entry',
      },
      {
        label: 'Lock Screen',
        href: '/auth/lock-screen',
        template: 'auth/LockScreenTemplate',
        icon: <FiLock />,
        description: 'Session lock page',
      },
      {
        label: 'Change Password',
        href: '/auth/change-password',
        template: 'auth/ChangePasswordTemplate',
        icon: <FiRefreshCw />,
        description: 'Update password form',
      },
      {
        label: 'Sessions',
        href: '/auth/sessions',
        template: 'auth/SessionsTemplate',
        icon: <FiMonitor />,
        description: 'Active login sessions',
      },
      {
        label: 'Recovery Codes',
        href: '/auth/recovery-codes',
        template: 'auth/RecoveryCodesTemplate',
        icon: <FiShield />,
        description: 'Two-factor recovery codes',
      },
      {
        label: 'Delete Account',
        href: '/auth/delete-account',
        template: 'auth/DeleteAccountTemplate',
        icon: <FiTrash2 />,
        description: 'Account deletion flow',
      },
      {
        label: 'Security',
        href: '/auth/security',
        template: 'auth/SecurityOverviewTemplate',
        icon: <FiLock />,
        description: 'Security overview',
      },
    ],
  },
  {
    title: 'Marketing',
    pages: [
      {
        label: 'Landing',
        href: '/landing/landing',
        template: 'landing/LandingTemplate',
        icon: <FiTerminal />,
        description: 'Marketing landing page',
      },
      {
        label: 'About',
        href: '/support/about',
        template: 'support/AboutTemplate',
        icon: <FiInfo />,
        description: 'App info & tech stack',
      },
      {
        label: 'Terms',
        href: '/landing/terms',
        template: 'landing/LegalTemplate',
        icon: <FiFileText />,
        description: 'Terms of service',
      },
      {
        label: 'Privacy',
        href: '/landing/privacy',
        template: 'landing/LegalTemplate',
        icon: <FiShieldOff />,
        description: 'Privacy policy',
      },
      {
        label: 'Coming Soon',
        href: '/mail/coming-soon',
        template: 'mail/LaunchStatusTemplate',
        icon: <FiClock2 />,
        description: 'Coming soon placeholder',
      },
      {
        label: 'Maintenance',
        href: '/mail/maintenance',
        template: 'mail/LaunchStatusTemplate',
        icon: <FiAlertCircle />,
        description: 'Maintenance mode page',
      },
      {
        label: 'Resume',
        href: '/landing/resume',
        template: 'landing/ResumeTemplate',
        icon: <FiFileText />,
        description: 'Resume template',
      },
      {
        label: 'Pricing',
        href: '/landing/pricing',
        template: 'landing/PricingTemplate',
        icon: <FiCreditCard />,
        description: 'Pricing plans',
      },
      {
        label: 'Contact',
        href: '/landing/contact',
        template: 'landing/ContactTemplate',
        icon: <FiMail />,
        description: 'Contact form',
      },
      {
        label: 'Careers',
        href: '/landing/careers',
        template: 'landing/CareersTemplate',
        icon: <FiBriefcase />,
        description: 'Job listings',
      },
      {
        label: 'Team',
        href: '/landing/team',
        template: 'landing/TeamTemplate',
        icon: <FiUsers />,
        description: 'Team directory',
      },
      {
        label: 'Changelog',
        href: '/landing/changelog',
        template: 'landing/ChangelogTemplate',
        icon: <FiClock />,
        description: 'Release notes',
      },
    ],
  },
  {
    title: 'Store',
    pages: [
      {
        label: 'Store',
        href: '/store',
        template: 'store/StoreFrontTemplate',
        icon: <FiShoppingBag />,
        description: 'Product listing',
      },
      {
        label: 'Product',
        href: '/store/1',
        template: 'store/StoreItemTemplate',
        icon: <FiShoppingBag />,
        description: 'Product detail (dynamic, /store/[id])',
      },
      {
        label: 'Cart',
        href: '/store/cart',
        template: 'store/CartTemplate',
        icon: <FiShoppingCart />,
        description: 'Shopping cart',
      },
      {
        label: 'Checkout',
        href: '/store/checkout',
        template: 'store/CheckoutTemplate',
        icon: <FiCreditCard />,
        description: 'Checkout flow',
      },
      {
        label: 'Order Confirmation',
        href: '/store/order-confirmation',
        template: 'store/OrderConfirmationTemplate',
        icon: <FiCheckCircle />,
        description: 'Order success page',
      },
      {
        label: 'Order History',
        href: '/store/order-history',
        template: 'store/OrderHistoryTemplate',
        icon: <FiArchive />,
        description: 'Past orders',
      },
      {
        label: 'Wishlist',
        href: '/store/wishlist',
        template: 'store/WishlistTemplate',
        icon: <FiHeart />,
        description: 'Saved products',
      },
      {
        label: 'Compare',
        href: '/store/compare',
        template: 'store/CompareTemplate',
        icon: <FiShuffle />,
        description: 'Product comparison',
      },
      {
        label: 'Addresses',
        href: '/store/addresses',
        template: 'store/AddressBookTemplate',
        icon: <FiMapPin />,
        description: 'Saved shipping addresses',
      },
      {
        label: 'Payment Methods',
        href: '/store/payment-methods',
        template: 'store/PaymentMethodsTemplate',
        icon: <FiCreditCard />,
        description: 'Saved payment cards',
      },
      {
        label: 'Order Tracking',
        href: '/store/tracking',
        template: 'store/OrderTrackingTemplate',
        icon: <FiTruck />,
        description: 'Shipment timeline',
      },
      {
        label: 'Deals',
        href: '/store/deals',
        template: 'store/DealsTemplate',
        icon: <FiTag />,
        description: 'Discount deals',
      },
      {
        label: 'Categories',
        href: '/store/categories',
        template: 'store/CategoriesTemplate',
        icon: <FiGrid />,
        description: 'Product categories',
      },
      {
        label: 'Reviews',
        href: '/store/reviews',
        template: 'store/ReviewsTemplate',
        icon: <FiStar />,
        description: 'Customer reviews',
      },
      {
        label: 'Support',
        href: '/store/support',
        template: 'store/SupportTemplate',
        icon: <FiHelpCircle />,
        description: 'Customer support',
      },
      {
        label: 'Gift Cards',
        href: '/store/gift-cards',
        template: 'store/GiftCardsTemplate',
        icon: <FiGift />,
        description: 'Gift card purchase',
      },
    ],
  },
  {
    title: 'Blog',
    pages: [
      {
        label: 'Blog',
        href: '/blog',
        template: 'blog/BlogListTemplate',
        icon: <FiBookOpen />,
        description: 'Blog index with posts',
      },
      {
        label: 'Blog Post',
        href: '/blog/getting-started',
        template: 'blog/BlogItemTemplate',
        icon: <FiBook />,
        description: 'Blog post detail (dynamic, /blog/[slug])',
      },
      {
        label: 'Archive',
        href: '/blog/archive',
        template: 'blog/BlogArchiveTemplate',
        icon: <FiArchive />,
        description: 'Posts by month',
      },
      {
        label: 'Author',
        href: '/blog/author',
        template: 'blog/BlogAuthorTemplate',
        icon: <FiUser />,
        description: 'Author profile & posts',
      },
      {
        label: 'Newsletter',
        href: '/blog/newsletter',
        template: 'blog/BlogNewsletterTemplate',
        icon: <FiSend />,
        description: 'Subscribe form',
      },
      {
        label: 'Categories',
        href: '/blog/categories',
        template: 'blog/BlogCategoriesTemplate',
        icon: <FiFolder />,
        description: 'Blog category explorer',
      },
      {
        label: 'Tags',
        href: '/blog/tags',
        template: 'blog/BlogTagsTemplate',
        icon: <FiTag />,
        description: 'Posts grouped by tag',
      },
      {
        label: 'Search',
        href: '/blog/search',
        template: 'blog/BlogSearchTemplate',
        icon: <FiSearch />,
        description: 'Live post search',
      },
    ],
  },
  {
    title: 'Commerce Admin',
    pages: [
      {
        label: 'Products',
        href: '/crm/products',
        template: 'crm/ProductsTemplate',
        icon: <FiShoppingBag />,
        description: 'Product catalog admin',
      },
      {
        label: 'Orders',
        href: '/crm/orders',
        template: 'crm/OrdersTemplate',
        icon: <FiShoppingCart />,
        description: 'Order management',
      },
      {
        label: 'Customers',
        href: '/crm/customers',
        template: 'crm/CustomersTemplate',
        icon: <FiUsers />,
        description: 'Customer directory',
      },
      {
        label: 'Inventory',
        href: '/crm/inventory',
        template: 'crm/InventoryTemplate',
        icon: <FiArchive />,
        description: 'Stock level management',
      },
      {
        label: 'Coupons',
        href: '/crm/coupons',
        template: 'crm/CouponsTemplate',
        icon: <FiTag />,
        description: 'Discount coupon management',
      },
      {
        label: 'Promotions',
        href: '/crm/promotions',
        template: 'crm/PromotionsTemplate',
        icon: <FiStar />,
        description: 'Promo campaign builder',
      },
      {
        label: 'Refunds',
        href: '/crm/refunds',
        template: 'crm/RefundsTemplate',
        icon: <FiDollarSign />,
        description: 'Refund requests',
      },
      {
        label: 'Shipments',
        href: '/crm/shipments',
        template: 'crm/ShipmentsTemplate',
        icon: <FiTruck />,
        description: 'Shipment logistics',
      },
    ],
  },
  {
    title: 'Finance',
    pages: [
      {
        label: 'Invoices',
        href: '/finance/invoices',
        template: 'finance/InvoicesTemplate',
        icon: <FiFileText />,
        description: 'Client invoice tracking',
      },
      {
        label: 'Budgets',
        href: '/finance/budgets',
        template: 'finance/BudgetsTemplate',
        icon: <FiBarChart2 />,
        description: 'Budget spending tracker',
      },
      {
        label: 'Subscriptions',
        href: '/finance/subscriptions',
        template: 'finance/SubscriptionsTemplate',
        icon: <FiRefreshCw />,
        description: 'Recurring subscription plans',
      },
      {
        label: 'Transactions',
        href: '/finance/transactions',
        template: 'finance/TransactionsTemplate',
        icon: <FiCreditCard />,
        description: 'Account transactions ledger',
      },
      {
        label: 'Taxes',
        href: '/finance/taxes',
        template: 'finance/TaxesTemplate',
        icon: <FiDollarSign />,
        description: 'Sales tax regions',
      },
      {
        label: 'Payroll',
        href: '/finance/payroll',
        template: 'finance/PayrollTemplate',
        icon: <FiBriefcase />,
        description: 'Employee payroll runs',
      },
      {
        label: 'Statements',
        href: '/finance/statements',
        template: 'finance/StatementsTemplate',
        icon: <FiTable />,
        description: 'Monthly account statements',
      },
      {
        label: 'Accounts',
        href: '/finance/accounts',
        template: 'finance/AccountsTemplate',
        icon: <FiShield />,
        description: 'Linked bank accounts',
      },
    ],
  },
  {
    title: 'Developer',
    pages: [
      {
        label: 'API Keys',
        href: '/developer/api-keys',
        template: 'developer/ApiKeysTemplate',
        icon: <FiKey />,
        description: 'Create and manage access keys',
      },
      {
        label: 'Feature Flags',
        href: '/developer/feature-flags',
        template: 'developer/FeatureFlagsTemplate',
        icon: <FiZap />,
        description: 'Toggle features per environment',
      },
      {
        label: 'Environments',
        href: '/developer/environments',
        template: 'developer/EnvironmentsTemplate',
        icon: <FiMonitor />,
        description: 'Monitor deployment environments',
      },
      {
        label: 'Deployments',
        href: '/developer/deployments',
        template: 'developer/DeploymentsTemplate',
        icon: <FiUpload />,
        description: 'Review deployment history',
      },
      {
        label: 'Logs',
        href: '/developer/logs',
        template: 'developer/LogsTemplate',
        icon: <FiFileText />,
        description: 'Inspect application log output',
      },
      {
        label: 'Endpoints',
        href: '/developer/endpoints',
        template: 'developer/EndpointsTemplate',
        icon: <FiLink />,
        description: 'Explore the public API surface',
      },
      {
        label: 'Monitors',
        href: '/developer/monitors',
        template: 'developer/MonitorsTemplate',
        icon: <FiActivity />,
        description: 'Track service availability',
      },
      {
        label: 'Backups',
        href: '/developer/backups',
        template: 'developer/BackupsTemplate',
        icon: <FiArchive />,
        description: 'Manage backup schedules and restores',
      },
    ],
  },
  {
    title: 'Social & Media',
    pages: [
      {
        label: 'Feed',
        href: '/social/feed',
        template: 'social/FeedTemplate',
        icon: <FiMessageSquare />,
        description: 'Latest updates from your network',
      },
      {
        label: 'Messages',
        href: '/social/messages',
        template: 'social/MessagesTemplate',
        icon: <FiMail />,
        description: 'Direct messages',
      },
      {
        label: 'Events',
        href: '/social/events',
        template: 'social/EventsTemplate',
        icon: <FiCalendar />,
        description: 'Discover community events',
      },
      {
        label: 'Groups',
        href: '/social/groups',
        template: 'social/GroupsTemplate',
        icon: <FiUsers />,
        description: 'Join communities that share your interests',
      },
      {
        label: 'Followers',
        href: '/social/followers',
        template: 'social/FollowersTemplate',
        icon: <FiUserPlus />,
        description: 'Manage who you follow',
      },
      {
        label: 'Media Library',
        href: '/media/library',
        template: 'media/MediaLibraryTemplate',
        icon: <FiFolder />,
        description: 'Browse and manage uploaded assets',
      },
      {
        label: 'Albums',
        href: '/media/albums',
        template: 'media/AlbumsTemplate',
        icon: <FiGrid />,
        description: 'Organize photos into albums',
      },
      {
        label: 'Video Player',
        href: '/media/video',
        template: 'media/VideoPlayerTemplate',
        icon: <FiSmartphone />,
        description: 'Watch recorded content',
      },
    ],
  },
  {
    title: 'Customer Support',
    pages: [
      {
        label: 'Support Tickets',
        href: '/support/tickets',
        template: 'support/TicketsTemplate',
        icon: <FiInbox />,
        description: 'Open tickets',
      },
      {
        label: 'Ticket Detail',
        href: '/support/ticket-detail',
        template: 'support/TicketDetailTemplate',
        icon: <FiFileText />,
        description: 'Conversation & status',
      },
      {
        label: 'Live Chat',
        href: '/support/live-chat',
        template: 'support/LiveChatTemplate',
        icon: <FiSend />,
        description: 'Chat with an agent',
      },
      {
        label: 'Knowledge Base',
        href: '/support/knowledge-base',
        template: 'support/KnowledgeBaseTemplate',
        icon: <FiBook />,
        description: 'Help articles',
      },
      {
        label: 'FAQs',
        href: '/support/faqs',
        template: 'support/FaqTemplate',
        icon: <FiHelpCircle />,
        description: 'Frequently asked questions',
      },
      {
        label: 'Announcements',
        href: '/support/announcements',
        template: 'support/AnnouncementsTemplate',
        icon: <FiBell />,
        description: 'Service updates',
      },
      {
        label: 'Service Status',
        href: '/support/status',
        template: 'support/ServiceStatusTemplate',
        icon: <FiActivity />,
        description: 'Incidents & uptime',
      },
      {
        label: 'Feedback',
        href: '/support/feedback',
        template: 'support/FeedbackTemplate',
        icon: <FiMessageSquare />,
        description: 'Share feedback',
      },
    ],
  },
  {
    title: 'Email',
    pages: [
      {
        label: 'Inbox',
        href: '/mail/inbox',
        template: 'mail/InboxTemplate',
        icon: <FiInbox />,
        description: 'Your messages',
      },
      {
        label: 'Compose',
        href: '/mail/compose',
        template: 'mail/ComposeTemplate',
        icon: <FiEdit2 />,
        description: 'Write a message',
      },
      {
        label: 'Thread',
        href: '/mail/thread',
        template: 'mail/ThreadTemplate',
        icon: <FiMessageSquare />,
        description: 'Message conversation',
      },
      {
        label: 'Drafts',
        href: '/mail/drafts',
        template: 'mail/DraftsTemplate',
        icon: <FiFileText />,
        description: 'Unsent messages',
      },
      {
        label: 'Sent',
        href: '/mail/sent',
        template: 'mail/SentTemplate',
        icon: <FiSend />,
        description: 'Sent messages',
      },
      {
        label: 'Spam',
        href: '/mail/spam',
        template: 'mail/SpamTemplate',
        icon: <FiAlertOctagon />,
        description: 'Junk messages',
      },
      {
        label: 'Labels',
        href: '/mail/labels',
        template: 'mail/LabelsTemplate',
        icon: <FiTag />,
        description: 'Manage labels',
      },
      {
        label: 'Search',
        href: '/mail/search',
        template: 'mail/MailSearchTemplate',
        icon: <FiSearch />,
        description: 'Find any message',
      },
    ],
  },
  {
    title: 'HR',
    pages: [
      {
        label: 'People Directory',
        href: '/hr/people',
        template: 'hr/PeopleDirectoryTemplate',
        icon: <FiUsers />,
        description: 'Find team members',
      },
      {
        label: 'Org Chart',
        href: '/hr/org-chart',
        template: 'hr/OrgChartTemplate',
        icon: <FiColumns />,
        description: 'Company structure',
      },
      {
        label: 'Hiring Pipeline',
        href: '/hr/hiring',
        template: 'hr/HiringPipelineTemplate',
        icon: <FiUserPlus />,
        description: 'Candidates & stages',
      },
      {
        label: 'Policies',
        href: '/hr/policies',
        template: 'hr/PoliciesTemplate',
        icon: <FiFileText />,
        description: 'Company policies',
      },
      {
        label: 'Benefits',
        href: '/hr/benefits',
        template: 'hr/BenefitsTemplate',
        icon: <FiGift />,
        description: 'Perks & packages',
      },
      {
        label: 'Reviews',
        href: '/hr/reviews',
        template: 'hr/PerformanceReviewsTemplate',
        icon: <FiStar />,
        description: 'Performance reviews',
      },
      {
        label: 'Shift Schedule',
        href: '/hr/shifts',
        template: 'hr/ShiftScheduleTemplate',
        icon: <FiCalendar />,
        description: 'Upcoming shifts',
      },
      {
        label: 'Time Off',
        href: '/hr/time-off',
        template: 'hr/TimeOffTemplate',
        icon: <FiClock />,
        description: 'Leave requests',
      },
    ],
  },
  {
    title: 'Sales & CRM',
    pages: [
      {
        label: 'Accounts',
        href: '/crm/accounts',
        template: 'crm/AccountsTemplate',
        icon: <FiBriefcase />,
        description: 'Customer accounts',
      },
      {
        label: 'Contacts',
        href: '/crm/contacts',
        template: 'crm/CrmContactsTemplate',
        icon: <FiUsers />,
        description: 'People & companies',
      },
      {
        label: 'Leads',
        href: '/crm/leads',
        template: 'crm/LeadsTemplate',
        icon: <FiUserPlus />,
        description: 'New prospects',
      },
      {
        label: 'Deals',
        href: '/crm/deals',
        template: 'crm/DealsTemplate',
        icon: <FiTag />,
        description: 'Open opportunities',
      },
      {
        label: 'Pipeline',
        href: '/crm/pipeline',
        template: 'crm/PipelineTemplate',
        icon: <FiColumns />,
        description: 'Deals by stage',
      },
      {
        label: 'Campaigns',
        href: '/crm/campaigns',
        template: 'crm/CampaignsTemplate',
        icon: <FiSend />,
        description: 'Email campaigns',
      },
      {
        label: 'Quote Builder',
        href: '/crm/quote-builder',
        template: 'crm/QuoteBuilderTemplate',
        icon: <FiEdit3 />,
        description: 'Build a quote',
      },
      {
        label: 'Sales Reports',
        href: '/crm/reports',
        template: 'crm/SalesReportsTemplate',
        icon: <FiBarChart2 />,
        description: 'Team performance',
      },
    ],
  },
  {
    title: 'Learning',
    pages: [
      {
        label: 'My Courses',
        href: '/blog/my-courses',
        template: 'blog/MyCoursesTemplate',
        icon: <FiLayers />,
        description: 'Enrolled courses',
      },
      {
        label: 'Course Catalog',
        href: '/blog/catalog',
        template: 'blog/CourseCatalogTemplate',
        icon: <FiBook />,
        description: 'Browse courses',
      },
      {
        label: 'Course Details',
        href: '/blog/course',
        template: 'blog/CourseDetailTemplate',
        icon: <FiBookOpen />,
        description: 'Curriculum & syllabus',
      },
      {
        label: 'Lesson Player',
        href: '/blog/lesson',
        template: 'blog/LessonPlayerTemplate',
        icon: <FiMonitor />,
        description: 'Watch and learn',
      },
      {
        label: 'Instructors',
        href: '/blog/instructors',
        template: 'blog/InstructorsTemplate',
        icon: <FiUser />,
        description: 'Meet the teachers',
      },
      {
        label: 'Quizzes',
        href: '/blog/quizzes',
        template: 'blog/QuizzesTemplate',
        icon: <FiCheckSquare />,
        description: 'Test your knowledge',
      },
      {
        label: 'Achievements',
        href: '/blog/achievements',
        template: 'blog/AchievementsTemplate',
        icon: <FiStar />,
        description: 'Badges & milestones',
      },
      {
        label: 'Analytics',
        href: '/blog/analytics',
        template: 'blog/LearningAnalyticsTemplate',
        icon: <FiBarChart2 />,
        description: 'Learning progress',
      },
    ],
  },
  {
    title: 'News & Magazine',
    pages: [
      {
        label: 'Article',
        href: '/news/article',
        template: 'news/ArticleTemplate',
        icon: <FiFileText />,
        description: 'Read the full story',
      },
      {
        label: 'Breaking News',
        href: '/news/breaking',
        template: 'news/BreakingNewsTemplate',
        icon: <FiZap />,
        description: 'Latest headlines',
      },
      {
        label: 'Editorial',
        href: '/news/editorial',
        template: 'news/EditorialTemplate',
        icon: <FiEdit3 />,
        description: 'Editor picks',
      },
      {
        label: 'Magazine',
        href: '/news/magazine',
        template: 'news/MagazineGridTemplate',
        icon: <FiBookOpen />,
        description: 'Feature stories',
      },
      {
        label: 'Categories',
        href: '/news/categories',
        template: 'news/NewsCategoriesTemplate',
        icon: <FiGrid />,
        description: 'Browse by topic',
      },
      {
        label: 'Newsletter',
        href: '/news/newsletter',
        template: 'news/NewsletterSignupTemplate',
        icon: <FiMail />,
        description: 'Subscribe by email',
      },
      {
        label: 'Opinion',
        href: '/news/opinion',
        template: 'news/OpinionTemplate',
        icon: <FiMessageSquare />,
        description: 'Columns & views',
      },
      {
        label: 'Press Releases',
        href: '/news/press',
        template: 'news/PressReleasesTemplate',
        icon: <FiUpload />,
        description: 'Media announcements',
      },
    ],
  },
  {
    title: 'Music',
    pages: [
      {
        label: 'Music Home',
        href: '/media/music-home',
        template: 'media/MusicHomeTemplate',
        icon: <FiMonitor />,
        description: 'Home feed',
      },
      {
        label: 'Album',
        href: '/media/album',
        template: 'media/AlbumDetailTemplate',
        icon: <FiLayers />,
        description: 'Album details',
      },
      {
        label: 'Artists',
        href: '/media/artists',
        template: 'media/ArtistsTemplate',
        icon: <FiUser />,
        description: 'Followed artists',
      },
      {
        label: 'Charts',
        href: '/media/charts',
        template: 'media/ChartsTemplate',
        icon: <FiBarChart2 />,
        description: 'Top tracks',
      },
      {
        label: 'Now Playing',
        href: '/media/now-playing',
        template: 'media/NowPlayingTemplate',
        icon: <FiClock />,
        description: 'Current track',
      },
      {
        label: 'Playlist',
        href: '/media/playlist',
        template: 'media/PlaylistTemplate',
        icon: <FiFolder />,
        description: 'Your curated mix',
      },
      {
        label: 'Lyrics',
        href: '/media/lyrics',
        template: 'media/LyricsTemplate',
        icon: <FiFileText />,
        description: 'Sing along',
      },
      {
        label: 'Search',
        href: '/media/search',
        template: 'media/MusicSearchTemplate',
        icon: <FiSearch />,
        description: 'Find music',
      },
    ],
  },
  {
    title: 'Video Streaming',
    pages: [
      {
        label: 'Streaming Home',
        href: '/media/streaming-home',
        template: 'media/StreamingHomeTemplate',
        icon: <FiMonitor />,
        description: 'Recommendations',
      },
      {
        label: 'Movie',
        href: '/media/movie',
        template: 'media/MovieDetailTemplate',
        icon: <FiBookOpen />,
        description: 'Movie details',
      },
      {
        label: 'Series',
        href: '/media/series',
        template: 'media/TvSeriesTemplate',
        icon: <FiLayers />,
        description: 'Browse TV shows',
      },
      {
        label: 'Live TV',
        href: '/social/live',
        template: 'social/LiveChannelsTemplate',
        icon: <FiZap />,
        description: 'Live channels',
      },
      {
        label: 'Continue Watching',
        href: '/media/continue-watching',
        template: 'media/ContinueWatchingTemplate',
        icon: <FiClock />,
        description: 'Resume titles',
      },
      {
        label: 'My List',
        href: '/media/my-list',
        template: 'media/MyListTemplate',
        icon: <FiHeart />,
        description: 'Titles you saved',
      },
      {
        label: 'History',
        href: '/social/history',
        template: 'social/WatchHistoryTemplate',
        icon: <FiRefreshCw />,
        description: 'Watch history',
      },
      {
        label: 'Search',
        href: '/social/search',
        template: 'social/StreamingSearchTemplate',
        icon: <FiSearch />,
        description: 'Find titles',
      },
    ],
  },
  {
    title: 'Gaming',
    pages: [
      {
        label: 'Game Catalog',
        href: '/mail/catalog',
        template: 'mail/GameCatalogTemplate',
        icon: <FiGrid />,
        description: 'Browse every title',
      },
      {
        label: 'Game Details',
        href: '/landing/game',
        template: 'landing/GameDetailTemplate',
        icon: <FiMonitor />,
        description: 'Game details',
      },
      {
        label: 'Challenges',
        href: '/social/challenges',
        template: 'social/GameChallengesTemplate',
        icon: <FiTarget />,
        description: 'Daily & weekly quests',
      },
      {
        label: 'Leaderboards',
        href: '/social/leaderboards',
        template: 'social/LeaderboardsTemplate',
        icon: <FiBarChart2 />,
        description: 'Top players',
      },
      {
        label: 'Live Matches',
        href: '/social/matches',
        template: 'social/LiveMatchesTemplate',
        icon: <FiActivity />,
        description: 'Ongoing games',
      },
      {
        label: 'Players',
        href: '/social/players',
        template: 'social/PlayerProfilesTemplate',
        icon: <FiUser />,
        description: 'Player profiles',
      },
      {
        label: 'Tournaments',
        href: '/social/tournaments',
        template: 'social/TournamentsTemplate',
        icon: <FiShield />,
        description: 'Competitions',
      },
      {
        label: 'Game News',
        href: '/social/news',
        template: 'social/GameNewsTemplate',
        icon: <FiZap />,
        description: 'Patch notes & updates',
      },
    ],
  },
  {
    title: 'Sports',
    pages: [
      {
        label: 'Live Scores',
        href: '/news/scores',
        template: 'news/LiveScoresTemplate',
        icon: <FiActivity />,
        description: 'Scores from today',
      },
      {
        label: 'Fixtures',
        href: '/news/fixtures',
        template: 'news/FixturesTemplate',
        icon: <FiCalendar />,
        description: 'Upcoming matches',
      },
      {
        label: 'Match Details',
        href: '/news/match',
        template: 'news/MatchDetailTemplate',
        icon: <FiMonitor />,
        description: 'Match details',
      },
      {
        label: 'Standings',
        href: '/news/standings',
        template: 'news/SeasonStandingsTemplate',
        icon: <FiColumns />,
        description: 'League table',
      },
      {
        label: 'Player Stats',
        href: '/news/stats',
        template: 'news/PlayerStatsTemplate',
        icon: <FiBarChart2 />,
        description: 'Goals & assists',
      },
      {
        label: 'Team Roster',
        href: '/news/roster',
        template: 'news/TeamRosterTemplate',
        icon: <FiUsers />,
        description: 'Meet the squad',
      },
      {
        label: 'Favorite Teams',
        href: '/news/favorites',
        template: 'news/FavoriteTeamsTemplate',
        icon: <FiHeart />,
        description: 'Teams you follow',
      },
      {
        label: 'Sports News',
        href: '/news/news',
        template: 'news/SportsNewsTemplate',
        icon: <FiBell />,
        description: 'Latest headlines',
      },
    ],
  },
  {
    title: 'Travel',
    pages: [
      {
        label: 'Bookings',
        href: '/travel/bookings',
        template: 'travel/BookingsTemplate',
        icon: <FiCalendar />,
        description: 'Upcoming trips',
      },
      {
        label: 'Booking Search',
        href: '/travel/search',
        template: 'travel/BookingSearchTemplate',
        icon: <FiSearch />,
        description: 'Find stays',
      },
      {
        label: 'Hotel',
        href: '/travel/hotel',
        template: 'travel/HotelDetailTemplate',
        icon: <FiLayers />,
        description: 'Hotel details',
      },
      {
        label: 'Destinations',
        href: '/travel/destinations',
        template: 'travel/DestinationsTemplate',
        icon: <FiMapPin />,
        description: 'Explore places',
      },
      {
        label: 'Guides',
        href: '/travel/guides',
        template: 'travel/TravelGuidesTemplate',
        icon: <FiBook />,
        description: 'City guides',
      },
      {
        label: 'Stories',
        href: '/travel/stories',
        template: 'travel/TravelStoriesTemplate',
        icon: <FiBookOpen />,
        description: 'Travel experiences',
      },
      {
        label: 'Packing List',
        href: '/travel/packing',
        template: 'travel/PackingListTemplate',
        icon: <FiCheckSquare />,
        description: 'What to pack',
      },
      {
        label: 'Trip Planner',
        href: '/travel/planner',
        template: 'travel/TripPlannerTemplate',
        icon: <FiMap />,
        description: 'Plan an itinerary',
      },
    ],
  },
  {
    title: 'Food & Dining',
    pages: [
      {
        label: 'Restaurants',
        href: '/health/restaurants',
        template: 'health/RestaurantListTemplate',
        icon: <FiMapPin />,
        description: 'Find a place to eat',
      },
      {
        label: 'Restaurant',
        href: '/health/restaurant',
        template: 'health/RestaurantDetailTemplate',
        icon: <FiStar />,
        description: 'Restaurant details',
      },
      {
        label: 'Menu',
        href: '/health/menu',
        template: 'health/MenuTemplate',
        icon: <FiFileText />,
        description: 'Dishes and prices',
      },
      {
        label: 'Recipes',
        href: '/health/recipes',
        template: 'health/RecipesTemplate',
        icon: <FiBookOpen />,
        description: 'Cook at home',
      },
      {
        label: 'Recipe',
        href: '/health/recipe',
        template: 'health/RecipeDetailTemplate',
        icon: <FiBook />,
        description: 'Step by step',
      },
      {
        label: 'Reservations',
        href: '/health/reservations',
        template: 'health/ReservationsTemplate',
        icon: <FiCalendar />,
        description: 'Upcoming bookings',
      },
      {
        label: 'Delivery',
        href: '/health/delivery',
        template: 'health/FoodDeliveryTemplate',
        icon: <FiTruck />,
        description: 'Order in',
      },
      {
        label: 'Wine List',
        href: '/health/wine',
        template: 'health/WineListTemplate',
        icon: <FiTag />,
        description: 'Pairings & bottles',
      },
    ],
  },
  {
    title: 'Health & Fitness',
    pages: [
      {
        label: 'Health Dashboard',
        href: '/health/dashboard',
        template: 'health/HealthDashboardTemplate',
        icon: <FiGrid />,
        description: 'Daily overview',
      },
      {
        label: 'Activity Tracker',
        href: '/health/activity',
        template: 'health/ActivityTrackerTemplate',
        icon: <FiActivity />,
        description: 'Daily movement',
      },
      {
        label: 'Workout Plans',
        href: '/health/workout',
        template: 'health/WorkoutPlannerTemplate',
        icon: <FiZap />,
        description: 'Training routines',
      },
      {
        label: 'Nutrition Tracker',
        href: '/health/nutrition',
        template: 'health/NutritionTrackerTemplate',
        icon: <FiHeart />,
        description: 'Macros & meals',
      },
      {
        label: 'Sleep Tracker',
        href: '/health/sleep',
        template: 'health/SleepTrackerTemplate',
        icon: <FiClock />,
        description: 'Recovery and rest',
      },
      {
        label: 'Water Intake',
        href: '/health/water',
        template: 'health/WaterIntakeTemplate',
        icon: <FiRefreshCw />,
        description: 'Hydration goal',
      },
      {
        label: 'Goals',
        href: '/health/goals',
        template: 'health/GoalsTemplate',
        icon: <FiTarget />,
        description: 'Daily health targets',
      },
      {
        label: 'Health Profile',
        href: '/health/profile',
        template: 'health/HealthProfileTemplate',
        icon: <FiUser />,
        description: 'Your health data',
      },
    ],
  },
  {
    title: 'Real Estate',
    pages: [
      {
        label: 'Property Listings',
        href: '/travel/listings',
        template: 'travel/PropertyListingsTemplate',
        icon: <FiGrid />,
        description: 'Browse properties',
      },
      {
        label: 'Property Detail',
        href: '/travel/property',
        template: 'travel/PropertyDetailTemplate',
        icon: <FiLayers />,
        description: 'Property details',
      },
      {
        label: 'Search Filters',
        href: '/travel/property-search',
        template: 'travel/SearchFiltersTemplate',
        icon: <FiSearch />,
        description: 'Refine results',
      },
      {
        label: 'Map View',
        href: '/travel/map',
        template: 'travel/MapViewTemplate',
        icon: <FiMap />,
        description: 'Neighborhood map',
      },
      {
        label: 'Saved Properties',
        href: '/travel/saved',
        template: 'travel/SavedPropertiesTemplate',
        icon: <FiHeart />,
        description: 'Your shortlist',
      },
      {
        label: 'Mortgage Calculator',
        href: '/travel/mortgage',
        template: 'travel/MortgageCalculatorTemplate',
        icon: <FiCreditCard />,
        description: 'Monthly payments',
      },
      {
        label: 'Open Houses',
        href: '/travel/open-houses',
        template: 'travel/OpenHousesTemplate',
        icon: <FiCalendar />,
        description: 'Tour schedules',
      },
      {
        label: 'Agent Profile',
        href: '/travel/agents',
        template: 'travel/AgentProfileTemplate',
        icon: <FiUser />,
        description: 'Meet the agent',
      },
    ],
  },
  {
    title: 'Smart Home / IoT',
    pages: [
      {
        label: 'Device Dashboard',
        href: '/developer/dashboard',
        template: 'developer/DeviceDashboardTemplate',
        icon: <FiMonitor />,
        description: 'All connected devices',
      },
      {
        label: 'Device Detail',
        href: '/developer/device',
        template: 'developer/DeviceDetailTemplate',
        icon: <FiZap />,
        description: 'Control a device',
      },
      {
        label: 'Scenes',
        href: '/developer/scenes',
        template: 'developer/ScenesTemplate',
        icon: <FiLayers />,
        description: 'One-tap routines',
      },
      {
        label: 'Automations',
        href: '/developer/automations',
        template: 'developer/AutomationsTemplate',
        icon: <FiClock />,
        description: 'Scheduled actions',
      },
      {
        label: 'Energy Usage',
        href: '/developer/energy',
        template: 'developer/EnergyUsageTemplate',
        icon: <FiActivity />,
        description: 'Consumption trends',
      },
      {
        label: 'Security',
        href: '/auth/home-security',
        template: 'auth/SecurityTemplate',
        icon: <FiShield />,
        description: 'Cameras & sensors',
      },
      {
        label: 'Sensor Data',
        href: '/developer/sensors',
        template: 'developer/SensorDataTemplate',
        icon: <FiBarChart2 />,
        description: 'Live readings',
      },
      {
        label: 'Smart Home Settings',
        href: '/developer/settings',
        template: 'developer/SmartHomeSettingsTemplate',
        icon: <FiSettings />,
        description: 'Preferences',
      },
    ],
  },
  {
    title: 'Portfolio',
    pages: [
      {
        label: 'Portfolio Overview',
        href: '/finance/overview',
        template: 'finance/PortfolioOverviewTemplate',
        icon: <FiTrendingUp />,
        description: 'Net worth & gains',
      },
      {
        label: 'Holdings',
        href: '/finance/holdings',
        template: 'finance/HoldingsTemplate',
        icon: <FiBriefcase />,
        description: 'Positions & value',
      },
      {
        label: 'Transactions',
        href: '/mail/transactions',
        template: 'mail/TransactionsTemplate',
        icon: <FiRefreshCw />,
        description: 'Buy & sell history',
      },
      {
        label: 'Performance',
        href: '/finance/performance',
        template: 'finance/PerformanceTemplate',
        icon: <FiBarChart2 />,
        description: 'Returns over time',
      },
      {
        label: 'Allocation',
        href: '/mail/allocation',
        template: 'mail/AllocationTemplate',
        icon: <FiColumns />,
        description: 'Asset mix',
      },
      {
        label: 'Watchlist',
        href: '/mail/watchlist',
        template: 'mail/WatchlistTemplate',
        icon: <FiStar />,
        description: 'Tracked symbols',
      },
      {
        label: 'Alerts',
        href: '/finance/alerts',
        template: 'finance/AlertsTemplate',
        icon: <FiBell />,
        description: 'Price notifications',
      },
      {
        label: 'Dividend Income',
        href: '/finance/dividends',
        template: 'finance/DividendIncomeTemplate',
        icon: <FiDollarSign />,
        description: 'Payout tracking',
      },
      {
        label: 'Portfolio Settings',
        href: '/finance/settings',
        template: 'finance/PortfolioSettingsTemplate',
        icon: <FiSettings />,
        description: 'Preferences',
      },
    ],
  },
];

export const TEMPLATE_COUNT = new Set(
  GROUPS.flatMap((group) => group.pages.map((page) => page.template))
).size;

export const TemplatesLevel: FC = () => {
  const [search, setSearch] = useState('');

  const term = search.trim().toLowerCase();
  const visible = term
    ? GROUPS.map((group) => ({
        ...group,
        pages: group.pages.filter((page) =>
          [page.label, page.template, page.description ?? '']
            .join(' ')
            .toLowerCase()
            .includes(term)
        ),
      })).filter((group) => group.pages.length > 0)
    : GROUPS;

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-3 p-5">
      <h2 className="text-base-content mb-1 text-2xl font-light tracking-tight">
        Templates Directory
      </h2>
      <label className="input input-bordered flex w-full items-center gap-2">
        <svg
          aria-hidden="true"
          className="text-base-content/50 size-4 shrink-0"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          viewBox="0 0 24 24">
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M21 21l-4.35-4.35M17 10.5a6.5 6.5 0 11-13 0 6.5 6.5 0 0113 0z"
          />
        </svg>
        <input
          type="search"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          data-testid="templates-search"
          placeholder="Search templates…"
          className="grow"
        />
      </label>
      <div className="flex flex-col gap-3">
        {visible.map((group) => (
          <details
            key={group.title}
            className="collapse-arrow border-base-content/10 bg-base-200 collapse border"
            open>
            <summary className="collapse-title text-base-content/60 font-mono text-xs uppercase">
              {group.title}
              <span className="badge badge-ghost badge-sm ml-2">
                {group.pages.length}
              </span>
            </summary>
            <div className="collapse-content">
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {group.pages.map((page) => (
                  <Link
                    key={page.href}
                    href={page.href}
                    className="border-base-content/10 bg-base-200 hover:border-base-content/30 flex items-center gap-3 rounded-xl border p-4 transition-colors">
                    <span className="text-base-content/60 shrink-0">
                      {page.icon}
                    </span>
                    <div className="min-w-0">
                      <span className="text-base-content block truncate text-sm font-medium">
                        {page.label}
                      </span>
                      {page.description && (
                        <span className="text-base-content/50 block truncate text-xs">
                          {page.description}
                        </span>
                      )}
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
};

TemplatesLevel.displayName = 'TemplatesLevel';
