openapi: 3.0.0
paths:
  /countries:
    get:
      operationId: CountriesController_getCountries
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountriesDto'
      tags: &a1
        - countries
  /countries/currencies:
    get:
      operationId: CountriesController_getCurrencies
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrenciesDto'
      tags: *a1
  /countries/languages:
    get:
      operationId: CountriesController_getLanguages
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguagesDto'
      tags: *a1
  /vietnam/ethnic-groups:
    get:
      operationId: VietnamController_getEthnicGroups
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EthnicGroupsResponseDto'
      tags: &a2
        - vietnam
  /vietnam/license-plates:
    get:
      operationId: VietnamController_getLicensePlates
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicensePlatesResponseDto'
      tags: *a2
  /crypto/coins:
    get:
      operationId: CryptoController_getCountries
      parameters:
        - name: limit
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinsResponseDto'
      tags:
        - crypto
  /health:
    get:
      operationId: HealthController_getHealth
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponseDto'
      tags:
        - health
  /news/google:
    get:
      operationId: NewsController_getGoogle
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleResponseDto'
      tags: &a3
        - news
  /news/sources:
    get:
      operationId: NewsController_getSources
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsSourcesDto'
      tags: *a3
  /tarot/cards:
    get:
      operationId: TarotController_getCards
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarotCardsResponseDto'
      tags:
        - tarot
info:
  title: hieudoanm
  description: Hieu Doan
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    CountryDto:
      type: object
      properties:
        region:
          type: string
        subregion:
          type: string
        currencies:
          type: object
        languages:
          type: object
      required:
        - region
        - subregion
        - currencies
        - languages
    CountriesDto:
      type: object
      properties:
        total:
          type: number
        countries:
          type: array
          items:
            $ref: '#/components/schemas/CountryDto'
      required:
        - total
        - countries
    CurrencyDto:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        symbol:
          type: string
      required:
        - code
        - name
        - symbol
    CurrenciesDto:
      type: object
      properties:
        total:
          type: number
        currencies:
          type: array
          items:
            $ref: '#/components/schemas/CurrencyDto'
      required:
        - total
        - currencies
    LanguageDto:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
      required:
        - code
        - name
    LanguagesDto:
      type: object
      properties:
        total:
          type: number
        languages:
          type: array
          items:
            $ref: '#/components/schemas/LanguageDto'
      required:
        - total
        - languages
    EthnicGroupDto:
      type: object
      properties: {}
    EthnicGroupsResponseDto:
      type: object
      properties:
        total:
          type: number
        ethnicGroups:
          default: []
          type: array
          items:
            $ref: '#/components/schemas/EthnicGroupDto'
      required:
        - total
        - ethnicGroups
    LicensePlateDto:
      type: object
      properties: {}
    LicensePlatesResponseDto:
      type: object
      properties:
        total:
          type: number
        licensePlates:
          default: []
          type: array
          items:
            $ref: '#/components/schemas/LicensePlateDto'
      required:
        - total
        - licensePlates
    CoinDto:
      type: object
      properties:
        uuid:
          type: string
        symbol:
          type: string
        name:
          type: string
        color:
          type: string
        iconUrl:
          type: string
        marketCap:
          type: string
        price:
          type: string
        listedAt:
          type: number
        tier:
          type: number
        change:
          type: string
        rank:
          type: number
        sparkline:
          type: array
          items:
            type: string
        lowVolume:
          type: boolean
          default: false
        coinrankingUrl:
          type: string
        24hVolume:
          type: string
        btcPrice:
          type: number
      required:
        - uuid
        - symbol
        - name
        - color
        - iconUrl
        - marketCap
        - price
        - listedAt
        - tier
        - change
        - rank
        - sparkline
        - lowVolume
        - coinrankingUrl
        - 24hVolume
        - btcPrice
    CoinsResponseDto:
      type: object
      properties:
        total:
          type: number
          default: 0
        coins:
          default: []
          type: array
          items:
            $ref: '#/components/schemas/CoinDto'
      required:
        - total
        - coins
    HealthResponseDto:
      type: object
      properties:
        status:
          type: string
      required:
        - status
    GoogleCountryDto:
      type: object
      properties:
        country:
          type: string
        queries:
          type: array
          items:
            type: string
      required:
        - country
        - queries
    GoogleResponseDto:
      type: object
      properties:
        total:
          type: number
        countries:
          type: array
          items:
            $ref: '#/components/schemas/GoogleCountryDto'
      required:
        - total
        - countries
    NewsSourceDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        category:
          type: string
        language:
          type: string
        country:
          type: string
      required:
        - id
        - name
        - description
        - url
        - category
        - language
        - country
    NewsSourcesDto:
      type: object
      properties:
        total:
          type: number
        sources:
          type: array
          items:
            $ref: '#/components/schemas/NewsSourceDto'
      required:
        - total
        - sources
    TarotCardDto:
      type: object
      properties: {}
    TarotCardsResponseDto:
      type: object
      properties:
        total:
          type: number
        cards:
          default: []
          type: array
          items:
            $ref: '#/components/schemas/TarotCardDto'
      required:
        - total
        - cards
