import { ComponentType, FC } from 'react';

import {
  Base64Modal,
  BlackjackModal,
  BrailleModal,
  BreakingBadModal,
  CalculatorModal,
  CalendarTrackerModal,
  CameraModal,
  ChatModal,
  ChessClockModal,
  ClipboardModal,
  ColorsModal,
  ConverterModal,
  CountdownModal,
  CronModal,
  DOIModal,
  EloModal,
  EmojisModal,
  FigletModal,
  FlashcardsModal,
  Game2048Modal,
  GitHubSocialPreviewModal,
  HouseModal,
  InflationModal,
  InstaSizeModal,
  InvoiceParserModal,
  IPModal,
  JSONSchemaModal,
  KaprekarModal,
  LanguagesEnglishModal,
  LegislationModal,
  LeetSpeakModal,
  LogMARChartModal,
  ManifestModal,
  MarkdownModal,
  MorseModal,
  NoSleepModal,
  OpenAPI2Postman,
  PalindromeModal,
  PeriodicTableModal,
  PiModal,
  PitchModal,
  PdModal,
  PokedexModal,
  PokerModal,
  PomodoroModal,
  ProxyModal,
  QRCodeModal,
  QuizifyModal,
  RecallModal,
  RedactModal,
  ResumeModal,
  ResumeTimelineModal,
  RockPaperScissorsModal,
  RegexModal,
  SheetsModal,
  ShopifyDetectModal,
  SignModal,
  SlidesModal,
  SnakeModal,
  SnellenChartModal,
  SplitBillModal,
  SudokuModal,
  SVGModal,
  T3Modal,
  TaxModal,
  TowersModal,
  TumblingEChartModal,
  TypoglycemiaModal,
  UUIDModal,
  WatchFaceModal,
  WordleModal,
  YouTubeThumbnailsModal,
} from './dynamic-imports';
import { ModalId } from './types';

export const MODAL_MAP: Record<
  ModalId,
  FC<{ onClose: () => void }> | ComponentType<{ onClose: () => void }>
> = {
  game2048: Game2048Modal,
  base64: Base64Modal,
  blackjack: BlackjackModal,
  braille: BrailleModal,
  'breaking-bad': BreakingBadModal,
  calculator: CalculatorModal,
  'calendar-tracker': CalendarTrackerModal,
  camera: CameraModal,
  chat: ChatModal,
  'chess-clock': ChessClockModal,
  clipboard: ClipboardModal,
  colors: ColorsModal,
  converter: ConverterModal,
  countdown: CountdownModal,
  cron: CronModal,
  doi: DOIModal,
  elo: EloModal,
  emojis: EmojisModal,
  english: LanguagesEnglishModal,
  figlet: FigletModal,
  flashcards: FlashcardsModal,
  'github-social-preview': GitHubSocialPreviewModal,
  house: HouseModal,
  inflation: InflationModal,
  instasize: InstaSizeModal,
  'invoice-parser': InvoiceParserModal,
  ip: IPModal,
  'json-schema': JSONSchemaModal,
  kaprekar: KaprekarModal,
  legislation: LegislationModal,
  logmar: LogMARChartModal,
  manifest: ManifestModal,
  markdown: MarkdownModal,
  morse: MorseModal,
  leetspeak: LeetSpeakModal,
  'no-sleep': NoSleepModal,
  openapi: OpenAPI2Postman,
  palindrome: PalindromeModal,
  pd: PdModal,
  'periodic-table': PeriodicTableModal,
  pi: PiModal,
  pitch: PitchModal,
  pokedex: PokedexModal,
  poker: PokerModal,
  pomodoro: PomodoroModal,
  proxy: ProxyModal,
  qr: QRCodeModal,
  quizify: QuizifyModal,
  recall: RecallModal,
  redact: RedactModal,
  rps: RockPaperScissorsModal,
  regex: RegexModal,
  resume: ResumeModal,
  sheets: SheetsModal,
  'shopify-detect': ShopifyDetectModal,
  sign: SignModal,
  slides: SlidesModal,
  snellen: SnellenChartModal,
  svg: SVGModal,
  sudoku: SudokuModal,
  t3: T3Modal,
  tax: TaxModal,
  'split-bill': SplitBillModal,
  towers: TowersModal,
  'tumbling-e': TumblingEChartModal,
  typoglycemia: TypoglycemiaModal,
  uuid: UUIDModal,
  watchface: WatchFaceModal,
  wordle: WordleModal,
  'youtube-thumbnails': YouTubeThumbnailsModal,
  snake: SnakeModal,
  'resume-timeline': ResumeTimelineModal,
};
