import { ComponentType, FC } from 'react';

import {
  BarcodeModal,
  Base64Modal,
  BlackjackModal,
  BrailleModal,
  BreakingBadModal,
  CalculatorModal,
  CalendarTrackerModal,
  CameraModal,
  ChatModal,
  ChessClockModal,
  ClipboardModal,
  ColorsModal,
  ConverterModal,
  CountdownModal,
  CronModal,
  DOIModal,
  DaysCountModal,
  EloModal,
  EmojisModal,
  FigletModal,
  FileArchiveModal,
  FileConvertModal,
  FlashcardsModal,
  Game2048Modal,
  GitHubSocialPreviewModal,
  GraphModal,
  HouseModal,
  ImageAiModal,
  ImageConvertModal,
  ImageBlurModal,
  ImageCombinerModal,
  ImageCreateModal,
  ImageEditModal,
  ImageOcrModal,
  InflationModal,
  InstaSizeModal,
  InvoiceParserModal,
  IPModal,
  JSONSchemaModal,
  KaprekarModal,
  LanguagesEnglishModal,
  LegislationModal,
  LeetSpeakModal,
  LoremIpsumModal,
  LogMARChartModal,
  ManifestModal,
  MarkdownModal,
  MorseModal,
  NoSleepModal,
  OpenAPI2Postman,
  PalindromeModal,
  PdfArrangeModal,
  PdfCombineModal,
  PdfConvertModal,
  PdfCreateModal,
  PdfEditModal,
  PdfExtractModal,
  PdfInspectModal,
  PdfMaintainModal,
  PdfSecurityModal,
  PdfTranslateModal,
  PdModal,
  PeriodicTableModal,
  PiModal,
  PitchModal,
  PokedexModal,
  PokerModal,
  PomodoroModal,
  ProxyModal,
  QRCodeModal,
  QuizifyModal,
  RecallModal,
  RegexModal,
  ResumeModal,
  ResumeTimelineModal,
  RockPaperScissorsModal,
  SheetsModal,
  ShopifyDetectModal,
  SignModal,
  SlidesModal,
  SnakeModal,
  SnellenChartModal,
  SplitBillModal,
  SudokuModal,
  SVGModal,
  ScreenRecorderModal,
  T3Modal,
  TaxModal,
  TextToolsModal,
  TowersModal,
  TumblingEChartModal,
  TypoglycemiaModal,
  UUIDModal,
  VideoAudioModal,
  VideoConvertModal,
  VideoDownloadModal,
  VideoEditModal,
  VideoProcessModal,
  WatchFaceModal,
  WordleModal,
  WriteBusinessModal,
  WriteContentModal,
  WriteGenerateModal,
  WriteImproveModal,
  WriteLegalModal,
  WriteMarketingModal,
  WriteSocialModal,
  YouTubeThumbnailsModal,
} from './dynamic-imports';
import { ModalId } from './types';

export const MODAL_MAP: Record<
  ModalId,
  FC<{ onClose: () => void }> | ComponentType<{ onClose: () => void }>
> = {
  game2048: Game2048Modal,
  barcode: BarcodeModal,
  base64: Base64Modal,
  blackjack: BlackjackModal,
  braille: BrailleModal,
  'breaking-bad': BreakingBadModal,
  calculator: CalculatorModal,
  'calendar-tracker': CalendarTrackerModal,
  camera: CameraModal,
  chat: ChatModal,
  'chess-clock': ChessClockModal,
  clipboard: ClipboardModal,
  colors: ColorsModal,
  converter: ConverterModal,
  countdown: CountdownModal,
  cron: CronModal,
  doi: DOIModal,
  elo: EloModal,
  emojis: EmojisModal,
  english: LanguagesEnglishModal,
  figlet: FigletModal,
  flashcards: FlashcardsModal,
  'github-social-preview': GitHubSocialPreviewModal,
  house: HouseModal,
  inflation: InflationModal,
  instasize: InstaSizeModal,
  'invoice-parser': InvoiceParserModal,
  ip: IPModal,
  'json-schema': JSONSchemaModal,
  kaprekar: KaprekarModal,
  legislation: LegislationModal,
  logmar: LogMARChartModal,
  manifest: ManifestModal,
  markdown: MarkdownModal,
  morse: MorseModal,
  leetspeak: LeetSpeakModal,
  'lorem-ipsum': LoremIpsumModal,
  'no-sleep': NoSleepModal,
  openapi: OpenAPI2Postman,
  palindrome: PalindromeModal,
  pd: PdModal,
  'periodic-table': PeriodicTableModal,
  pi: PiModal,
  pitch: PitchModal,
  pokedex: PokedexModal,
  poker: PokerModal,
  pomodoro: PomodoroModal,
  proxy: ProxyModal,
  qr: QRCodeModal,
  quizify: QuizifyModal,
  recall: RecallModal,
  redact: PdfEditModal,
  'pdf-combine': PdfCombineModal,
  'pdf-edit': PdfEditModal,
  'pdf-extract': PdfExtractModal,
  'pdf-inspect': PdfInspectModal,
  'pdf-maintain': PdfMaintainModal,
  'pdf-security': PdfSecurityModal,
  rps: RockPaperScissorsModal,
  regex: RegexModal,
  resume: ResumeModal,
  sheets: SheetsModal,
  'shopify-detect': ShopifyDetectModal,
  sign: SignModal,
  slides: SlidesModal,
  snellen: SnellenChartModal,
  svg: SVGModal,
  sudoku: SudokuModal,
  t3: T3Modal,
  tax: TaxModal,
  'split-bill': SplitBillModal,
  towers: TowersModal,
  'tumbling-e': TumblingEChartModal,
  typoglycemia: TypoglycemiaModal,
  uuid: UUIDModal,
  watchface: WatchFaceModal,
  wordle: WordleModal,
  'youtube-thumbnails': YouTubeThumbnailsModal,
  snake: SnakeModal,
  'resume-timeline': ResumeTimelineModal,
  'days-count': DaysCountModal,
  'file-convert': FileConvertModal,
  graph: GraphModal,
  'image-ai': ImageAiModal,
  'image-convert': ImageConvertModal,
  'image-edit': ImageEditModal,
  'pdf-arrange': PdfArrangeModal,
  'pdf-convert': PdfConvertModal,
  'video-convert': VideoConvertModal,
  'video-edit': VideoEditModal,
  'write-generate': WriteGenerateModal,
  'write-improve': WriteImproveModal,
  'write-social': WriteSocialModal,
  'video-download': VideoDownloadModal,
  'video-audio': VideoAudioModal,
  'write-business': WriteBusinessModal,
  'write-marketing': WriteMarketingModal,
  'write-legal': WriteLegalModal,
  'file-archive': FileArchiveModal,
  'image-create': ImageCreateModal,
  'image-ocr': ImageOcrModal,
  'image-blur': ImageBlurModal,
  'write-content': WriteContentModal,
  'pdf-create': PdfCreateModal,
  'pdf-translate': PdfTranslateModal,
  'text-tools': TextToolsModal,
  'image-combiner': ImageCombinerModal,
  'screen-recorder': ScreenRecorderModal,
  'video-process': VideoProcessModal,
};
