import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';

export const TOOL_SECTION_LABELS: Record<string, string> = {
  ai: 'AI',
  casino: 'Casino',
  clocks: 'Clocks',
  converter: 'Converter',
  'data-csv': 'Data CSV',
  'data-excel': 'Data Excel',
  'data-utility': 'Data Utility',
  'data-xml-json': 'Data XML/JSON',
  developer: 'Developer',
  editors: 'Editors',
  education: 'Education',
  eyes: 'Eyes',
  financial: 'Financial',
  format: 'Format',
  games: 'Games',
  'image-convert-gif': 'GIF Convert',
  'image-convert-heic': 'HEIC Convert',
  'image-convert-jpg': 'JPG Convert',
  'image-convert-png': 'PNG Convert',
  'image-convert-psd': 'PSD Convert',
  'image-convert-svg': 'SVG Convert',
  'image-convert-tiff': 'TIFF Convert',
  'image-convert-webp': 'WebP Convert',
  'image-create': 'Image Create',
  'image-edit': 'Image Edit',
  'image-effect': 'Image Effect',
  'image-scan': 'Image Scan',
  memory: 'Memory',
  'pdf-convert': 'PDF Convert',
  'pdf-create': 'PDF Create',
  'pdf-ebook': 'PDF Ebook',
  'pdf-edit': 'PDF Edit',
  'pdf-extract': 'PDF Extract',
  'pdf-misc': 'PDF Misc',
  utilities: 'Utilities',
  'video-audio': 'Video Audio',
  'video-convert-aac': 'AAC Convert',
  'video-convert-avi': 'AVI Convert',
  'video-convert-flv': 'FLV Convert',
  'video-convert-gif': 'GIF Convert',
  'video-convert-m4a': 'M4A Convert',
  'video-convert-mkv': 'MKV Convert',
  'video-convert-mov': 'MOV Convert',
  'video-convert-mp4': 'MP4 Convert',
  'video-convert-ogg': 'OGG Convert',
  'video-convert-webm': 'WebM Convert',
  'video-convert-wmv': 'WMV Convert',
  'video-download': 'Video Download',
  'video-edit': 'Video Edit',
  visualization: 'Visualization',
  'write-article': 'Write Article',
  'write-business': 'Write Business',
  'write-content': 'Write Content',
  'write-edit': 'Write Edit',
  'write-misc': 'Write Misc',
  'write-real-estate': 'Write Real Estate',
  'write-social': 'Write Social',
};

export const getToolSectionDefs = (
  toolSections: Record<string, Tool[]>
): { label: string; items: Tool[] }[] =>
  Object.entries(TOOL_SECTION_LABELS).map(([key, label]) => ({
    label,
    items: toolSections[key] ?? [],
  }));
