import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';

import { ModalId } from './types';

export const makeTools = (
  open: (id: ModalId) => () => void
): Record<string, Tool[]> => ({
  ai: [
    {
      label: 'Remove BG',
      description: 'AI Background',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'delete',
        'erase',
        'clear',
        'removal',
        'backdrop',
        'background-removal',
      ],
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('ai-remove-bg'),
    },
    {
      label: 'Restore',
      description: 'AI Photo Restore',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'restoration',
        'recover',
        'repair',
        'fix',
        'old-photo',
      ],
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('ai-restore'),
    },
    {
      label: 'Colorize',
      description: 'AI Colorize',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'colour',
        'colorization',
        'black-and-white',
        'bw',
      ],
      emoji: '🎨',
      color: '#3b82f6',
      onClick: open('ai-colorize'),
    },
    {
      label: 'Unblur',
      description: 'AI Deblur',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'sharpen',
        'focus',
        'blurry',
      ],
      emoji: '👁️',
      color: '#3b82f6',
      onClick: open('ai-unblur'),
    },
    {
      label: 'Remove Watermark',
      description: 'AI Clean',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'delete',
        'erase',
        'clear',
        'removal',
        'watermark-removal',
        'logo',
      ],
      emoji: '💧',
      color: '#3b82f6',
      onClick: open('ai-remove-watermark'),
    },
    {
      label: 'Generate',
      description: 'AI Image Gen',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'generation',
        'create',
        'ai-art',
        'text-to-image',
        'stable-diffusion',
        'dalle',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '✨',
      color: '#3b82f6',
      onClick: open('ai-generate'),
    },
    {
      label: 'Remove Person',
      description: 'AI Object Removal',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'delete',
        'erase',
        'clear',
      ],
      emoji: '🚶',
      color: '#3b82f6',
      onClick: open('ai-remove-person'),
    },
    {
      label: 'Remove Object',
      description: 'AI Cleanup',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'delete',
        'erase',
        'clear',
        'removal',
      ],
      emoji: '🎯',
      color: '#3b82f6',
      onClick: open('ai-remove-object'),
    },
    {
      label: 'Upscale',
      description: 'AI Enlarge',
      tags: [
        'artificial-intelligence',
        'machine-learning',
        'blow-up',
        'super-resolution',
        'hd',
        '4k',
      ],
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('ai-upscale'),
    },
  ],
  casino: [
    {
      label: 'Blackjack',
      description: 'Cards Counter',
      tags: [
        'casino',
        'gambling',
        'card-game',
        'bj',
        '21',
        'black-jack',
        'tally',
      ],
      emoji: '🃏',
      color: '#f59e0b',
      onClick: open('blackjack'),
    },
    {
      label: 'Poker',
      description: 'Odds Calculator',
      tags: [
        'casino',
        'gambling',
        'card-game',
        'texas-holdem',
        'holdem',
        'cards',
        'hand',
        'math',
        'arithmetic',
      ],
      emoji: '🃏',
      color: '#f59e0b',
      onClick: open('poker'),
    },
  ],
  clocks: [
    {
      label: 'Chess Clock',
      description: 'Chess Timer',
      tags: ['world-clock', 'countdown', 'stopwatch', 'alarm'],
      emoji: '♟️',
      color: '#8b5cf6',
      onClick: open('chess-clock'),
    },
    {
      label: 'Countdown',
      description: 'Timer',
      tags: ['clock', 'world-clock', 'stopwatch', 'alarm'],
      emoji: '⏳',
      color: '#06b6d4',
      onClick: open('countdown'),
    },
    {
      label: 'Cron',
      description: 'Expression Builder',
      tags: ['clock', 'time', 'world-clock'],
      emoji: '🕒',
      color: '#8b5cf6',
      onClick: open('cron'),
    },
    {
      label: 'Pomodoro',
      description: 'Timer',
      tags: ['clock', 'world-clock', 'countdown', 'stopwatch', 'alarm'],
      emoji: '🍅',
      color: '#ef4444',
      onClick: open('pomodoro'),
    },
    {
      label: 'Watchface',
      description: 'Garmin',
      tags: [
        'clock',
        'time',
        'world-clock',
        'smartwatch',
        'watch-face',
        'clock-face',
      ],
      emoji: '⌚',
      color: '#ef4444',
      onClick: open('watchface'),
    },
  ],
  converter: [
    {
      label: 'Calculator',
      description: 'Math',
      tags: ['converter', 'unit-converter', 'arithmetic'],
      emoji: '➗',
      color: '#8b5cf6',
      onClick: open('calculator'),
    },
    {
      label: 'Angle',
      description: 'Converter',
      tags: ['unit-converter', 'transform', 'change'],
      emoji: '📐',
      color: '#8b5cf6',
      onClick: open('angle'),
    },
    {
      label: 'Base',
      description: 'Converter',
      tags: ['unit-converter', 'transform', 'change'],
      emoji: '💻',
      color: '#8b5cf6',
      onClick: open('base'),
    },
    {
      label: 'Data',
      description: 'Converter',
      tags: ['unit-converter', 'transform', 'change'],
      emoji: '💾',
      color: '#8b5cf6',
      onClick: open('data'),
    },
    {
      label: 'Roman',
      description: 'Converter',
      tags: ['unit-converter', 'transform', 'change'],
      emoji: '🏛️',
      color: '#8b5cf6',
      onClick: open('roman'),
    },
    {
      label: 'Length',
      description: 'Converter',
      tags: ['unit-converter', 'transform', 'change'],
      emoji: '📏',
      color: '#8b5cf6',
      onClick: open('length'),
    },
    {
      label: 'Weight',
      description: 'Converter',
      tags: ['unit-converter', 'transform', 'change'],
      emoji: '⚖️',
      color: '#8b5cf6',
      onClick: open('weight'),
    },
    {
      label: 'Temperature',
      description: 'Converter',
      tags: ['unit-converter', 'transform', 'change'],
      emoji: '🌡️',
      color: '#8b5cf6',
      onClick: open('temperature'),
    },
    {
      label: 'Time',
      description: 'Converter',
      tags: [
        'unit-converter',
        'timezone',
        'world-clock',
        'time-converter',
        'clock',
        'transform',
        'change',
      ],
      emoji: '⏰',
      color: '#8b5cf6',
      onClick: open('time'),
    },
  ],
  'data-csv': [
    {
      label: 'CSV to Excel',
      description: 'Data',
      tags: [
        'spreadsheet',
        'comma-separated',
        'xlsx',
        'xls',
        'microsoft-excel',
      ],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('csv-to-excel'),
    },
    {
      label: 'CSV to JSON',
      description: 'Data',
      tags: ['spreadsheet', 'comma-separated', 'javascript-object-notation'],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('csv-to-json'),
    },
    {
      label: 'CSV to XML',
      description: 'Data',
      tags: ['spreadsheet', 'comma-separated', 'markup'],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('csv-to-xml'),
    },
    {
      label: 'Excel to CSV',
      description: 'Data',
      tags: [
        'spreadsheet',
        'xlsx',
        'xls',
        'microsoft-excel',
        'comma-separated',
      ],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('excel-to-csv'),
    },
    {
      label: 'Split CSV',
      description: 'Data',
      tags: ['spreadsheet', 'comma-separated'],
      emoji: '✂️',
      color: '#10b981',
      onClick: open('split-csv'),
    },
  ],
  'data-excel': [
    {
      label: 'Excel to PDF',
      description: 'Data',
      tags: [
        'spreadsheet',
        'xlsx',
        'xls',
        'microsoft-excel',
        'document',
        'adobe',
        'acrobat',
      ],
      emoji: '📄',
      color: '#10b981',
      onClick: open('excel-to-pdf'),
    },
    {
      label: 'Excel to XML',
      description: 'Data',
      tags: ['spreadsheet', 'xlsx', 'xls', 'microsoft-excel', 'markup'],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('excel-to-xml'),
    },
    {
      label: 'Split Excel',
      description: 'Data',
      tags: ['spreadsheet', 'xlsx', 'xls', 'microsoft-excel'],
      emoji: '✂️',
      color: '#10b981',
      onClick: open('split-excel'),
    },
  ],
  'data-utility': [
    {
      label: 'Create ZIP',
      description: 'Data',
      tags: ['utility', 'tool'],
      emoji: '🗜️',
      color: '#10b981',
      onClick: open('create-zip'),
    },
    {
      label: 'Epoch Convert',
      description: 'Data',
      tags: ['utility', 'tool'],
      emoji: '🕐',
      color: '#10b981',
      onClick: open('epoch-convert'),
    },
    {
      label: 'Word Counter',
      description: 'Data',
      tags: ['utility', 'tool', 'docx', 'doc', 'microsoft-word', 'tally'],
      emoji: '📝',
      color: '#10b981',
      onClick: open('word-counter'),
    },
  ],
  'data-xml-json': [
    {
      label: 'JSON to CSV',
      description: 'Data',
      tags: [
        'xml',
        'converter',
        'javascript-object-notation',
        'comma-separated',
        'spreadsheet',
      ],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('json-to-csv'),
    },
    {
      label: 'JSON to XML',
      description: 'Data',
      tags: ['converter', 'javascript-object-notation', 'markup'],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('json-to-xml'),
    },
    {
      label: 'XML to CSV',
      description: 'Data',
      tags: ['json', 'converter', 'markup', 'comma-separated', 'spreadsheet'],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-csv'),
    },
    {
      label: 'XML to Excel',
      description: 'Data',
      tags: [
        'json',
        'converter',
        'markup',
        'xlsx',
        'xls',
        'spreadsheet',
        'microsoft-excel',
      ],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-excel'),
    },
    {
      label: 'XML to JSON',
      description: 'Data',
      tags: ['converter', 'markup', 'javascript-object-notation'],
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-json'),
    },
  ],
  developer: [
    {
      label: 'Figlet',
      description: 'Text art',
      tags: ['developer', 'programming', 'code', 'dev-tools'],
      emoji: '📝',
      color: '#8b5cf6',
      onClick: open('figlet'),
    },
    {
      label: 'IP',
      description: 'Inspector',
      tags: ['developer', 'programming', 'code', 'dev-tools'],
      emoji: '🌐',
      color: '#f59e0b',
      onClick: open('ip'),
    },
    {
      label: 'Proxy',
      description: 'CORS Proxy',
      tags: ['developer', 'programming', 'code', 'dev-tools'],
      emoji: '🔗',
      color: '#3b82f6',
      onClick: open('proxy'),
    },
    {
      label: 'Shopify Detect',
      description: 'Detect Shopify',
      tags: ['developer', 'programming', 'code', 'dev-tools'],
      emoji: '🔍',
      color: '#06b6d4',
      onClick: open('shopify-detect'),
    },
    {
      label: 'SVG',
      description: 'Editor',
      tags: [
        'developer',
        'programming',
        'code',
        'dev-tools',
        'modify',
        'change',
      ],
      emoji: '🎨',
      color: '#8b5cf6',
      onClick: open('svg'),
    },
    {
      label: 'UUID',
      description: 'Generator',
      tags: [
        'developer',
        'programming',
        'code',
        'dev-tools',
        'guid',
        'unique-id',
        'identifier',
        'create',
        'maker',
        'builder',
      ],
      emoji: '🔑',
      color: '#a855f7',
      onClick: open('uuid'),
    },
    {
      label: 'Diff',
      description: 'Text Comparison',
      tags: ['developer', 'programming', 'code', 'dev-tools'],
      emoji: '📝',
      color: '#3b82f6',
      onClick: open('text-diff'),
    },
    {
      label: 'Case',
      description: 'Converter',
      tags: [
        'developer',
        'programming',
        'code',
        'dev-tools',
        'transform',
        'change',
      ],
      emoji: '🔤',
      color: '#3b82f6',
      onClick: open('text-case'),
    },
    {
      label: 'URL Tracer',
      description: 'Redirect Tracker',
      tags: ['developer', 'programming', 'code', 'dev-tools'],
      emoji: '🔗',
      color: '#3b82f6',
      onClick: open('text-url-tracer'),
    },
    {
      label: 'Sheets',
      description: 'SQLite Browser',
      tags: [
        'developer',
        'programming',
        'code',
        'dev-tools',
        'spreadsheet',
        'excel',
        'google-sheets',
      ],
      emoji: '🗄️',
      color: '#3b82f6',
      onClick: open('sheets'),
    },
  ],
  editors: [
    {
      label: 'JSON Schema',
      description: 'Validator',
      tags: ['editor', 'edit', 'text', 'javascript-object-notation', 'data'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('json-schema'),
    },
    {
      label: 'Manifest',
      description: 'JSON Editor',
      tags: ['text', 'javascript-object-notation', 'data', 'modify', 'change'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('manifest'),
    },
    {
      label: 'Markdown',
      description: 'Markdown Editor',
      tags: ['text', 'md', 'readme', 'markup', 'modify', 'change'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('markdown'),
    },
    {
      label: 'Resume',
      description: 'Resume Builder',
      tags: ['editor', 'edit', 'text'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('resume'),
    },
    {
      label: 'Regex',
      description: 'Pattern Generator',
      tags: [
        'editor',
        'edit',
        'text',
        'regular-expression',
        'regexp',
        'create',
        'maker',
        'builder',
      ],
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('regex'),
    },
    {
      label: 'Redact',
      description: 'PDF Redactor',
      tags: ['editor', 'edit', 'text', 'document', 'adobe', 'acrobat'],
      emoji: '🖋️',
      color: '#3b82f6',
      onClick: open('redact'),
    },
    {
      label: 'Slides',
      description: 'Pitch Deck',
      tags: [
        'editor',
        'edit',
        'text',
        'presentation',
        'powerpoint',
        'google-slides',
      ],
      emoji: '📽️',
      color: '#3b82f6',
      onClick: open('slides'),
    },
  ],
  education: [
    {
      label: 'English',
      description: 'Dictionary',
      tags: ['education', 'learning', 'study', 'academic'],
      emoji: '📚',
      color: '#3b82f6',
      onClick: open('english'),
    },
    {
      label: 'Flashcards',
      description: 'Words',
      tags: ['education', 'learning', 'study', 'academic'],
      emoji: '📓',
      color: '#fefefe',
      onClick: open('flashcards'),
    },
    {
      label: 'Sign Language',
      description: 'Detection',
      tags: ['education', 'learning', 'study', 'academic'],
      emoji: '🤟',
      color: '#3b82f6',
      onClick: open('sign'),
    },
    {
      label: 'Periodic Table',
      description: 'Elements',
      tags: ['education', 'learning', 'study', 'academic'],
      emoji: '📊',
      color: '#f59e0b',
      onClick: open('periodic-table'),
    },
    {
      label: 'Pitch',
      description: 'Training',
      tags: ['education', 'learning', 'study', 'academic'],
      emoji: '🎹',
      color: '#8b5cf6',
      onClick: open('pitch'),
    },
    {
      label: 'DOI',
      description: 'Cite',
      tags: [
        'education',
        'learning',
        'study',
        'academic',
        'digital-object-identifier',
        'citation',
      ],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('doi'),
    },
  ],
  eyes: [
    {
      label: 'LogMAR Chart',
      description: 'LogMAR Chart',
      tags: ['eyes', 'vision', 'eye-test', 'sight'],
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('logmar'),
    },
    {
      label: 'Snellen Chart',
      description: 'Snellen Chart',
      tags: ['eyes', 'vision', 'eye-test', 'sight'],
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('snellen'),
    },
    {
      label: 'Tumbling E Chart',
      description: 'Tumbling E Chart',
      tags: ['eyes', 'vision', 'eye-test', 'sight'],
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('tumbling-e'),
    },
  ],
  financial: [
    {
      label: 'Elo',
      description: 'Calculator',
      tags: ['finance', 'money', 'financial', 'math', 'arithmetic'],
      emoji: '♟️',
      color: '#f59e0b',
      onClick: open('elo'),
    },
    {
      label: 'Inflation',
      description: 'Calculator',
      tags: ['finance', 'money', 'financial', 'math', 'arithmetic'],
      emoji: '💰',
      color: '#f59e0b',
      onClick: open('inflation'),
    },
    {
      label: 'Tax',
      description: 'Vietnam PIT',
      tags: ['finance', 'money', 'financial', 'calculator'],
      emoji: '🇻🇳',
      color: '#ef4444',
      onClick: open('tax'),
    },
    {
      label: 'Split Bill',
      description: 'Calculator',
      tags: ['finance', 'money', 'financial', 'math', 'arithmetic'],
      emoji: '💵',
      color: '#10b981',
      onClick: open('split-bill'),
    },
    {
      label: 'Days Count',
      description: 'Date Difference',
      tags: ['finance', 'money', 'financial', 'calculator'],
      emoji: '📅',
      color: '#3b82f6',
      onClick: open('days-count'),
    },
  ],
  format: [
    {
      label: 'Braille',
      description: 'From Text',
      tags: ['format', 'converter', 'data'],
      emoji: '⠿',
      color: '#8b5cf6',
      onClick: open('braille'),
    },
    {
      label: 'Colors',
      description: 'From HEX',
      tags: ['format', 'converter', 'data'],
      emoji: '🎨',
      color: '#ec4899',
      onClick: open('colors'),
    },
    {
      label: 'Morse Code',
      description: 'From Text',
      tags: ['format', 'converter', 'data'],
      emoji: '🔣',
      color: '#f59e0b',
      onClick: open('morse'),
    },
    {
      label: 'Leet Speak',
      description: 'From Text',
      tags: ['format', 'converter', 'data'],
      emoji: '🔐',
      color: '#10b981',
      onClick: open('leetspeak'),
    },
    {
      label: 'Lorem Ipsum',
      description: 'Dummy text',
      tags: [
        'format',
        'converter',
        'data',
        'placeholder',
        'dummy-text',
        'filler',
      ],
      emoji: '📝',
      color: '#8b5cf6',
      onClick: open('lorem-ipsum'),
    },
    {
      label: 'OpenAPI',
      description: 'to Postman',
      tags: ['format', 'converter', 'data', 'rest', 'swagger', 'specification'],
      emoji: '🔄',
      color: '#ff6c37',
      onClick: open('openapi'),
    },
  ],
  games: [
    {
      label: '2048',
      description: 'Merge tiles',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '🔢',
      color: '#f59e0b',
      onClick: open('game2048'),
    },
    {
      label: 'Palindrome',
      description: 'Palindrome',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '🔁',
      color: '#f59e0b',
      onClick: open('palindrome'),
    },
    {
      label: 'PD',
      description: "Prisoner's Dilemma",
      tags: ['game', 'fun', 'entertainment'],
      emoji: '⚖️',
      color: '#f59e0b',
      onClick: open('pd'),
    },
    {
      label: 'Sudoku',
      description: '4×4 & 9×9',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '🧩',
      color: '#f59e0b',
      onClick: open('sudoku'),
    },
    {
      label: 'Snake',
      description: '12×12 grid',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '🐍',
      color: '#f59e0b',
      onClick: open('snake'),
    },
    {
      label: 'Pokedex',
      description: 'Pokemon',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '📕',
      color: '#f59e0b',
      onClick: open('pokedex'),
    },
    {
      label: 'RPS',
      description: 'Rock Paper Scissors',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '✂️',
      color: '#f59e0b',
      onClick: open('rps'),
    },
    {
      label: 'T3',
      description: 'Tic-Tac-Toe',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '❌',
      color: '#f59e0b',
      onClick: open('t3'),
    },
    {
      label: 'Towers',
      description: 'Towers of Hanoi',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '🗼',
      color: '#f59e0b',
      onClick: open('towers'),
    },
    {
      label: 'Typoglycemia',
      description: 'Scrambled text',
      tags: ['game', 'fun', 'entertainment'],
      emoji: '🔀',
      color: '#f59e0b',
      onClick: open('typoglycemia'),
    },
    {
      label: 'Wordle',
      description: 'Guess the word',
      tags: ['game', 'fun', 'entertainment', 'docx', 'doc', 'microsoft-word'],
      emoji: '🟩',
      color: '#f59e0b',
      onClick: open('wordle'),
    },
  ],
  'image-convert': [
    {
      label: 'HEIC to JPG',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-heic-to-jpg'),
    },
    {
      label: 'WebP to JPG',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-jpg'),
    },
    {
      label: 'WebP to PNG',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-png'),
    },
    {
      label: 'JPG to WebP',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-webp'),
    },
    {
      label: 'JPG to PNG',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-png'),
    },
    {
      label: 'PNG to WebP',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-webp'),
    },
    {
      label: 'PNG to JPG',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-jpg'),
    },
    {
      label: 'PNG to SVG',
      description: 'Convert',
      tags: ['image', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-svg'),
    },
  ],
  'image-convert-plus': [
    {
      label: 'HEIC to PNG',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-heic-to-png'),
    },
    {
      label: 'JPG to AVIF',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-avif'),
    },
    {
      label: 'JPG to GIF',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-gif'),
    },
    {
      label: 'JPG to SVG',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-svg'),
    },
    {
      label: 'JPG to TIFF',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-tiff'),
    },
    {
      label: 'PNG to AVIF',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-avif'),
    },
    {
      label: 'PNG to EPS',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-eps'),
    },
    {
      label: 'PNG to GIF',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-gif'),
    },
    {
      label: 'PNG to TIFF',
      description: 'Convert',
      tags: ['image', 'advanced', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-tiff'),
    },
  ],
  'image-convert-pro': [
    {
      label: 'GIF to JPG',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-gif-to-jpg'),
    },
    {
      label: 'GIF to PNG',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-gif-to-png'),
    },
    {
      label: 'HEIC to AVIF',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-heic-to-avif'),
    },
    {
      label: 'PSD to JPG',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-psd-to-jpg'),
    },
    {
      label: 'PSD to PNG',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-psd-to-png'),
    },
    {
      label: 'SVG to PNG',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-svg-to-png'),
    },
    {
      label: 'TIFF to JPG',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-tiff-to-jpg'),
    },
    {
      label: 'TIFF to PNG',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-tiff-to-png'),
    },
    {
      label: 'WebP to AVIF',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-avif'),
    },
    {
      label: 'WebP to GIF',
      description: 'Convert',
      tags: ['image', 'pro', 'photo'],
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-gif'),
    },
  ],
  'image-create': [
    {
      label: 'Chart Maker',
      description: 'Create Chart',
      tags: ['image', 'photo', 'generator'],
      emoji: '📊',
      color: '#3b82f6',
      onClick: open('chart-maker'),
    },
    {
      label: 'Meme Maker',
      description: 'Create Meme',
      tags: ['image', 'photo', 'generator', 'funny'],
      emoji: '🎭',
      color: '#3b82f6',
      onClick: open('meme-maker'),
    },
    {
      label: 'Collage',
      description: 'Photo Collage',
      tags: ['image', 'create', 'generator'],
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('collage-maker'),
    },
    {
      label: 'Profile',
      description: 'Photo Maker',
      tags: ['image', 'create', 'generator'],
      emoji: '👤',
      color: '#3b82f6',
      onClick: open('image-profile'),
    },
    {
      label: 'Pixel',
      description: 'Art Grid',
      tags: ['image', 'create', 'photo', 'generator'],
      emoji: '▪️',
      color: '#8b5cf6',
      onClick: open('pixel'),
    },
    {
      label: 'InstaSize',
      description: 'Square Fit',
      tags: ['image', 'create', 'photo', 'generator'],
      emoji: '📸',
      color: '#3b82f6',
      onClick: open('instasize'),
    },
    {
      label: 'Social Preview',
      description: 'GitHub',
      tags: ['image', 'create', 'photo', 'generator'],
      emoji: '📸',
      color: '#10b981',
      onClick: open('github-social-preview'),
    },
    {
      label: 'Thumbnails',
      description: 'YouTube',
      tags: [
        'image',
        'create',
        'photo',
        'generator',
        'yt',
        'video',
        'download',
      ],
      emoji: '📸',
      color: '#22d3ee',
      onClick: open('youtube-thumbnails'),
    },
    {
      label: 'House',
      description: 'M.D.',
      tags: ['image', 'create', 'photo', 'generator'],
      emoji: '🏥',
      color: '#ef4444',
      onClick: open('house'),
    },
    {
      label: 'Camera',
      description: 'Composition',
      tags: ['image', 'create', 'photo', 'generator'],
      emoji: '📸',
      color: '#ef4444',
      onClick: open('camera'),
    },
    {
      label: 'Breaking Bad',
      description: 'Element',
      tags: ['image', 'create', 'photo', 'generator'],
      emoji: '🧪',
      color: '#eab308',
      onClick: open('breaking-bad'),
    },
    {
      label: 'Base64',
      description: 'Decode/Encode',
      tags: ['image', 'create', 'photo', 'generator', 'base-64'],
      emoji: '🔐',
      color: '#3b82f6',
      onClick: open('base64'),
    },
  ],
  'image-edit': [
    {
      label: 'Resize',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'scale',
        'resize-image',
        'dimensions',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '📐',
      color: '#3b82f6',
      onClick: open('image-resize'),
    },
    {
      label: 'Crop',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'trim',
        'cut',
        'clip-image',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '✂️',
      color: '#3b82f6',
      onClick: open('image-crop'),
    },
    {
      label: 'Compress',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'zip',
        'archive',
        'minify',
        'reduce-size',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '📦',
      color: '#3b82f6',
      onClick: open('image-compress'),
    },
    {
      label: 'Flip',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('image-flip'),
    },
    {
      label: 'B&W',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '⚫',
      color: '#3b82f6',
      onClick: open('image-bw'),
    },
    {
      label: 'Pixelate',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '🧊',
      color: '#3b82f6',
      onClick: open('image-pixelate'),
    },
    {
      label: 'Sharpen',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '💫',
      color: '#3b82f6',
      onClick: open('image-sharpen'),
    },
    {
      label: 'Border',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('image-border'),
    },
    {
      label: 'Round',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '⭕',
      color: '#3b82f6',
      onClick: open('image-round'),
    },
    {
      label: 'Rotate',
      description: 'Image',
      tags: [
        'edit',
        'photo-editor',
        'flip',
        'orientation',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('image-rotate'),
    },
    {
      label: 'Split',
      description: 'Image Splitter',
      tags: [
        'edit',
        'photo-editor',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
        'divide',
        'separate',
      ],
      emoji: '✂️',
      color: '#3b82f6',
      onClick: open('image-split'),
    },
  ],
  'image-effect': [
    {
      label: 'Blur Background',
      description: 'Image Effect',
      tags: [
        'filter',
        'photo',
        'bg',
        'backdrop',
        'background-removal',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
      ],
      emoji: '🌫️',
      color: '#06b6d4',
      onClick: open('image-blur-background'),
    },
    {
      label: 'Colorize',
      description: 'Photo Filter',
      tags: [
        'image',
        'effect',
        'colour',
        'colorization',
        'black-and-white',
        'bw',
      ],
      emoji: '🎨',
      color: '#3b82f6',
      onClick: open('image-colorize'),
    },
    {
      label: 'Transparent BG',
      description: 'Make Transparent',
      tags: ['image', 'effect', 'filter', 'photo'],
      emoji: '✨',
      color: '#3b82f6',
      onClick: open('image-transparent-bg'),
    },
    {
      label: 'Photo Filters',
      description: 'Apply Filters',
      tags: ['image', 'effect'],
      emoji: '📸',
      color: '#3b82f6',
      onClick: open('image-photo-filters'),
    },
    {
      label: 'Adjust',
      description: 'Brightness/Contrast',
      tags: ['image', 'effect', 'filter', 'photo'],
      emoji: '⚙️',
      color: '#3b82f6',
      onClick: open('image-adjust'),
    },
    {
      label: 'Vignette',
      description: 'Vignette Effect',
      tags: ['image', 'filter', 'photo'],
      emoji: '🌑',
      color: '#3b82f6',
      onClick: open('image-vignette'),
    },
    {
      label: 'Shadow',
      description: 'Add Shadow',
      tags: ['image', 'effect', 'filter', 'photo'],
      emoji: '👤',
      color: '#3b82f6',
      onClick: open('image-shadow'),
    },
    {
      label: 'Watermark',
      description: 'Add Watermark',
      tags: ['image', 'effect', 'filter', 'photo', 'watermark-removal', 'logo'],
      emoji: '💧',
      color: '#3b82f6',
      onClick: open('image-watermark'),
    },
    {
      label: 'Text',
      description: 'Add Text',
      tags: ['image', 'effect', 'filter', 'photo'],
      emoji: '✏️',
      color: '#3b82f6',
      onClick: open('image-text'),
    },
    {
      label: 'Side by Side',
      description: 'Combine',
      tags: ['image', 'effect', 'filter', 'photo'],
      emoji: '🔗',
      color: '#06b6d4',
      onClick: open('image-combiner-side-by-side'),
    },
    {
      label: 'Stacked',
      description: 'Combine',
      tags: ['image', 'effect', 'filter', 'photo'],
      emoji: '🔗',
      color: '#06b6d4',
      onClick: open('image-combiner-stacked'),
    },
  ],
  'image-scan': [
    {
      label: 'Barcode',
      description: 'Generator',
      tags: [
        'image',
        'scan',
        'ocr',
        'photo',
        'code128',
        'ean',
        'upc',
        'create',
        'maker',
        'builder',
      ],
      emoji: '▌',
      color: '#22d3ee',
      onClick: open('barcode'),
    },
    {
      label: 'QR Code',
      description: 'Generator',
      tags: [
        'image',
        'scan',
        'ocr',
        'photo',
        'qrcode',
        'barcode',
        'create',
        'maker',
        'builder',
      ],
      emoji: '▦',
      color: '#22d3ee',
      onClick: open('qr'),
    },
    {
      label: 'QR Read',
      description: 'QR Scanner',
      tags: ['image', 'ocr', 'photo', 'qrcode', 'barcode', 'code'],
      emoji: '📱',
      color: '#3b82f6',
      onClick: open('qr-read'),
    },
    {
      label: 'Barcode Read',
      description: 'Barcode Scanner',
      tags: ['image', 'ocr', 'photo', 'code128', 'ean', 'upc'],
      emoji: '📋',
      color: '#3b82f6',
      onClick: open('barcode-read'),
    },
    {
      label: 'OCR',
      description: 'Text Extraction',
      tags: ['image', 'scan', 'photo'],
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('image-ocr'),
    },
    {
      label: 'Dominant Color',
      description: 'Extract Color',
      tags: [
        'image',
        'scan',
        'ocr',
        'photo',
        'colour',
        'hex',
        'rgb',
        'hsl',
        'picker',
      ],
      emoji: '🎯',
      color: '#3b82f6',
      onClick: open('image-dominant-color'),
    },
    {
      label: 'Invoice Parser',
      description: 'OCR',
      tags: ['image', 'scan', 'photo'],
      emoji: '📄',
      color: '#ef4444',
      onClick: open('invoice-parser'),
    },
    {
      label: 'Image Translate',
      description: 'OCR + Translate',
      tags: [
        'scan',
        'photo',
        'picture',
        'img',
        'png',
        'jpg',
        'jpeg',
        'gif',
        'translation',
        'language',
        'i18n',
      ],
      emoji: '🌐',
      color: '#10b981',
      onClick: open('image-translate'),
    },
  ],
  memory: [
    {
      label: 'PI',
      description: 'Memorization',
      tags: ['memory', 'brain', 'cognitive', 'game'],
      emoji: 'π',
      color: '#f59e0b',
      onClick: open('pi'),
    },
    {
      label: 'Quizify',
      description: 'Quiz',
      tags: ['memory', 'brain', 'cognitive', 'game'],
      emoji: '❓',
      color: '#f59e0b',
      onClick: open('quizify'),
    },
    {
      label: 'Recall',
      description: 'Memorization',
      tags: ['memory', 'brain', 'cognitive', 'game'],
      emoji: '🔣',
      color: '#f59e0b',
      onClick: open('recall'),
    },
  ],
  'pdf-convert': [
    {
      label: 'PDF to Excel',
      description: 'PDF',
      tags: [
        'convert',
        'document',
        'adobe',
        'acrobat',
        'xlsx',
        'xls',
        'spreadsheet',
        'microsoft-excel',
      ],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-excel'),
    },
    {
      label: 'PDF to EPUB',
      description: 'PDF',
      tags: ['convert', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-epub'),
    },
    {
      label: 'PDF to Images',
      description: 'PDF',
      tags: ['convert', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-images'),
    },
    {
      label: 'PDF to PPT',
      description: 'PDF',
      tags: ['convert', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-ppt'),
    },
    {
      label: 'PDF to Word',
      description: 'PDF',
      tags: [
        'convert',
        'document',
        'adobe',
        'acrobat',
        'docx',
        'doc',
        'microsoft-word',
      ],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-word'),
    },
  ],
  'pdf-create': [
    {
      label: 'EPUB to PDF',
      description: 'PDF',
      tags: ['create', 'document', 'word', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('epub-to-pdf'),
    },
    {
      label: 'Images to PDF',
      description: 'PDF',
      tags: ['create', 'document', 'word', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('images-to-pdf'),
    },
    {
      label: 'MD to PDF',
      description: 'PDF',
      tags: ['create', 'document', 'word', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('create-md-to-pdf'),
    },
    {
      label: 'PPT to PDF',
      description: 'PDF',
      tags: ['create', 'document', 'word', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('ppt-to-pdf'),
    },
    {
      label: 'Text to PDF',
      description: 'PDF',
      tags: ['create', 'document', 'word', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('create-text-to-pdf'),
    },
    {
      label: 'URL to PDF',
      description: 'PDF',
      tags: ['create', 'document', 'word', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('create-url-to-pdf'),
    },
    {
      label: 'URL to PDF',
      description: 'PDF',
      tags: ['create', 'document', 'word', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('url-to-pdf'),
    },
    {
      label: 'Word to PDF',
      description: 'PDF',
      tags: [
        'create',
        'document',
        'docx',
        'doc',
        'microsoft-word',
        'adobe',
        'acrobat',
      ],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('word-to-pdf'),
    },
  ],
  'pdf-ebook': [
    {
      label: 'AZW3 to EPUB',
      description: 'Ebook',
      tags: ['pdf', 'document'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('azw3-to-epub'),
    },
    {
      label: 'AZW3 to MOBI',
      description: 'Ebook',
      tags: ['pdf', 'epub', 'document'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('azw3-to-mobi'),
    },
    {
      label: 'EPUB to AZW3',
      description: 'Ebook',
      tags: ['pdf', 'document'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('epub-to-azw3'),
    },
    {
      label: 'EPUB to MOBI',
      description: 'Ebook',
      tags: ['pdf', 'document'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('epub-to-mobi'),
    },
    {
      label: 'MOBI to AZW3',
      description: 'Ebook',
      tags: ['pdf', 'epub', 'document'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('mobi-to-azw3'),
    },
    {
      label: 'MOBI to EPUB',
      description: 'Ebook',
      tags: ['pdf', 'document'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('mobi-to-epub'),
    },
  ],
  'pdf-edit': [
    {
      label: 'Annotate',
      description: 'PDF',
      tags: ['edit', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-annotate'),
    },
    {
      label: 'Compress',
      description: 'PDF',
      tags: [
        'edit',
        'document',
        'zip',
        'archive',
        'minify',
        'reduce-size',
        'adobe',
        'acrobat',
      ],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-compress'),
    },
    {
      label: 'Crop Pages',
      description: 'PDF',
      tags: [
        'edit',
        'document',
        'trim',
        'cut',
        'clip-image',
        'adobe',
        'acrobat',
      ],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-crop'),
    },
    {
      label: 'Delete Pages',
      description: 'PDF',
      tags: ['edit', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-delete-pages'),
    },
    {
      label: 'Merge',
      description: 'PDF',
      tags: ['edit', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-merge'),
    },
    {
      label: 'Page Numbers',
      description: 'PDF',
      tags: ['edit', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-page-numbers'),
    },
    {
      label: 'Rearrange',
      description: 'PDF',
      tags: ['edit', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-rearrange'),
    },
    {
      label: 'Redact',
      description: 'PDF',
      tags: ['edit', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-redact'),
    },
    {
      label: 'Rotate',
      description: 'PDF',
      tags: ['edit', 'document', 'flip', 'orientation', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-rotate'),
    },
    {
      label: 'Split',
      description: 'PDF',
      tags: ['edit', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-split'),
    },
    {
      label: 'Watermark',
      description: 'PDF',
      tags: [
        'edit',
        'document',
        'watermark-removal',
        'logo',
        'adobe',
        'acrobat',
      ],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-watermark'),
    },
  ],
  'pdf-extract': [
    {
      label: 'Extract Images',
      description: 'PDF',
      tags: ['document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-extract-images'),
    },
    {
      label: 'Extract Text',
      description: 'PDF',
      tags: ['document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-extract-text'),
    },
    {
      label: 'Info',
      description: 'PDF',
      tags: ['extract', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-info'),
    },
    {
      label: 'Metadata',
      description: 'PDF',
      tags: ['extract', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-metadata'),
    },
    {
      label: 'OCR',
      description: 'PDF',
      tags: ['extract', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-ocr'),
    },
    {
      label: 'Repair',
      description: 'PDF',
      tags: ['extract', 'document', 'adobe', 'acrobat'],
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-repair'),
    },
  ],
  'pdf-misc': [
    {
      label: 'Security',
      description: 'Encrypt/Decrypt',
      tags: ['pdf', 'document', 'utility'],
      emoji: '🔒',
      color: '#ef4444',
      onClick: open('pdf-security'),
    },
    {
      label: 'Translate',
      description: 'PDF',
      tags: [
        'document',
        'utility',
        'translation',
        'language',
        'i18n',
        'adobe',
        'acrobat',
      ],
      emoji: '🌐',
      color: '#ef4444',
      onClick: open('pdf-translate'),
    },
    {
      label: 'eSign',
      description: 'Sign PDF',
      tags: ['document', 'utility', 'adobe', 'acrobat'],
      emoji: '✍️',
      color: '#ef4444',
      onClick: open('pdf-esign'),
    },
  ],
  utilities: [
    {
      label: 'Chat',
      description: 'AI Assistant',
      tags: ['utility', 'tool', 'productivity'],
      emoji: '💬',
      color: '#3b82f6',
      onClick: open('chat'),
    },
    {
      label: 'Clipboard',
      description: 'Clipboard',
      tags: [
        'utility',
        'tool',
        'productivity',
        'copy',
        'paste',
        'clipboard-manager',
      ],
      emoji: '📋',
      color: '#3b82f6',
      onClick: open('clipboard'),
    },
    {
      label: 'Emojis',
      description: 'Explorer',
      tags: ['utility', 'tool', 'productivity'],
      emoji: '😀',
      color: '#f59e0b',
      onClick: open('emojis'),
    },
    {
      label: 'Contrast',
      description: 'Checker',
      tags: ['utility', 'tool', 'productivity'],
      emoji: '👁️',
      color: '#3b82f6',
      onClick: open('contrast-checker'),
    },
    {
      label: 'Gradient',
      description: 'Generator',
      tags: ['utility', 'tool', 'productivity', 'create', 'maker', 'builder'],
      emoji: '🎨',
      color: '#8b5cf6',
      onClick: open('gradient-generator'),
    },
    {
      label: 'Kaprekar',
      description: 'Routine',
      tags: ['utility', 'tool', 'productivity'],
      emoji: '🔢',
      color: '#f59e0b',
      onClick: open('kaprekar'),
    },
    {
      label: 'No Sleep',
      description: 'Timer',
      tags: [
        'utility',
        'tool',
        'productivity',
        'countdown',
        'stopwatch',
        'alarm',
      ],
      emoji: '😴',
      color: '#3b82f6',
      onClick: open('no-sleep'),
    },
    {
      label: 'Password',
      description: 'Generator',
      tags: [
        'utility',
        'tool',
        'productivity',
        'secret',
        'strong',
        'create',
        'maker',
        'builder',
      ],
      emoji: '🔐',
      color: '#3b82f6',
      onClick: open('text-password'),
    },
    {
      label: 'Word Count',
      description: 'Counter',
      tags: [
        'utility',
        'tool',
        'productivity',
        'docx',
        'doc',
        'microsoft-word',
        'tally',
      ],
      emoji: '📊',
      color: '#3b82f6',
      onClick: open('text-word-count'),
    },
    {
      label: 'Screen Recorder',
      description: 'Record & Download',
      tags: ['utility', 'tool', 'productivity'],
      emoji: '🎥',
      color: '#3b82f6',
      onClick: open('screen-recorder'),
    },
  ],
  'video-audio': [
    {
      label: 'Subtitles',
      description: 'Video',
      tags: ['audio', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎤',
      color: '#ef4444',
      onClick: open('generate-subtitle'),
    },
    {
      label: 'Transcribe',
      description: 'Video',
      tags: ['audio', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎤',
      color: '#ef4444',
      onClick: open('audio-transcribe'),
    },
  ],
  'video-convert': [
    {
      label: 'AVI to GIF',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-avi-to-gif'),
    },
    {
      label: 'AVI to MP3',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-avi-to-mp3'),
    },
    {
      label: 'AVI to MP4',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-avi-to-mp4'),
    },
    {
      label: 'FLV to MP4',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-flv-to-mp4'),
    },
    {
      label: 'GIF to MOV',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-gif-to-mov'),
    },
    {
      label: 'GIF to MP4',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-gif-to-mp4'),
    },
    {
      label: 'GIF to WebM',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-gif-to-webm'),
    },
    {
      label: 'MKV to MP4',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mkv-to-mp4'),
    },
    {
      label: 'MOV to MP4',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-mp4'),
    },
    {
      label: 'MP4 to AVI',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-avi'),
    },
    {
      label: 'MP4 to MOV',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-mov'),
    },
    {
      label: 'WMV to MP4',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-wmv-to-mp4'),
    },
  ],
  'video-convert-audio': [
    {
      label: 'AAC to MP3',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-aac-to-mp3'),
    },
    {
      label: 'AAC to MP4',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-aac-to-mp4'),
    },
    {
      label: 'AAC to WAV',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-aac-to-wav'),
    },
    {
      label: 'M4A to MP3',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-m4a-to-mp3'),
    },
    {
      label: 'M4A to MP4',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-m4a-to-mp4'),
    },
    {
      label: 'M4A to WAV',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-m4a-to-wav'),
    },
    {
      label: 'MOV to MP3',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-mp3'),
    },
    {
      label: 'MOV to WAV',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-wav'),
    },
    {
      label: 'MP4 to MP3',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-mp3'),
    },
    {
      label: 'MP4 to WAV',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-wav'),
    },
    {
      label: 'OGG to MP3',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-ogg-to-mp3'),
    },
    {
      label: 'OGG to WAV',
      description: 'Video',
      tags: ['audio', 'convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-ogg-to-wav'),
    },
  ],
  'video-convert-misc': [
    {
      label: 'Convert to WebM',
      description: 'Video',
      tags: ['media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-convert-to-webm'),
    },
    {
      label: 'MKV to GIF',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mkv-to-gif'),
    },
    {
      label: 'MKV to MP3',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mkv-to-mp3'),
    },
    {
      label: 'MOV to AVI',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-avi'),
    },
    {
      label: 'MOV to GIF',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-gif'),
    },
    {
      label: 'MP4 to OGG',
      description: 'Video',
      tags: ['convert', 'media', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-ogg'),
    },
    {
      label: 'Video to GIF',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-to-gif'),
    },
    {
      label: 'Video to WebP',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-to-webp'),
    },
    {
      label: 'WebM to MP3',
      description: 'Video',
      tags: ['convert', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-webm-to-mp3'),
    },
  ],
  'video-download': [
    {
      label: 'Facebook',
      description: 'Video',
      tags: [
        'download',
        'media',
        'fb',
        'social',
        'meta',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-facebook'),
    },
    {
      label: 'Instagram',
      description: 'Video',
      tags: [
        'download',
        'media',
        'ig',
        'social',
        'photo',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-instagram'),
    },
    {
      label: 'TikTok',
      description: 'Video',
      tags: [
        'download',
        'media',
        'social',
        'short-video',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-tiktok'),
    },
    {
      label: 'Twitter/X',
      description: 'Video',
      tags: [
        'download',
        'media',
        'social',
        'tweet',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-twitter'),
    },
    {
      label: 'YouTube to Text',
      description: 'Video',
      tags: ['download', 'media', 'yt', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-youtube-text'),
    },
    {
      label: 'YouTube Transcript',
      description: 'Video',
      tags: ['download', 'media', 'yt', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-youtube-transcript'),
    },
  ],
  'video-edit': [
    {
      label: 'Compress',
      description: 'Video',
      tags: [
        'edit',
        'media',
        'zip',
        'archive',
        'minify',
        'reduce-size',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-compress'),
    },
    {
      label: 'Crop',
      description: 'Video',
      tags: [
        'edit',
        'media',
        'trim',
        'cut',
        'clip-image',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-crop'),
    },
    {
      label: 'Extract Audio',
      description: 'Video',
      tags: [
        'edit',
        'media',
        'sound',
        'music',
        'mp3',
        'wav',
        'ogg',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-extract-audio'),
    },
    {
      label: 'Extract Frames',
      description: 'Video',
      tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-extract-frames'),
    },
    {
      label: 'Merge',
      description: 'Video',
      tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-merge'),
    },
    {
      label: 'Mute',
      description: 'Video',
      tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-mute'),
    },
    {
      label: 'Resize',
      description: 'Video',
      tags: [
        'edit',
        'media',
        'scale',
        'resize-image',
        'dimensions',
        'mp4',
        'movie',
        'clip',
        'footage',
      ],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-resize'),
    },
    {
      label: 'Speed',
      description: 'Video',
      tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-speed'),
    },
    {
      label: 'Stabilize',
      description: 'Video',
      tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-stabilize'),
    },
    {
      label: 'Trim',
      description: 'Video',
      tags: ['edit', 'media', 'mp4', 'movie', 'clip', 'footage'],
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-trim'),
    },
  ],
  visualization: [
    {
      label: 'Calendar Tracker',
      description: 'Activities',
      tags: [
        'chart',
        'graph',
        'visualization',
        'data',
        'date',
        'event',
        'schedule',
      ],
      emoji: '📅',
      color: '#10b981',
      onClick: open('calendar-tracker'),
    },
    {
      label: 'Legislation',
      description: 'Visualization',
      tags: ['chart', 'graph', 'data'],
      emoji: '🏛️',
      color: '#ef4444',
      onClick: open('legislation'),
    },
    {
      label: 'Resume',
      description: 'Timeline',
      tags: ['chart', 'graph', 'visualization', 'data'],
      emoji: '⏳',
      color: '#ef4444',
      onClick: open('resume-timeline'),
    },
    {
      label: 'Graph',
      description: 'Force Layout',
      tags: ['chart', 'visualization', 'data'],
      emoji: '🕸️',
      color: '#6c5ce7',
      onClick: open('graph'),
    },
  ],
  'write-article': [
    {
      label: 'Article',
      description: 'Write',
      tags: ['content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-article'),
    },
    {
      label: 'Article Rewriter',
      description: 'Write',
      tags: ['content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-article-rewriter'),
    },
    {
      label: 'Blog Ideas',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-blog-ideas'),
    },
    {
      label: 'Blog Outline',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-blog-outline'),
    },
    {
      label: 'Blog Post',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-blog-post'),
    },
    {
      label: 'Essay',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-essay'),
    },
    {
      label: 'Listicle',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-listicle'),
    },
    {
      label: 'Paragraph',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-paragraph'),
    },
    {
      label: 'Story',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-story'),
    },
    {
      label: 'Story Ideas',
      description: 'Write',
      tags: ['article', 'content', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-story-ideas'),
    },
    {
      label: 'YouTube Script',
      description: 'Write',
      tags: ['article', 'content', 'writing', 'yt', 'video', 'download'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-youtube-script'),
    },
  ],
  'write-business': [
    {
      label: 'Bill of Sale',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-bill-of-sale'),
    },
    {
      label: 'Business Name',
      description: 'Write',
      tags: ['document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-business-name'),
    },
    {
      label: 'Business Plan',
      description: 'Write',
      tags: ['document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-business-plan'),
    },
    {
      label: 'Slogan',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-business-slogan'),
    },
    {
      label: 'Cold Email',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-cold-email'),
    },
    {
      label: 'Landing Page',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-landing-page'),
    },
    {
      label: 'NDA',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-nda'),
    },
    {
      label: 'Podcast Script',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-podcast-script'),
    },
    {
      label: 'Press Release',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-press-release'),
    },
    {
      label: 'Privacy Policy',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-privacy-policy'),
    },
    {
      label: 'Purchase Agreement',
      description: 'Write',
      tags: ['business', 'document', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-purchase-agreement'),
    },
  ],
  'write-content': [
    {
      label: 'Content Brief',
      description: 'Write',
      tags: ['writing', 'copy'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-content-brief'),
    },
    {
      label: 'Content Planner',
      description: 'Write',
      tags: ['writing', 'copy'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-content-planner'),
    },
    {
      label: 'FAQ',
      description: 'Write',
      tags: ['content', 'writing', 'copy'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-faq'),
    },
    {
      label: 'Poll',
      description: 'Write',
      tags: ['content', 'writing', 'copy'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-poll'),
    },
    {
      label: 'Trivia',
      description: 'Write',
      tags: ['content', 'writing', 'copy'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-trivia'),
    },
  ],
  'write-edit': [
    {
      label: 'Complete',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-complete'),
    },
    {
      label: 'Grammar Check',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-grammar'),
    },
    {
      label: 'Humanizer',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-humanizer'),
    },
    {
      label: 'Improve Text',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-improve-text'),
    },
    {
      label: 'Paraphrase',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-paraphrase'),
    },
    {
      label: 'Rewrite',
      description: 'Write',
      tags: ['edit', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-rewrite'),
    },
    {
      label: 'Shorten Text',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-shorten'),
    },
    {
      label: 'Summarize',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-summarize'),
    },
    {
      label: 'Tone Changer',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-tone'),
    },
    {
      label: 'Translate',
      description: 'Write',
      tags: ['edit', 'rewrite', 'writing', 'translation', 'language', 'i18n'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-translate'),
    },
  ],
  'write-misc': [
    {
      label: 'AI Detector',
      description: 'Write',
      tags: ['writing', 'text'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-ai-detector'),
    },
    {
      label: 'Explain',
      description: 'Write',
      tags: ['writing', 'text'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-explain'),
    },
    {
      label: 'Summarize Podcast',
      description: 'Write',
      tags: ['writing', 'text'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-summarize-podcast'),
    },
    {
      label: 'Summarize YouTube',
      description: 'Write',
      tags: ['writing', 'text', 'yt', 'video', 'download'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-summarize-youtube'),
    },
    {
      label: 'Title Generator',
      description: 'Write',
      tags: ['writing', 'text', 'create', 'maker', 'builder'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-title'),
    },
  ],
  'write-real-estate': [
    {
      label: 'Agent Bio',
      description: 'Write',
      tags: ['real-estate', 'property', 'listing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-real-estate-bio'),
    },
    {
      label: 'Real Estate Desc',
      description: 'Write',
      tags: ['real-estate', 'property', 'listing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-real-estate-description'),
    },
    {
      label: 'Real Estate Listing',
      description: 'Write',
      tags: ['real-estate', 'property'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-real-estate-listing'),
    },
  ],
  'write-social': [
    {
      label: 'Caption',
      description: 'Write',
      tags: ['social-media', 'post', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-caption'),
    },
    {
      label: 'Headline',
      description: 'Write',
      tags: ['social-media', 'post', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-headline'),
    },
    {
      label: 'LinkedIn Post',
      description: 'Write',
      tags: ['social-media', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-linkedin-post'),
    },
    {
      label: 'Meta Description',
      description: 'Write',
      tags: ['social-media', 'post', 'writing'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-meta-description'),
    },
    {
      label: 'TikTok Script',
      description: 'Write',
      tags: ['social-media', 'post', 'writing', 'social', 'short-video'],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-tiktok-script'),
    },
    {
      label: 'Twitter Generator',
      description: 'Write',
      tags: [
        'social-media',
        'post',
        'writing',
        'social',
        'tweet',
        'create',
        'maker',
        'builder',
      ],
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-twitter-generator'),
    },
  ],
});
