import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';

import { ModalId } from './types';

export const makeTools = (
  open: (id: ModalId) => () => void
): Record<string, Tool[]> => ({
  tools: [
    {
      label: 'Chat',
      description: 'AI Assistant',
      emoji: '💬',
      color: '#3b82f6',
      onClick: open('chat'),
    },
    {
      label: 'Clipboard',
      description: 'Clipboard',
      emoji: '📋',
      color: '#3b82f6',
      onClick: open('clipboard'),
    },
    {
      label: 'Emojis',
      description: 'Explorer',
      emoji: '😀',
      color: '#f59e0b',
      onClick: open('emojis'),
    },
    {
      label: 'Contrast',
      description: 'Checker',
      emoji: '👁️',
      color: '#3b82f6',
      onClick: open('contrast-checker'),
    },
    {
      label: 'Figlet',
      description: 'Text art',
      emoji: '📝',
      color: '#8b5cf6',
      onClick: open('figlet'),
    },
    {
      label: 'Gradient',
      description: 'Generator',
      emoji: '🎨',
      color: '#8b5cf6',
      onClick: open('gradient-generator'),
    },
    {
      label: 'IP',
      description: 'Inspector',
      emoji: '🌐',
      color: '#f59e0b',
      onClick: open('ip'),
    },
    {
      label: 'Kaprekar',
      description: 'Routine',
      emoji: '🔢',
      color: '#f59e0b',
      onClick: open('kaprekar'),
    },
    {
      label: 'No Sleep',
      description: 'Timer',
      emoji: '😴',
      color: '#3b82f6',
      onClick: open('no-sleep'),
    },
    {
      label: 'Proxy',
      description: 'CORS Proxy',
      emoji: '🔗',
      color: '#3b82f6',
      onClick: open('proxy'),
    },
    {
      label: 'Shopify Detect',
      description: 'Detect Shopify',
      emoji: '🔍',
      color: '#06b6d4',
      onClick: open('shopify-detect'),
    },
    {
      label: 'SVG',
      description: 'Editor',
      emoji: '🎨',
      color: '#8b5cf6',
      onClick: open('svg'),
    },
    {
      label: 'UUID',
      description: 'Generator',
      emoji: '🔑',
      color: '#a855f7',
      onClick: open('uuid'),
    },
    {
      label: 'Diff',
      description: 'Text Comparison',
      emoji: '📝',
      color: '#3b82f6',
      onClick: open('text-diff'),
    },
    {
      label: 'Case',
      description: 'Converter',
      emoji: '🔤',
      color: '#3b82f6',
      onClick: open('text-case'),
    },
    {
      label: 'Password',
      description: 'Generator',
      emoji: '🔐',
      color: '#3b82f6',
      onClick: open('text-password'),
    },
    {
      label: 'URL Tracer',
      description: 'Redirect Tracker',
      emoji: '🔗',
      color: '#3b82f6',
      onClick: open('text-url-tracer'),
    },
    {
      label: 'Word Count',
      description: 'Counter',
      emoji: '📊',
      color: '#3b82f6',
      onClick: open('text-word-count'),
    },
    {
      label: 'Screen Recorder',
      description: 'Record & Download',
      emoji: '🎥',
      color: '#3b82f6',
      onClick: open('screen-recorder'),
    },
    {
      label: 'Sheets',
      description: 'SQLite Browser',
      emoji: '🗄️',
      color: '#3b82f6',
      onClick: open('sheets'),
    },
  ],
  calculators: [
    {
      label: 'Calculator',
      description: 'Math',
      emoji: '➗',
      color: '#8b5cf6',
      onClick: open('calculator'),
    },
    {
      label: 'Angle',
      description: 'Converter',
      emoji: '📐',
      color: '#8b5cf6',
      onClick: open('angle'),
    },
    {
      label: 'Base',
      description: 'Converter',
      emoji: '💻',
      color: '#8b5cf6',
      onClick: open('base'),
    },
    {
      label: 'Data',
      description: 'Converter',
      emoji: '💾',
      color: '#8b5cf6',
      onClick: open('data'),
    },
    {
      label: 'Roman',
      description: 'Converter',
      emoji: '🏛️',
      color: '#8b5cf6',
      onClick: open('roman'),
    },
    {
      label: 'Length',
      description: 'Converter',
      emoji: '📏',
      color: '#8b5cf6',
      onClick: open('length'),
    },
    {
      label: 'Weight',
      description: 'Converter',
      emoji: '⚖️',
      color: '#8b5cf6',
      onClick: open('weight'),
    },
    {
      label: 'Temperature',
      description: 'Converter',
      emoji: '🌡️',
      color: '#8b5cf6',
      onClick: open('temperature'),
    },
    {
      label: 'Time',
      description: 'Converter',
      emoji: '⏰',
      color: '#8b5cf6',
      onClick: open('time'),
    },
    {
      label: 'Elo',
      description: 'Calculator',
      emoji: '♟️',
      color: '#f59e0b',
      onClick: open('elo'),
    },
    {
      label: 'Inflation',
      description: 'Calculator',
      emoji: '💰',
      color: '#f59e0b',
      onClick: open('inflation'),
    },
    {
      label: 'Tax',
      description: 'Vietnam PIT',
      emoji: '🇻🇳',
      color: '#ef4444',
      onClick: open('tax'),
    },
    {
      label: 'Split Bill',
      description: 'Calculator',
      emoji: '💵',
      color: '#10b981',
      onClick: open('split-bill'),
    },
    {
      label: 'Days Count',
      description: 'Date Difference',
      emoji: '📅',
      color: '#3b82f6',
      onClick: open('days-count'),
    },
  ],
  casino: [
    {
      label: 'Blackjack',
      description: 'Cards Counter',
      emoji: '🃏',
      color: '#f59e0b',
      onClick: open('blackjack'),
    },
    {
      label: 'Poker',
      description: 'Odds Calculator',
      emoji: '🃏',
      color: '#f59e0b',
      onClick: open('poker'),
    },
  ],
  clocks: [
    {
      label: 'Chess Clock',
      description: 'Chess Timer',
      emoji: '♟️',
      color: '#8b5cf6',
      onClick: open('chess-clock'),
    },
    {
      label: 'Countdown',
      description: 'Timer',
      emoji: '⏳',
      color: '#06b6d4',
      onClick: open('countdown'),
    },
    {
      label: 'Cron',
      description: 'Expression Builder',
      emoji: '🕒',
      color: '#8b5cf6',
      onClick: open('cron'),
    },
    {
      label: 'Pomodoro',
      description: 'Timer',
      emoji: '🍅',
      color: '#ef4444',
      onClick: open('pomodoro'),
    },
    {
      label: 'Watchface',
      description: 'Garmin',
      emoji: '⌚',
      color: '#ef4444',
      onClick: open('watchface'),
    },
  ],
  converters: [
    {
      label: 'Braille',
      description: 'From Text',
      emoji: '⠿',
      color: '#8b5cf6',
      onClick: open('braille'),
    },
    {
      label: 'Colors',
      description: 'From HEX',
      emoji: '🎨',
      color: '#ec4899',
      onClick: open('colors'),
    },
    {
      label: 'Morse Code',
      description: 'From Text',
      emoji: '🔣',
      color: '#f59e0b',
      onClick: open('morse'),
    },
    {
      label: 'Leet Speak',
      description: 'From Text',
      emoji: '🔐',
      color: '#10b981',
      onClick: open('leetspeak'),
    },
    {
      label: 'Lorem Ipsum',
      description: 'Dummy text',
      emoji: '📝',
      color: '#8b5cf6',
      onClick: open('lorem-ipsum'),
    },
    {
      label: 'OpenAPI',
      description: 'to Postman',
      emoji: '🔄',
      color: '#ff6c37',
      onClick: open('openapi'),
    },
  ],
  editors: [
    {
      label: 'JSON Schema',
      description: 'Validator',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('json-schema'),
    },
    {
      label: 'Manifest',
      description: 'JSON Editor',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('manifest'),
    },
    {
      label: 'Markdown',
      description: 'Markdown Editor',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('markdown'),
    },
    {
      label: 'Resume',
      description: 'Resume Builder',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('resume'),
    },
    {
      label: 'Regex',
      description: 'Pattern Generator',
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('regex'),
    },
    {
      label: 'Redact',
      description: 'PDF Redactor',
      emoji: '🖋️',
      color: '#3b82f6',
      onClick: open('redact'),
    },
    {
      label: 'Slides',
      description: 'Pitch Deck',
      emoji: '📽️',
      color: '#3b82f6',
      onClick: open('slides'),
    },
  ],
  pdf: [
    {
      label: 'Combine',
      description: 'Merge/Split',
      emoji: '📄',
      color: '#ef4444',
      onClick: open('pdf-combine'),
    },
    {
      label: 'Security',
      description: 'Encrypt/Decrypt',
      emoji: '🔒',
      color: '#ef4444',
      onClick: open('pdf-security'),
    },
    {
      label: 'Extract',
      description: 'Text/Images',
      emoji: '📋',
      color: '#ef4444',
      onClick: open('pdf-extract'),
    },
    {
      label: 'Edit',
      description: 'Compress/Rotate/Watermark',
      emoji: '✏️',
      color: '#ef4444',
      onClick: open('pdf-edit'),
    },
    {
      label: 'Inspect',
      description: 'Info/Metadata',
      emoji: '🔍',
      color: '#ef4444',
      onClick: open('pdf-inspect'),
    },
    {
      label: 'Maintain',
      description: 'Repair/OCR',
      emoji: '🔧',
      color: '#ef4444',
      onClick: open('pdf-maintain'),
    },
    {
      label: 'Convert',
      description: 'Formats',
      emoji: '📄',
      color: '#ef4444',
      onClick: open('pdf-convert'),
    },
    {
      label: 'Arrange',
      description: 'Reorder/Delete',
      emoji: '📑',
      color: '#ef4444',
      onClick: open('pdf-arrange'),
    },
    {
      label: 'Create',
      description: 'From Text',
      emoji: '📄',
      color: '#ef4444',
      onClick: open('pdf-create'),
    },
    {
      label: 'Translate',
      description: 'PDF',
      emoji: '🌐',
      color: '#ef4444',
      onClick: open('pdf-translate'),
    },
    {
      label: 'eSign',
      description: 'Sign PDF',
      emoji: '✍️',
      color: '#ef4444',
      onClick: open('pdf-esign'),
    },
  ],
  education: [
    {
      label: 'English',
      description: 'Dictionary',
      emoji: '📚',
      color: '#3b82f6',
      onClick: open('english'),
    },
    {
      label: 'Flashcards',
      description: 'Words',
      emoji: '📓',
      color: '#fefefe',
      onClick: open('flashcards'),
    },
    {
      label: 'Sign Language',
      description: 'Detection',
      emoji: '🤟',
      color: '#3b82f6',
      onClick: open('sign'),
    },
    {
      label: 'Periodic Table',
      description: 'Elements',
      emoji: '📊',
      color: '#f59e0b',
      onClick: open('periodic-table'),
    },
    {
      label: 'Pitch',
      description: 'Training',
      emoji: '🎹',
      color: '#8b5cf6',
      onClick: open('pitch'),
    },
    {
      label: 'DOI',
      description: 'Cite',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('doi'),
    },
  ],
  eyes: [
    {
      label: 'LogMAR Chart',
      description: 'LogMAR Chart',
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('logmar'),
    },
    {
      label: 'Snellen Chart',
      description: 'Snellen Chart',
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('snellen'),
    },
    {
      label: 'Tumbling E Chart',
      description: 'Tumbling E Chart',
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('tumbling-e'),
    },
  ],
  games: [
    {
      label: '2048',
      description: 'Merge tiles',
      emoji: '🔢',
      color: '#f59e0b',
      onClick: open('game2048'),
    },
    {
      label: 'Palindrome',
      description: 'Palindrome',
      emoji: '🔁',
      color: '#f59e0b',
      onClick: open('palindrome'),
    },
    {
      label: 'PD',
      description: "Prisoner's Dilemma",
      emoji: '⚖️',
      color: '#f59e0b',
      onClick: open('pd'),
    },
    {
      label: 'Sudoku',
      description: '4×4 & 9×9',
      emoji: '🧩',
      color: '#f59e0b',
      onClick: open('sudoku'),
    },
    {
      label: 'Snake',
      description: '12×12 grid',
      emoji: '🐍',
      color: '#f59e0b',
      onClick: open('snake'),
    },
    {
      label: 'Pokedex',
      description: 'Pokemon',
      emoji: '📕',
      color: '#f59e0b',
      onClick: open('pokedex'),
    },
    {
      label: 'RPS',
      description: 'Rock Paper Scissors',
      emoji: '✂️',
      color: '#f59e0b',
      onClick: open('rps'),
    },
    {
      label: 'T3',
      description: 'Tic-Tac-Toe',
      emoji: '❌',
      color: '#f59e0b',
      onClick: open('t3'),
    },
    {
      label: 'Towers',
      description: 'Towers of Hanoi',
      emoji: '🗼',
      color: '#f59e0b',
      onClick: open('towers'),
    },
    {
      label: 'Typoglycemia',
      description: 'Scrambled text',
      emoji: '🔀',
      color: '#f59e0b',
      onClick: open('typoglycemia'),
    },
    {
      label: 'Wordle',
      description: 'Guess the word',
      emoji: '🟩',
      color: '#f59e0b',
      onClick: open('wordle'),
    },
  ],
  memory: [
    {
      label: 'PI',
      description: 'Memorization',
      emoji: 'π',
      color: '#f59e0b',
      onClick: open('pi'),
    },
    {
      label: 'Quizify',
      description: 'Quiz',
      emoji: '❓',
      color: '#f59e0b',
      onClick: open('quizify'),
    },
    {
      label: 'Recall',
      description: 'Memorization',
      emoji: '🔣',
      color: '#f59e0b',
      onClick: open('recall'),
    },
  ],
  images: [
    {
      label: 'Base64',
      description: 'Decode/Encode',
      emoji: '🔐',
      color: '#3b82f6',
      onClick: open('base64'),
    },
    {
      label: 'Breaking Bad',
      description: 'Element',
      emoji: '🧪',
      color: '#eab308',
      onClick: open('breaking-bad'),
    },
    {
      label: 'Camera',
      description: 'Composition',
      emoji: '📸',
      color: '#ef4444',
      onClick: open('camera'),
    },
    {
      label: 'Social Preview',
      description: 'GitHub',
      emoji: '📸',
      color: '#10b981',
      onClick: open('github-social-preview'),
    },
    {
      label: 'House',
      description: 'M.D.',
      emoji: '🏥',
      color: '#ef4444',
      onClick: open('house'),
    },
    {
      label: 'InstaSize',
      description: 'Square Fit',
      emoji: '📸',
      color: '#3b82f6',
      onClick: open('instasize'),
    },
    {
      label: 'Invoice Parser',
      description: 'OCR',
      emoji: '📄',
      color: '#ef4444',
      onClick: open('invoice-parser'),
    },
    {
      label: 'Barcode',
      description: 'Generator',
      emoji: '▌',
      color: '#22d3ee',
      onClick: open('barcode'),
    },
    {
      label: 'QR Code',
      description: 'Generator',
      emoji: '▦',
      color: '#22d3ee',
      onClick: open('qr'),
    },
    {
      label: 'Thumbnails',
      description: 'YouTube',
      emoji: '📸',
      color: '#22d3ee',
      onClick: open('youtube-thumbnails'),
    },
    {
      label: 'Remove BG',
      description: 'AI Background',
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('ai-remove-bg'),
    },
    {
      label: 'Restore',
      description: 'AI Photo Restore',
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('ai-restore'),
    },
    {
      label: 'Colorize',
      description: 'AI Colorize',
      emoji: '🎨',
      color: '#3b82f6',
      onClick: open('ai-colorize'),
    },
    {
      label: 'Unblur',
      description: 'AI Deblur',
      emoji: '👁️',
      color: '#3b82f6',
      onClick: open('ai-unblur'),
    },
    {
      label: 'Remove Watermark',
      description: 'AI Clean',
      emoji: '💧',
      color: '#3b82f6',
      onClick: open('ai-remove-watermark'),
    },
    {
      label: 'Generate',
      description: 'AI Image Gen',
      emoji: '✨',
      color: '#3b82f6',
      onClick: open('ai-generate'),
    },
    {
      label: 'Remove Person',
      description: 'AI Object Removal',
      emoji: '🚶',
      color: '#3b82f6',
      onClick: open('ai-remove-person'),
    },
    {
      label: 'Remove Object',
      description: 'AI Cleanup',
      emoji: '🎯',
      color: '#3b82f6',
      onClick: open('ai-remove-object'),
    },
    {
      label: 'Upscale',
      description: 'AI Enlarge',
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('ai-upscale'),
    },
    {
      label: 'Art',
      description: 'AI Art Filter',
      emoji: '🎭',
      color: '#3b82f6',
      onClick: open('ai-art'),
    },
    {
      label: 'Resize',
      description: 'Image',
      emoji: '📐',
      color: '#3b82f6',
      onClick: open('image-resize'),
    },
    {
      label: 'Crop',
      description: 'Image',
      emoji: '✂️',
      color: '#3b82f6',
      onClick: open('image-crop'),
    },
    {
      label: 'Compress',
      description: 'Image',
      emoji: '📦',
      color: '#3b82f6',
      onClick: open('image-compress'),
    },
    {
      label: 'Flip',
      description: 'Image',
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('image-flip'),
    },
    {
      label: 'B&W',
      description: 'Image',
      emoji: '⚫',
      color: '#3b82f6',
      onClick: open('image-bw'),
    },
    {
      label: 'Pixelate',
      description: 'Image',
      emoji: '🧊',
      color: '#3b82f6',
      onClick: open('image-pixelate'),
    },
    {
      label: 'Sharpen',
      description: 'Image',
      emoji: '💫',
      color: '#3b82f6',
      onClick: open('image-sharpen'),
    },
    {
      label: 'Border',
      description: 'Image',
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('image-border'),
    },
    {
      label: 'Round',
      description: 'Image',
      emoji: '⭕',
      color: '#3b82f6',
      onClick: open('image-round'),
    },
    {
      label: 'Text',
      description: 'Add Text',
      emoji: '✏️',
      color: '#3b82f6',
      onClick: open('image-text'),
    },
    {
      label: 'Convert',
      description: 'Format',
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('image-convert'),
    },
    {
      label: 'Chart Maker',
      description: 'Create Chart',
      emoji: '📊',
      color: '#3b82f6',
      onClick: open('chart-maker'),
    },
    {
      label: 'Meme Maker',
      description: 'Create Meme',
      emoji: '🎭',
      color: '#3b82f6',
      onClick: open('meme-maker'),
    },
    {
      label: 'Collage',
      description: 'Photo Collage',
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('collage-maker'),
    },
    {
      label: 'Split',
      description: 'Image Splitter',
      emoji: '✂️',
      color: '#3b82f6',
      onClick: open('image-split'),
    },
    {
      label: 'OCR',
      description: 'Text Extraction',
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('image-ocr'),
    },
    {
      label: 'QR Read',
      description: 'QR Scanner',
      emoji: '📱',
      color: '#3b82f6',
      onClick: open('qr-read'),
    },
    {
      label: 'Barcode Read',
      description: 'Barcode Scanner',
      emoji: '📋',
      color: '#3b82f6',
      onClick: open('barcode-read'),
    },
    {
      label: 'Blur',
      description: 'Background/Face',
      emoji: '🌫️',
      color: '#3b82f6',
      onClick: open('image-blur'),
    },
    {
      label: 'Combine',
      description: 'Join Images',
      emoji: '🔗',
      color: '#3b82f6',
      onClick: open('image-combiner'),
    },
    {
      label: 'Colorize',
      description: 'Photo Filter',
      emoji: '🎨',
      color: '#3b82f6',
      onClick: open('image-colorize'),
    },
    {
      label: 'Transparent BG',
      description: 'Make Transparent',
      emoji: '✨',
      color: '#3b82f6',
      onClick: open('image-transparent-bg'),
    },
    {
      label: 'Photo Filters',
      description: 'Apply Filters',
      emoji: '📸',
      color: '#3b82f6',
      onClick: open('image-photo-filters'),
    },
    {
      label: 'Adjust',
      description: 'Brightness/Contrast',
      emoji: '⚙️',
      color: '#3b82f6',
      onClick: open('image-adjust'),
    },
    {
      label: 'Rotate',
      description: 'Rotate Image',
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('image-rotate'),
    },
    {
      label: 'Vignette',
      description: 'Vignette Effect',
      emoji: '🌑',
      color: '#3b82f6',
      onClick: open('image-vignette'),
    },
    {
      label: 'Shadow',
      description: 'Add Shadow',
      emoji: '👤',
      color: '#3b82f6',
      onClick: open('image-shadow'),
    },
    {
      label: 'Watermark',
      description: 'Add Watermark',
      emoji: '💧',
      color: '#3b82f6',
      onClick: open('image-watermark'),
    },
    {
      label: 'Dominant Color',
      description: 'Extract Color',
      emoji: '🎯',
      color: '#3b82f6',
      onClick: open('image-dominant-color'),
    },
    {
      label: 'Profile',
      description: 'Photo Maker',
      emoji: '👤',
      color: '#3b82f6',
      onClick: open('image-profile'),
    },
    {
      label: 'Pixel',
      description: 'Art Grid',
      emoji: '▪️',
      color: '#8b5cf6',
      onClick: open('pixel'),
    },
  ],
  visualization: [
    {
      label: 'Calendar Tracker',
      description: 'Activities',
      emoji: '📅',
      color: '#10b981',
      onClick: open('calendar-tracker'),
    },
    {
      label: 'Legislation',
      description: 'Visualization',
      emoji: '🏛️',
      color: '#ef4444',
      onClick: open('legislation'),
    },
    {
      label: 'Resume',
      description: 'Timeline',
      emoji: '⏳',
      color: '#ef4444',
      onClick: open('resume-timeline'),
    },
    {
      label: 'Graph',
      description: 'Force Layout',
      emoji: '🕸️',
      color: '#6c5ce7',
      onClick: open('graph'),
    },
  ],
  write: [
    {
      label: 'Write',
      description: 'Generate',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-generate'),
    },
    {
      label: 'Improve',
      description: 'Edit Text',
      emoji: '📝',
      color: '#8b5cf6',
      onClick: open('write-improve'),
    },
    {
      label: 'Social',
      description: 'Content',
      emoji: '📱',
      color: '#8b5cf6',
      onClick: open('write-social'),
    },
    {
      label: 'Business',
      description: 'Writing',
      emoji: '💼',
      color: '#8b5cf6',
      onClick: open('write-business'),
    },
    {
      label: 'Marketing',
      description: 'Writing',
      emoji: '📢',
      color: '#8b5cf6',
      onClick: open('write-marketing'),
    },
    {
      label: 'Legal',
      description: 'Docs',
      emoji: '⚖️',
      color: '#8b5cf6',
      onClick: open('write-legal'),
    },
    {
      label: 'Content',
      description: 'Writing',
      emoji: '📰',
      color: '#8b5cf6',
      onClick: open('write-content'),
    },
    {
      label: 'Real Estate',
      description: 'Descriptions',
      emoji: '🏠',
      color: '#8b5cf6',
      onClick: open('write-real-estate'),
    },
  ],
  video: [
    {
      label: 'Convert',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-convert'),
    },
    {
      label: 'Edit',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-edit'),
    },
    {
      label: 'Download',
      description: 'Social Media',
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download'),
    },
    {
      label: 'Audio',
      description: 'Extract/Transcribe',
      emoji: '🎵',
      color: '#ef4444',
      onClick: open('video-audio'),
    },
    {
      label: 'Process',
      description: 'Merge/Speed/Crop',
      emoji: '⚙️',
      color: '#ef4444',
      onClick: open('video-process'),
    },
    {
      label: 'Audio to Text',
      description: 'Transcribe',
      emoji: '🎤',
      color: '#ef4444',
      onClick: open('audio-to-text'),
    },
  ],
  data: [
    {
      label: 'Split CSV',
      description: 'File Splitter',
      emoji: '✂️',
      color: '#10b981',
      onClick: open('split-csv'),
    },
    {
      label: 'Split Excel',
      description: 'File Splitter',
      emoji: '✂️',
      color: '#10b981',
      onClick: open('split-excel'),
    },
    {
      label: 'CSV to Excel',
      description: 'Converter',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('csv-to-excel'),
    },
    {
      label: 'Excel to CSV',
      description: 'Converter',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('excel-to-csv'),
    },
    {
      label: 'XML to Excel',
      description: 'Converter',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-excel'),
    },
    {
      label: 'Excel to XML',
      description: 'Converter',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('excel-to-xml'),
    },
    {
      label: 'XML to CSV',
      description: 'Converter',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-csv'),
    },
    {
      label: 'XML to JSON',
      description: 'Converter',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-json'),
    },
    {
      label: 'Excel to PDF',
      description: 'Converter',
      emoji: '📄',
      color: '#10b981',
      onClick: open('excel-to-pdf'),
    },
    {
      label: 'Create ZIP',
      description: 'Archiver',
      emoji: '🗜️',
      color: '#10b981',
      onClick: open('create-zip'),
    },
    {
      label: 'Epoch Convert',
      description: 'Timestamp',
      emoji: '🕐',
      color: '#10b981',
      onClick: open('epoch-convert'),
    },
    {
      label: 'Word Counter',
      description: 'Count Words',
      emoji: '📝',
      color: '#10b981',
      onClick: open('word-counter'),
    },
  ],
});
