import { Tool } from '@hieudoanm.github.io/components/pages/start/cards/ToolCard';

import { ModalId } from './types';

export const makeTools = (
  open: (id: ModalId) => () => void
): Record<string, Tool[]> => ({
  ai: [
    {
      label: 'Remove BG',
      description: 'AI Background',
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('ai-remove-bg'),
    },
    {
      label: 'Restore',
      description: 'AI Photo Restore',
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('ai-restore'),
    },
    {
      label: 'Colorize',
      description: 'AI Colorize',
      emoji: '🎨',
      color: '#3b82f6',
      onClick: open('ai-colorize'),
    },
    {
      label: 'Unblur',
      description: 'AI Deblur',
      emoji: '👁️',
      color: '#3b82f6',
      onClick: open('ai-unblur'),
    },
    {
      label: 'Remove Watermark',
      description: 'AI Clean',
      emoji: '💧',
      color: '#3b82f6',
      onClick: open('ai-remove-watermark'),
    },
    {
      label: 'Generate',
      description: 'AI Image Gen',
      emoji: '✨',
      color: '#3b82f6',
      onClick: open('ai-generate'),
    },
    {
      label: 'Remove Person',
      description: 'AI Object Removal',
      emoji: '🚶',
      color: '#3b82f6',
      onClick: open('ai-remove-person'),
    },
    {
      label: 'Remove Object',
      description: 'AI Cleanup',
      emoji: '🎯',
      color: '#3b82f6',
      onClick: open('ai-remove-object'),
    },
    {
      label: 'Upscale',
      description: 'AI Enlarge',
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('ai-upscale'),
    },
  ],
  casino: [
    {
      label: 'Blackjack',
      description: 'Cards Counter',
      emoji: '🃏',
      color: '#f59e0b',
      onClick: open('blackjack'),
    },
    {
      label: 'Poker',
      description: 'Odds Calculator',
      emoji: '🃏',
      color: '#f59e0b',
      onClick: open('poker'),
    },
  ],
  clocks: [
    {
      label: 'Chess Clock',
      description: 'Chess Timer',
      emoji: '♟️',
      color: '#8b5cf6',
      onClick: open('chess-clock'),
    },
    {
      label: 'Countdown',
      description: 'Timer',
      emoji: '⏳',
      color: '#06b6d4',
      onClick: open('countdown'),
    },
    {
      label: 'Cron',
      description: 'Expression Builder',
      emoji: '🕒',
      color: '#8b5cf6',
      onClick: open('cron'),
    },
    {
      label: 'Pomodoro',
      description: 'Timer',
      emoji: '🍅',
      color: '#ef4444',
      onClick: open('pomodoro'),
    },
    {
      label: 'Watchface',
      description: 'Garmin',
      emoji: '⌚',
      color: '#ef4444',
      onClick: open('watchface'),
    },
  ],
  converter: [
    {
      label: 'Calculator',
      description: 'Math',
      emoji: '➗',
      color: '#8b5cf6',
      onClick: open('calculator'),
    },
    {
      label: 'Angle',
      description: 'Converter',
      emoji: '📐',
      color: '#8b5cf6',
      onClick: open('angle'),
    },
    {
      label: 'Base',
      description: 'Converter',
      emoji: '💻',
      color: '#8b5cf6',
      onClick: open('base'),
    },
    {
      label: 'Data',
      description: 'Converter',
      emoji: '💾',
      color: '#8b5cf6',
      onClick: open('data'),
    },
    {
      label: 'Roman',
      description: 'Converter',
      emoji: '🏛️',
      color: '#8b5cf6',
      onClick: open('roman'),
    },
    {
      label: 'Length',
      description: 'Converter',
      emoji: '📏',
      color: '#8b5cf6',
      onClick: open('length'),
    },
    {
      label: 'Weight',
      description: 'Converter',
      emoji: '⚖️',
      color: '#8b5cf6',
      onClick: open('weight'),
    },
    {
      label: 'Temperature',
      description: 'Converter',
      emoji: '🌡️',
      color: '#8b5cf6',
      onClick: open('temperature'),
    },
    {
      label: 'Time',
      description: 'Converter',
      emoji: '⏰',
      color: '#8b5cf6',
      onClick: open('time'),
    },
  ],
  'data-csv': [
    {
      label: 'CSV to Excel',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('csv-to-excel'),
    },
    {
      label: 'CSV to JSON',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('csv-to-json'),
    },
    {
      label: 'CSV to XML',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('csv-to-xml'),
    },
    {
      label: 'Excel to CSV',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('excel-to-csv'),
    },
    {
      label: 'Split CSV',
      description: 'Data',
      emoji: '✂️',
      color: '#10b981',
      onClick: open('split-csv'),
    },
  ],
  'data-excel': [
    {
      label: 'Excel to PDF',
      description: 'Data',
      emoji: '📄',
      color: '#10b981',
      onClick: open('excel-to-pdf'),
    },
    {
      label: 'Excel to XML',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('excel-to-xml'),
    },
    {
      label: 'Split Excel',
      description: 'Data',
      emoji: '✂️',
      color: '#10b981',
      onClick: open('split-excel'),
    },
  ],
  'data-utility': [
    {
      label: 'Create ZIP',
      description: 'Data',
      emoji: '🗜️',
      color: '#10b981',
      onClick: open('create-zip'),
    },
    {
      label: 'Epoch Convert',
      description: 'Data',
      emoji: '🕐',
      color: '#10b981',
      onClick: open('epoch-convert'),
    },
    {
      label: 'Word Counter',
      description: 'Data',
      emoji: '📝',
      color: '#10b981',
      onClick: open('word-counter'),
    },
  ],
  'data-xml-json': [
    {
      label: 'JSON to CSV',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('json-to-csv'),
    },
    {
      label: 'JSON to XML',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('json-to-xml'),
    },
    {
      label: 'XML to CSV',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-csv'),
    },
    {
      label: 'XML to Excel',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-excel'),
    },
    {
      label: 'XML to JSON',
      description: 'Data',
      emoji: '🔄',
      color: '#10b981',
      onClick: open('xml-to-json'),
    },
  ],
  developer: [
    {
      label: 'Figlet',
      description: 'Text art',
      emoji: '📝',
      color: '#8b5cf6',
      onClick: open('figlet'),
    },
    {
      label: 'IP',
      description: 'Inspector',
      emoji: '🌐',
      color: '#f59e0b',
      onClick: open('ip'),
    },
    {
      label: 'Proxy',
      description: 'CORS Proxy',
      emoji: '🔗',
      color: '#3b82f6',
      onClick: open('proxy'),
    },
    {
      label: 'Shopify Detect',
      description: 'Detect Shopify',
      emoji: '🔍',
      color: '#06b6d4',
      onClick: open('shopify-detect'),
    },
    {
      label: 'SVG',
      description: 'Editor',
      emoji: '🎨',
      color: '#8b5cf6',
      onClick: open('svg'),
    },
    {
      label: 'UUID',
      description: 'Generator',
      emoji: '🔑',
      color: '#a855f7',
      onClick: open('uuid'),
    },
    {
      label: 'Diff',
      description: 'Text Comparison',
      emoji: '📝',
      color: '#3b82f6',
      onClick: open('text-diff'),
    },
    {
      label: 'Case',
      description: 'Converter',
      emoji: '🔤',
      color: '#3b82f6',
      onClick: open('text-case'),
    },
    {
      label: 'URL Tracer',
      description: 'Redirect Tracker',
      emoji: '🔗',
      color: '#3b82f6',
      onClick: open('text-url-tracer'),
    },
    {
      label: 'Sheets',
      description: 'SQLite Browser',
      emoji: '🗄️',
      color: '#3b82f6',
      onClick: open('sheets'),
    },
  ],
  editors: [
    {
      label: 'JSON Schema',
      description: 'Validator',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('json-schema'),
    },
    {
      label: 'Manifest',
      description: 'JSON Editor',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('manifest'),
    },
    {
      label: 'Markdown',
      description: 'Markdown Editor',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('markdown'),
    },
    {
      label: 'Resume',
      description: 'Resume Builder',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('resume'),
    },
    {
      label: 'Regex',
      description: 'Pattern Generator',
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('regex'),
    },
    {
      label: 'Redact',
      description: 'PDF Redactor',
      emoji: '🖋️',
      color: '#3b82f6',
      onClick: open('redact'),
    },
    {
      label: 'Slides',
      description: 'Pitch Deck',
      emoji: '📽️',
      color: '#3b82f6',
      onClick: open('slides'),
    },
  ],
  education: [
    {
      label: 'English',
      description: 'Dictionary',
      emoji: '📚',
      color: '#3b82f6',
      onClick: open('english'),
    },
    {
      label: 'Flashcards',
      description: 'Words',
      emoji: '📓',
      color: '#fefefe',
      onClick: open('flashcards'),
    },
    {
      label: 'Sign Language',
      description: 'Detection',
      emoji: '🤟',
      color: '#3b82f6',
      onClick: open('sign'),
    },
    {
      label: 'Periodic Table',
      description: 'Elements',
      emoji: '📊',
      color: '#f59e0b',
      onClick: open('periodic-table'),
    },
    {
      label: 'Pitch',
      description: 'Training',
      emoji: '🎹',
      color: '#8b5cf6',
      onClick: open('pitch'),
    },
    {
      label: 'DOI',
      description: 'Cite',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('doi'),
    },
  ],
  eyes: [
    {
      label: 'LogMAR Chart',
      description: 'LogMAR Chart',
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('logmar'),
    },
    {
      label: 'Snellen Chart',
      description: 'Snellen Chart',
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('snellen'),
    },
    {
      label: 'Tumbling E Chart',
      description: 'Tumbling E Chart',
      emoji: '👀',
      color: '#3b82f6',
      onClick: open('tumbling-e'),
    },
  ],
  financial: [
    {
      label: 'Elo',
      description: 'Calculator',
      emoji: '♟️',
      color: '#f59e0b',
      onClick: open('elo'),
    },
    {
      label: 'Inflation',
      description: 'Calculator',
      emoji: '💰',
      color: '#f59e0b',
      onClick: open('inflation'),
    },
    {
      label: 'Tax',
      description: 'Vietnam PIT',
      emoji: '🇻🇳',
      color: '#ef4444',
      onClick: open('tax'),
    },
    {
      label: 'Split Bill',
      description: 'Calculator',
      emoji: '💵',
      color: '#10b981',
      onClick: open('split-bill'),
    },
    {
      label: 'Days Count',
      description: 'Date Difference',
      emoji: '📅',
      color: '#3b82f6',
      onClick: open('days-count'),
    },
  ],
  format: [
    {
      label: 'Braille',
      description: 'From Text',
      emoji: '⠿',
      color: '#8b5cf6',
      onClick: open('braille'),
    },
    {
      label: 'Colors',
      description: 'From HEX',
      emoji: '🎨',
      color: '#ec4899',
      onClick: open('colors'),
    },
    {
      label: 'Morse Code',
      description: 'From Text',
      emoji: '🔣',
      color: '#f59e0b',
      onClick: open('morse'),
    },
    {
      label: 'Leet Speak',
      description: 'From Text',
      emoji: '🔐',
      color: '#10b981',
      onClick: open('leetspeak'),
    },
    {
      label: 'Lorem Ipsum',
      description: 'Dummy text',
      emoji: '📝',
      color: '#8b5cf6',
      onClick: open('lorem-ipsum'),
    },
    {
      label: 'OpenAPI',
      description: 'to Postman',
      emoji: '🔄',
      color: '#ff6c37',
      onClick: open('openapi'),
    },
  ],
  games: [
    {
      label: '2048',
      description: 'Merge tiles',
      emoji: '🔢',
      color: '#f59e0b',
      onClick: open('game2048'),
    },
    {
      label: 'Palindrome',
      description: 'Palindrome',
      emoji: '🔁',
      color: '#f59e0b',
      onClick: open('palindrome'),
    },
    {
      label: 'PD',
      description: "Prisoner's Dilemma",
      emoji: '⚖️',
      color: '#f59e0b',
      onClick: open('pd'),
    },
    {
      label: 'Sudoku',
      description: '4×4 & 9×9',
      emoji: '🧩',
      color: '#f59e0b',
      onClick: open('sudoku'),
    },
    {
      label: 'Snake',
      description: '12×12 grid',
      emoji: '🐍',
      color: '#f59e0b',
      onClick: open('snake'),
    },
    {
      label: 'Pokedex',
      description: 'Pokemon',
      emoji: '📕',
      color: '#f59e0b',
      onClick: open('pokedex'),
    },
    {
      label: 'RPS',
      description: 'Rock Paper Scissors',
      emoji: '✂️',
      color: '#f59e0b',
      onClick: open('rps'),
    },
    {
      label: 'T3',
      description: 'Tic-Tac-Toe',
      emoji: '❌',
      color: '#f59e0b',
      onClick: open('t3'),
    },
    {
      label: 'Towers',
      description: 'Towers of Hanoi',
      emoji: '🗼',
      color: '#f59e0b',
      onClick: open('towers'),
    },
    {
      label: 'Typoglycemia',
      description: 'Scrambled text',
      emoji: '🔀',
      color: '#f59e0b',
      onClick: open('typoglycemia'),
    },
    {
      label: 'Wordle',
      description: 'Guess the word',
      emoji: '🟩',
      color: '#f59e0b',
      onClick: open('wordle'),
    },
  ],
  'image-convert': [
    {
      label: 'HEIC to JPG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-heic-to-jpg'),
    },
    {
      label: 'WebP to JPG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-jpg'),
    },
    {
      label: 'WebP to PNG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-png'),
    },
    {
      label: 'JPG to WebP',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-webp'),
    },
    {
      label: 'JPG to PNG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-png'),
    },
    {
      label: 'PNG to WebP',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-webp'),
    },
    {
      label: 'PNG to JPG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-jpg'),
    },
    {
      label: 'PNG to SVG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-svg'),
    },
  ],
  'image-convert-plus': [
    {
      label: 'HEIC to PNG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-heic-to-png'),
    },
    {
      label: 'JPG to AVIF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-avif'),
    },
    {
      label: 'JPG to GIF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-gif'),
    },
    {
      label: 'JPG to SVG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-svg'),
    },
    {
      label: 'JPG to TIFF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-jpg-to-tiff'),
    },
    {
      label: 'PNG to AVIF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-avif'),
    },
    {
      label: 'PNG to EPS',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-eps'),
    },
    {
      label: 'PNG to GIF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-gif'),
    },
    {
      label: 'PNG to TIFF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-png-to-tiff'),
    },
  ],
  'image-convert-pro': [
    {
      label: 'GIF to JPG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-gif-to-jpg'),
    },
    {
      label: 'GIF to PNG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-gif-to-png'),
    },
    {
      label: 'HEIC to AVIF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-heic-to-avif'),
    },
    {
      label: 'PSD to JPG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-psd-to-jpg'),
    },
    {
      label: 'PSD to PNG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-psd-to-png'),
    },
    {
      label: 'SVG to PNG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-svg-to-png'),
    },
    {
      label: 'TIFF to JPG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-tiff-to-jpg'),
    },
    {
      label: 'TIFF to PNG',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-tiff-to-png'),
    },
    {
      label: 'WebP to AVIF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-avif'),
    },
    {
      label: 'WebP to GIF',
      description: 'Convert',
      emoji: '🔄',
      color: '#06b6d4',
      onClick: open('image-convert-webp-to-gif'),
    },
  ],
  'image-create': [
    {
      label: 'Chart Maker',
      description: 'Create Chart',
      emoji: '📊',
      color: '#3b82f6',
      onClick: open('chart-maker'),
    },
    {
      label: 'Meme Maker',
      description: 'Create Meme',
      emoji: '🎭',
      color: '#3b82f6',
      onClick: open('meme-maker'),
    },
    {
      label: 'Collage',
      description: 'Photo Collage',
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('collage-maker'),
    },
    {
      label: 'Profile',
      description: 'Photo Maker',
      emoji: '👤',
      color: '#3b82f6',
      onClick: open('image-profile'),
    },
    {
      label: 'Pixel',
      description: 'Art Grid',
      emoji: '▪️',
      color: '#8b5cf6',
      onClick: open('pixel'),
    },
    {
      label: 'InstaSize',
      description: 'Square Fit',
      emoji: '📸',
      color: '#3b82f6',
      onClick: open('instasize'),
    },
    {
      label: 'Social Preview',
      description: 'GitHub',
      emoji: '📸',
      color: '#10b981',
      onClick: open('github-social-preview'),
    },
    {
      label: 'Thumbnails',
      description: 'YouTube',
      emoji: '📸',
      color: '#22d3ee',
      onClick: open('youtube-thumbnails'),
    },
    {
      label: 'House',
      description: 'M.D.',
      emoji: '🏥',
      color: '#ef4444',
      onClick: open('house'),
    },
    {
      label: 'Camera',
      description: 'Composition',
      emoji: '📸',
      color: '#ef4444',
      onClick: open('camera'),
    },
    {
      label: 'Breaking Bad',
      description: 'Element',
      emoji: '🧪',
      color: '#eab308',
      onClick: open('breaking-bad'),
    },
    {
      label: 'Base64',
      description: 'Decode/Encode',
      emoji: '🔐',
      color: '#3b82f6',
      onClick: open('base64'),
    },
  ],
  'image-edit': [
    {
      label: 'Resize',
      description: 'Image',
      emoji: '📐',
      color: '#3b82f6',
      onClick: open('image-resize'),
    },
    {
      label: 'Crop',
      description: 'Image',
      emoji: '✂️',
      color: '#3b82f6',
      onClick: open('image-crop'),
    },
    {
      label: 'Compress',
      description: 'Image',
      emoji: '📦',
      color: '#3b82f6',
      onClick: open('image-compress'),
    },
    {
      label: 'Flip',
      description: 'Image',
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('image-flip'),
    },
    {
      label: 'B&W',
      description: 'Image',
      emoji: '⚫',
      color: '#3b82f6',
      onClick: open('image-bw'),
    },
    {
      label: 'Pixelate',
      description: 'Image',
      emoji: '🧊',
      color: '#3b82f6',
      onClick: open('image-pixelate'),
    },
    {
      label: 'Sharpen',
      description: 'Image',
      emoji: '💫',
      color: '#3b82f6',
      onClick: open('image-sharpen'),
    },
    {
      label: 'Border',
      description: 'Image',
      emoji: '🖼️',
      color: '#3b82f6',
      onClick: open('image-border'),
    },
    {
      label: 'Round',
      description: 'Image',
      emoji: '⭕',
      color: '#3b82f6',
      onClick: open('image-round'),
    },
    {
      label: 'Rotate',
      description: 'Image',
      emoji: '🔄',
      color: '#3b82f6',
      onClick: open('image-rotate'),
    },
    {
      label: 'Split',
      description: 'Image Splitter',
      emoji: '✂️',
      color: '#3b82f6',
      onClick: open('image-split'),
    },
  ],
  'image-effect': [
    {
      label: 'Blur Background',
      description: 'Image Effect',
      emoji: '🌫️',
      color: '#06b6d4',
      onClick: open('image-blur-background'),
    },
    {
      label: 'Colorize',
      description: 'Photo Filter',
      emoji: '🎨',
      color: '#3b82f6',
      onClick: open('image-colorize'),
    },
    {
      label: 'Transparent BG',
      description: 'Make Transparent',
      emoji: '✨',
      color: '#3b82f6',
      onClick: open('image-transparent-bg'),
    },
    {
      label: 'Photo Filters',
      description: 'Apply Filters',
      emoji: '📸',
      color: '#3b82f6',
      onClick: open('image-photo-filters'),
    },
    {
      label: 'Adjust',
      description: 'Brightness/Contrast',
      emoji: '⚙️',
      color: '#3b82f6',
      onClick: open('image-adjust'),
    },
    {
      label: 'Vignette',
      description: 'Vignette Effect',
      emoji: '🌑',
      color: '#3b82f6',
      onClick: open('image-vignette'),
    },
    {
      label: 'Shadow',
      description: 'Add Shadow',
      emoji: '👤',
      color: '#3b82f6',
      onClick: open('image-shadow'),
    },
    {
      label: 'Watermark',
      description: 'Add Watermark',
      emoji: '💧',
      color: '#3b82f6',
      onClick: open('image-watermark'),
    },
    {
      label: 'Text',
      description: 'Add Text',
      emoji: '✏️',
      color: '#3b82f6',
      onClick: open('image-text'),
    },
    {
      label: 'Side by Side',
      description: 'Combine',
      emoji: '🔗',
      color: '#06b6d4',
      onClick: open('image-combiner-side-by-side'),
    },
    {
      label: 'Stacked',
      description: 'Combine',
      emoji: '🔗',
      color: '#06b6d4',
      onClick: open('image-combiner-stacked'),
    },
  ],
  'image-scan': [
    {
      label: 'Barcode',
      description: 'Generator',
      emoji: '▌',
      color: '#22d3ee',
      onClick: open('barcode'),
    },
    {
      label: 'QR Code',
      description: 'Generator',
      emoji: '▦',
      color: '#22d3ee',
      onClick: open('qr'),
    },
    {
      label: 'QR Read',
      description: 'QR Scanner',
      emoji: '📱',
      color: '#3b82f6',
      onClick: open('qr-read'),
    },
    {
      label: 'Barcode Read',
      description: 'Barcode Scanner',
      emoji: '📋',
      color: '#3b82f6',
      onClick: open('barcode-read'),
    },
    {
      label: 'OCR',
      description: 'Text Extraction',
      emoji: '🔍',
      color: '#3b82f6',
      onClick: open('image-ocr'),
    },
    {
      label: 'Dominant Color',
      description: 'Extract Color',
      emoji: '🎯',
      color: '#3b82f6',
      onClick: open('image-dominant-color'),
    },
    {
      label: 'Invoice Parser',
      description: 'OCR',
      emoji: '📄',
      color: '#ef4444',
      onClick: open('invoice-parser'),
    },
    {
      label: 'Image Translate',
      description: 'OCR + Translate',
      emoji: '🌐',
      color: '#10b981',
      onClick: open('image-translate'),
    },
  ],
  memory: [
    {
      label: 'PI',
      description: 'Memorization',
      emoji: 'π',
      color: '#f59e0b',
      onClick: open('pi'),
    },
    {
      label: 'Quizify',
      description: 'Quiz',
      emoji: '❓',
      color: '#f59e0b',
      onClick: open('quizify'),
    },
    {
      label: 'Recall',
      description: 'Memorization',
      emoji: '🔣',
      color: '#f59e0b',
      onClick: open('recall'),
    },
  ],
  'pdf-convert': [
    {
      label: 'PDF to Excel',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-excel'),
    },
    {
      label: 'PDF to EPUB',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-epub'),
    },
    {
      label: 'PDF to Images',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-images'),
    },
    {
      label: 'PDF to PPT',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-ppt'),
    },
    {
      label: 'PDF to Word',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-to-word'),
    },
  ],
  'pdf-create': [
    {
      label: 'EPUB to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('epub-to-pdf'),
    },
    {
      label: 'Images to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('images-to-pdf'),
    },
    {
      label: 'MD to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('create-md-to-pdf'),
    },
    {
      label: 'PPT to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('ppt-to-pdf'),
    },
    {
      label: 'Text to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('create-text-to-pdf'),
    },
    {
      label: 'URL to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('create-url-to-pdf'),
    },
    {
      label: 'URL to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('url-to-pdf'),
    },
    {
      label: 'Word to PDF',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('word-to-pdf'),
    },
  ],
  'pdf-ebook': [
    {
      label: 'AZW3 to EPUB',
      description: 'Ebook',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('azw3-to-epub'),
    },
    {
      label: 'AZW3 to MOBI',
      description: 'Ebook',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('azw3-to-mobi'),
    },
    {
      label: 'EPUB to AZW3',
      description: 'Ebook',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('epub-to-azw3'),
    },
    {
      label: 'EPUB to MOBI',
      description: 'Ebook',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('epub-to-mobi'),
    },
    {
      label: 'MOBI to AZW3',
      description: 'Ebook',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('mobi-to-azw3'),
    },
    {
      label: 'MOBI to EPUB',
      description: 'Ebook',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('mobi-to-epub'),
    },
  ],
  'pdf-edit': [
    {
      label: 'Annotate',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-annotate'),
    },
    {
      label: 'Compress',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-compress'),
    },
    {
      label: 'Crop Pages',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-crop'),
    },
    {
      label: 'Delete Pages',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-delete-pages'),
    },
    {
      label: 'Merge',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-merge'),
    },
    {
      label: 'Page Numbers',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-page-numbers'),
    },
    {
      label: 'Rearrange',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-rearrange'),
    },
    {
      label: 'Redact',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-redact'),
    },
    {
      label: 'Rotate',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-rotate'),
    },
    {
      label: 'Split',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-split'),
    },
    {
      label: 'Watermark',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-watermark'),
    },
  ],
  'pdf-extract': [
    {
      label: 'Extract Images',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-extract-images'),
    },
    {
      label: 'Extract Text',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-extract-text'),
    },
    {
      label: 'Info',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-info'),
    },
    {
      label: 'Metadata',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-metadata'),
    },
    {
      label: 'OCR',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-ocr'),
    },
    {
      label: 'Repair',
      description: 'PDF',
      emoji: '📄',
      color: '#3b82f6',
      onClick: open('pdf-repair'),
    },
  ],
  'pdf-misc': [
    {
      label: 'Security',
      description: 'Encrypt/Decrypt',
      emoji: '🔒',
      color: '#ef4444',
      onClick: open('pdf-security'),
    },
    {
      label: 'Translate',
      description: 'PDF',
      emoji: '🌐',
      color: '#ef4444',
      onClick: open('pdf-translate'),
    },
    {
      label: 'eSign',
      description: 'Sign PDF',
      emoji: '✍️',
      color: '#ef4444',
      onClick: open('pdf-esign'),
    },
  ],
  utilities: [
    {
      label: 'Chat',
      description: 'AI Assistant',
      emoji: '💬',
      color: '#3b82f6',
      onClick: open('chat'),
    },
    {
      label: 'Clipboard',
      description: 'Clipboard',
      emoji: '📋',
      color: '#3b82f6',
      onClick: open('clipboard'),
    },
    {
      label: 'Emojis',
      description: 'Explorer',
      emoji: '😀',
      color: '#f59e0b',
      onClick: open('emojis'),
    },
    {
      label: 'Contrast',
      description: 'Checker',
      emoji: '👁️',
      color: '#3b82f6',
      onClick: open('contrast-checker'),
    },
    {
      label: 'Gradient',
      description: 'Generator',
      emoji: '🎨',
      color: '#8b5cf6',
      onClick: open('gradient-generator'),
    },
    {
      label: 'Kaprekar',
      description: 'Routine',
      emoji: '🔢',
      color: '#f59e0b',
      onClick: open('kaprekar'),
    },
    {
      label: 'No Sleep',
      description: 'Timer',
      emoji: '😴',
      color: '#3b82f6',
      onClick: open('no-sleep'),
    },
    {
      label: 'Password',
      description: 'Generator',
      emoji: '🔐',
      color: '#3b82f6',
      onClick: open('text-password'),
    },
    {
      label: 'Word Count',
      description: 'Counter',
      emoji: '📊',
      color: '#3b82f6',
      onClick: open('text-word-count'),
    },
    {
      label: 'Screen Recorder',
      description: 'Record & Download',
      emoji: '🎥',
      color: '#3b82f6',
      onClick: open('screen-recorder'),
    },
  ],
  'video-audio': [
    {
      label: 'Subtitles',
      description: 'Video',
      emoji: '🎤',
      color: '#ef4444',
      onClick: open('generate-subtitle'),
    },
    {
      label: 'Transcribe',
      description: 'Video',
      emoji: '🎤',
      color: '#ef4444',
      onClick: open('audio-transcribe'),
    },
  ],
  'video-convert': [
    {
      label: 'AVI to GIF',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-avi-to-gif'),
    },
    {
      label: 'AVI to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-avi-to-mp3'),
    },
    {
      label: 'AVI to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-avi-to-mp4'),
    },
    {
      label: 'FLV to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-flv-to-mp4'),
    },
    {
      label: 'GIF to MOV',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-gif-to-mov'),
    },
    {
      label: 'GIF to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-gif-to-mp4'),
    },
    {
      label: 'GIF to WebM',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-gif-to-webm'),
    },
    {
      label: 'MKV to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mkv-to-mp4'),
    },
    {
      label: 'MOV to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-mp4'),
    },
    {
      label: 'MP4 to AVI',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-avi'),
    },
    {
      label: 'MP4 to MOV',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-mov'),
    },
    {
      label: 'WMV to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-wmv-to-mp4'),
    },
  ],
  'video-convert-audio': [
    {
      label: 'AAC to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-aac-to-mp3'),
    },
    {
      label: 'AAC to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-aac-to-mp4'),
    },
    {
      label: 'AAC to WAV',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-aac-to-wav'),
    },
    {
      label: 'M4A to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-m4a-to-mp3'),
    },
    {
      label: 'M4A to MP4',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-m4a-to-mp4'),
    },
    {
      label: 'M4A to WAV',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-m4a-to-wav'),
    },
    {
      label: 'MOV to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-mp3'),
    },
    {
      label: 'MOV to WAV',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-wav'),
    },
    {
      label: 'MP4 to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-mp3'),
    },
    {
      label: 'MP4 to WAV',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-wav'),
    },
    {
      label: 'OGG to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-ogg-to-mp3'),
    },
    {
      label: 'OGG to WAV',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-ogg-to-wav'),
    },
  ],
  'video-convert-misc': [
    {
      label: 'Convert to WebM',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-convert-to-webm'),
    },
    {
      label: 'MKV to GIF',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mkv-to-gif'),
    },
    {
      label: 'MKV to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mkv-to-mp3'),
    },
    {
      label: 'MOV to AVI',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-avi'),
    },
    {
      label: 'MOV to GIF',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mov-to-gif'),
    },
    {
      label: 'MP4 to OGG',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-mp4-to-ogg'),
    },
    {
      label: 'Video to GIF',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-to-gif'),
    },
    {
      label: 'Video to WebP',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-to-webp'),
    },
    {
      label: 'WebM to MP3',
      description: 'Video',
      emoji: '🎬',
      color: '#ef4444',
      onClick: open('video-webm-to-mp3'),
    },
  ],
  'video-download': [
    {
      label: 'Facebook',
      description: 'Video',
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-facebook'),
    },
    {
      label: 'Instagram',
      description: 'Video',
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-instagram'),
    },
    {
      label: 'TikTok',
      description: 'Video',
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-tiktok'),
    },
    {
      label: 'Twitter/X',
      description: 'Video',
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-download-twitter'),
    },
    {
      label: 'YouTube to Text',
      description: 'Video',
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-youtube-text'),
    },
    {
      label: 'YouTube Transcript',
      description: 'Video',
      emoji: '⬇️',
      color: '#ef4444',
      onClick: open('video-youtube-transcript'),
    },
  ],
  'video-edit': [
    {
      label: 'Compress',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-compress'),
    },
    {
      label: 'Crop',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-crop'),
    },
    {
      label: 'Extract Audio',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-extract-audio'),
    },
    {
      label: 'Extract Frames',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-extract-frames'),
    },
    {
      label: 'Merge',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-merge'),
    },
    {
      label: 'Mute',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-mute'),
    },
    {
      label: 'Resize',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-resize'),
    },
    {
      label: 'Speed',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-speed'),
    },
    {
      label: 'Stabilize',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-stabilize'),
    },
    {
      label: 'Trim',
      description: 'Video',
      emoji: '✂️',
      color: '#ef4444',
      onClick: open('video-trim'),
    },
  ],
  visualization: [
    {
      label: 'Calendar Tracker',
      description: 'Activities',
      emoji: '📅',
      color: '#10b981',
      onClick: open('calendar-tracker'),
    },
    {
      label: 'Legislation',
      description: 'Visualization',
      emoji: '🏛️',
      color: '#ef4444',
      onClick: open('legislation'),
    },
    {
      label: 'Resume',
      description: 'Timeline',
      emoji: '⏳',
      color: '#ef4444',
      onClick: open('resume-timeline'),
    },
    {
      label: 'Graph',
      description: 'Force Layout',
      emoji: '🕸️',
      color: '#6c5ce7',
      onClick: open('graph'),
    },
  ],
  'write-article': [
    {
      label: 'Article',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-article'),
    },
    {
      label: 'Article Rewriter',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-article-rewriter'),
    },
    {
      label: 'Blog Ideas',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-blog-ideas'),
    },
    {
      label: 'Blog Outline',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-blog-outline'),
    },
    {
      label: 'Blog Post',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-blog-post'),
    },
    {
      label: 'Essay',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-essay'),
    },
    {
      label: 'Listicle',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-listicle'),
    },
    {
      label: 'Paragraph',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-paragraph'),
    },
    {
      label: 'Story',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-story'),
    },
    {
      label: 'Story Ideas',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-story-ideas'),
    },
    {
      label: 'YouTube Script',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-youtube-script'),
    },
  ],
  'write-business': [
    {
      label: 'Bill of Sale',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-bill-of-sale'),
    },
    {
      label: 'Business Name',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-business-name'),
    },
    {
      label: 'Business Plan',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-business-plan'),
    },
    {
      label: 'Slogan',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-business-slogan'),
    },
    {
      label: 'Cold Email',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-cold-email'),
    },
    {
      label: 'Landing Page',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-landing-page'),
    },
    {
      label: 'NDA',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-nda'),
    },
    {
      label: 'Podcast Script',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-podcast-script'),
    },
    {
      label: 'Press Release',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-press-release'),
    },
    {
      label: 'Privacy Policy',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-privacy-policy'),
    },
    {
      label: 'Purchase Agreement',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-purchase-agreement'),
    },
  ],
  'write-content': [
    {
      label: 'Content Brief',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-content-brief'),
    },
    {
      label: 'Content Planner',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-content-planner'),
    },
    {
      label: 'FAQ',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-faq'),
    },
    {
      label: 'Poll',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-poll'),
    },
    {
      label: 'Trivia',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-trivia'),
    },
  ],
  'write-edit': [
    {
      label: 'Complete',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-complete'),
    },
    {
      label: 'Grammar Check',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-grammar'),
    },
    {
      label: 'Humanizer',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-humanizer'),
    },
    {
      label: 'Improve Text',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-improve-text'),
    },
    {
      label: 'Paraphrase',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-paraphrase'),
    },
    {
      label: 'Rewrite',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-rewrite'),
    },
    {
      label: 'Shorten Text',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-shorten'),
    },
    {
      label: 'Summarize',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-summarize'),
    },
    {
      label: 'Tone Changer',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-tone'),
    },
    {
      label: 'Translate',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-translate'),
    },
  ],
  'write-misc': [
    {
      label: 'AI Detector',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-ai-detector'),
    },
    {
      label: 'Explain',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-explain'),
    },
    {
      label: 'Summarize Podcast',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-summarize-podcast'),
    },
    {
      label: 'Summarize YouTube',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-summarize-youtube'),
    },
    {
      label: 'Title Generator',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-title'),
    },
  ],
  'write-real-estate': [
    {
      label: 'Agent Bio',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-real-estate-bio'),
    },
    {
      label: 'Real Estate Desc',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-real-estate-description'),
    },
    {
      label: 'Real Estate Listing',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-real-estate-listing'),
    },
  ],
  'write-social': [
    {
      label: 'Caption',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-caption'),
    },
    {
      label: 'Headline',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-headline'),
    },
    {
      label: 'LinkedIn Post',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-linkedin-post'),
    },
    {
      label: 'Meta Description',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-meta-description'),
    },
    {
      label: 'TikTok Script',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-tiktok-script'),
    },
    {
      label: 'Twitter Generator',
      description: 'Write',
      emoji: '✍️',
      color: '#8b5cf6',
      onClick: open('write-twitter-generator'),
    },
  ],
});
