import Container from '@mini/common/components/Container';
import { Navbar } from '@mini/common/components/Navbar';
import { APP_NAME } from '@mini/common/constants/app.constants';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: APP_NAME,
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex h-screen flex-col">
            <Navbar />
            <div className="grow h-full">
              <Container className="h-full">{children}</Container>
            </div>
            <footer className="border-t shadow">
              <Container>
                <div className="px-4 md:px-8 py-2 md:py-4">
                  <p className="uppercase">Mini</p>
                </div>
              </Container>
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
