[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.1.0", features = [] }

[dependencies]
glib = "=0.20.9"
serde_json = "=1.0.140"
serde = { version = "=1.0.219", features = ["derive"] }
log = "=0.4.26"
tauri = { version = "=2.4.0", features = [] }
tauri-plugin-log = "=2.3.1"
