import type { HistoricalEvent } from './types';

export const EVENTS: HistoricalEvent[] = [
  {
    id: 'printing-press-1450',
    title: 'Printing Press',
    year: 1450,
    description:
      'Gutenberg invented the movable-type printing press in Europe, revolutionising information sharing.',
    category: 'technology',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'columbus-1492',
    title: 'Columbus Reaches Americas',
    year: 1492,
    description:
      'Christopher Columbus landed in the Bahamas, initiating European exploration of the Americas.',
    category: 'culture',
    region: 'americas',
    difficulty: 1,
    source: 'britannica',
  },
  {
    id: 'magna-carta-1215',
    title: 'Magna Carta Signed',
    year: 1215,
    description:
      'King John sealed the Magna Carta at Runnymede, limiting royal power and establishing legal principles.',
    category: 'politics',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'fall-rome-476',
    title: 'Fall of Western Rome',
    year: 476,
    description:
      'The Western Roman Empire fell when Germanic leader Odoacer deposed Emperor Romulus Augustulus.',
    category: 'war',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'battle-hastings-1066',
    title: 'Battle of Hastings',
    year: 1066,
    description:
      'William the Conqueror defeated King Harold II, changing the course of English history.',
    category: 'war',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'declaration-1776',
    title: 'Declaration of Independence',
    year: 1776,
    description:
      'The thirteen American colonies declared independence from Britain, forming the United States.',
    category: 'politics',
    region: 'americas',
    difficulty: 1,
    source: 'britannica',
  },
  {
    id: 'french-revolution-1789',
    title: 'French Revolution Begins',
    year: 1789,
    description:
      'The storming of the Bastille ignited a decade of radical social and political upheaval in France.',
    category: 'politics',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'moon-landing-1969',
    title: 'Apollo 11 Moon Landing',
    year: 1969,
    description:
      'Neil Armstrong and Buzz Aldrin became the first humans to walk on the lunar surface.',
    category: 'space',
    region: 'americas',
    difficulty: 1,
    source: 'nasa',
  },
  {
    id: 'ww1-begins-1914',
    title: 'World War I Begins',
    year: 1914,
    description:
      'The assassination of Archduke Franz Ferdinand triggered a global conflict involving major world powers.',
    category: 'war',
    region: 'europe',
    difficulty: 1,
    source: 'britannica',
  },
  {
    id: 'ww2-ends-1945',
    title: 'World War II Ends',
    year: 1945,
    description:
      'Germany and Japan surrendered, ending the deadliest conflict in human history.',
    category: 'war',
    region: 'world',
    difficulty: 1,
    source: 'britannica',
  },

  {
    id: 'sputnik-1957',
    title: 'Sputnik Launched',
    year: 1957,
    description:
      'The Soviet Union launched the first artificial satellite, sparking the space race.',
    category: 'space',
    region: 'europe',
    difficulty: 1,
    source: 'nasa',
  },
  {
    id: 'penicillin-1928',
    title: 'Penicillin Discovered',
    year: 1928,
    description:
      'Alexander Fleming discovered the antibiotic properties of penicillin, revolutionising medicine.',
    category: 'medicine',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'dna-1953',
    title: 'DNA Structure Discovered',
    year: 1953,
    description:
      'Watson and Crick revealed the double helix structure of DNA, transforming biology.',
    category: 'science',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-flight-1903',
    title: 'First Airplane Flight',
    year: 1903,
    description:
      'The Wright brothers achieved the first powered, sustained, and controlled airplane flight.',
    category: 'technology',
    region: 'americas',
    difficulty: 1,
    source: 'britannica',
  },
  {
    id: 'einstein-relativity-1905',
    title: 'Theory of Relativity',
    year: 1905,
    description:
      'Albert Einstein published his special theory of relativity, fundamentally changing physics.',
    category: 'science',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'fall-berlin-wall-1989',
    title: 'Fall of Berlin Wall',
    year: 1989,
    description:
      'The Berlin Wall fell, symbolising the end of the Cold War and division of Europe.',
    category: 'politics',
    region: 'europe',
    difficulty: 1,
    source: 'britannica',
  },
  {
    id: 'first-olympics-1896',
    title: 'First Modern Olympics',
    year: 1896,
    description:
      'The first modern Olympic Games were held in Athens, reviving the ancient tradition.',
    category: 'sports',
    region: 'europe',
    difficulty: 2,
    source: 'olympic',
  },
  {
    id: 'titanic-sinks-1912',
    title: 'Titanic Sinks',
    year: 1912,
    description:
      'The RMS Titanic struck an iceberg and sank on its maiden voyage, killing over 1,500 people.',
    category: 'culture',
    region: 'world',
    difficulty: 1,
    source: 'britannica',
  },
  {
    id: 'first-iphone-2007',
    title: 'First iPhone Released',
    year: 2007,
    description:
      'Apple introduced the iPhone, revolutionising the smartphone industry and mobile computing.',
    category: 'technology',
    region: 'americas',
    difficulty: 1,
    source: 'apple',
  },
  {
    id: 'einstein-relativity-1915',
    title: 'General Relativity',
    year: 1915,
    description:
      'Einstein completed his general theory of relativity, describing gravity as spacetime curvature.',
    category: 'science',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },

  {
    id: 'great-depression-1929',
    title: 'Great Depression Begins',
    year: 1929,
    description:
      'The Wall Street Crash triggered a worldwide economic depression lasting through the 1930s.',
    category: 'culture',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'womens-suffrage-1920',
    title: 'Womens Suffrage in US',
    year: 1920,
    description:
      'The 19th Amendment granted American women the constitutional right to vote.',
    category: 'politics',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-heart-transplant-1967',
    title: 'First Heart Transplant',
    year: 1967,
    description:
      'Dr. Christiaan Barnard performed the first human-to-human heart transplant in South Africa.',
    category: 'medicine',
    region: 'africa',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'woodstock-1969',
    title: 'Woodstock Festival',
    year: 1969,
    description:
      'The iconic music festival drew over 400,000 people to a dairy farm in New York.',
    category: 'music',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-star-wars-1977',
    title: 'Star Wars Released',
    year: 1977,
    description:
      'George Lucas launched one of the most successful film franchises in cinema history.',
    category: 'film',
    region: 'americas',
    difficulty: 1,
    source: 'imdb',
  },
  {
    id: 'world-wide-web-1991',
    title: 'World Wide Web Launched',
    year: 1991,
    description:
      'Tim Berners-Lee introduced the World Wide Web to the public, transforming global communication.',
    category: 'technology',
    region: 'europe',
    difficulty: 1,
    source: 'webfoundation',
  },
  {
    id: 'human-genome-1990',
    title: 'Human Genome Project Begins',
    year: 1990,
    description:
      'An international effort to map all human genes launched, revolutionising genetics and medicine.',
    category: 'science',
    region: 'world',
    difficulty: 3,
    source: 'genome',
  },
  {
    id: 'dolly-sheep-1996',
    title: 'Dolly the Sheep Cloned',
    year: 1996,
    description:
      'Dolly became the first mammal cloned from an adult somatic cell, a breakthrough in genetics.',
    category: 'science',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'civil-rights-act-1964',
    title: 'Civil Rights Act Passed',
    year: 1964,
    description:
      'The landmark US law outlawed discrimination based on race, colour, religion, sex, or national origin.',
    category: 'politics',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-mars-rover-1997',
    title: 'First Mars Rover Landing',
    year: 1997,
    description:
      'NASAs Pathfinder mission delivered Sojourner, the first successful Mars rover.',
    category: 'space',
    region: 'americas',
    difficulty: 3,
    source: 'nasa',
  },

  {
    id: 'eiffel-tower-1889',
    title: 'Eiffel Tower Completed',
    year: 1889,
    description:
      'Gustave Eiffels iconic tower opened as the centrepiece of the 1889 Worlds Fair in Paris.',
    category: 'culture',
    region: 'europe',
    difficulty: 1,
    source: 'britannica',
  },
  {
    id: 'first-grammy-1959',
    title: 'First Grammy Awards',
    year: 1959,
    description:
      'The inaugural Grammy Awards ceremony honoured musical achievements from 1958.',
    category: 'music',
    region: 'americas',
    difficulty: 3,
    source: 'grammy',
  },
  {
    id: 'beatles-ed-sullivan-1964',
    title: 'Beatles on Ed Sullivan',
    year: 1964,
    description:
      'The Beatles made their legendary US television debut, marking the British Invasion.',
    category: 'music',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-academy-awards-1929',
    title: 'First Academy Awards',
    year: 1929,
    description:
      'The first Oscars ceremony honoured films from 1927 and 1928 in a 15-minute event.',
    category: 'film',
    region: 'americas',
    difficulty: 3,
    source: 'oscars',
  },
  {
    id: 'first-super-bowl-1967',
    title: 'First Super Bowl',
    year: 1967,
    description:
      'The Green Bay Packers won the first AFL-NFL World Championship Game, later called the Super Bowl.',
    category: 'sports',
    region: 'americas',
    difficulty: 2,
    source: 'nfl',
  },
  {
    id: 'touring-bicycle-1885',
    title: 'First Modern Bicycle',
    year: 1885,
    description:
      'John Kemp Starley unveiled the Rover Safety Bicycle, the first modern bicycle design.',
    category: 'technology',
    region: 'europe',
    difficulty: 4,
    source: 'britannica',
  },
  {
    id: 'berlin-wall-built-1961',
    title: 'Berlin Wall Built',
    year: 1961,
    description:
      'East Germany began constructing the Berlin Wall, dividing the city and symbolising Cold War tensions.',
    category: 'politics',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-test-tube-baby-1978',
    title: 'First Test-Tube Baby',
    year: 1978,
    description:
      'Louise Brown, the first baby conceived through IVF, was born in England.',
    category: 'medicine',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-transistor-1947',
    title: 'First Transistor Invented',
    year: 1947,
    description:
      'Bardeen, Brattain, and Shockley invented the transistor at Bell Labs, founding modern electronics.',
    category: 'technology',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-woman-space-1963',
    title: 'First Woman in Space',
    year: 1963,
    description:
      'Valentina Tereshkova became the first woman to fly in space aboard Vostok 6.',
    category: 'space',
    region: 'europe',
    difficulty: 2,
    source: 'nasa',
  },

  {
    id: 'us-constitution-1787',
    title: 'US Constitution Signed',
    year: 1787,
    description:
      'The Philadelphia Convention signed the US Constitution, establishing the framework of American government.',
    category: 'politics',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'smallpox-vaccine-1796',
    title: 'Smallpox Vaccine Developed',
    year: 1796,
    description:
      'Edward Jenner developed the first successful vaccine, using cowpox to prevent smallpox.',
    category: 'medicine',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-subway-1863',
    title: 'First Subway Opens',
    year: 1863,
    description:
      'The London Underground opened as the worlds first underground railway system.',
    category: 'technology',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'marconi-radio-1895',
    title: 'First Radio Transmission',
    year: 1895,
    description:
      'Guglielmo Marconi transmitted the first wireless radio signal, pioneering long-distance communication.',
    category: 'technology',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'xrays-discovered-1895',
    title: 'X-Rays Discovered',
    year: 1895,
    description:
      'Wilhelm Röntgen discovered X-rays, revolutionising medical imaging and diagnosis.',
    category: 'medicine',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'pluto-reclassified-2006',
    title: 'Pluto Reclassified',
    year: 2006,
    description:
      'The IAU reclassified Pluto as a dwarf planet, changing the definition of a planet.',
    category: 'space',
    region: 'world',
    difficulty: 2,
    source: 'nasa',
  },
  {
    id: 'cold-war-ends-1991',
    title: 'Soviet Union Dissolved',
    year: 1991,
    description:
      'The Soviet Union officially dissolved, ending the Cold War and creating 15 independent republics.',
    category: 'politics',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'jesse-owens-1936',
    title: 'Jesse Owens Wins Gold',
    year: 1936,
    description:
      'Jesse Owens won four gold medals at the Berlin Olympics, disproving Nazi racial ideology.',
    category: 'sports',
    region: 'europe',
    difficulty: 2,
    source: 'olympic',
  },
  {
    id: 'live-aid-1985',
    title: 'Live Aid Concert',
    year: 1985,
    description:
      'Bob Geldof organised simultaneous concerts in London and Philadelphia to raise funds for Ethiopian famine relief.',
    category: 'music',
    region: 'world',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'nirvana-nevermind-1991',
    title: 'Nevermind Released',
    year: 1991,
    description:
      'Nirvana released Nevermind, bringing grunge and alternative rock into the mainstream.',
    category: 'music',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },

  {
    id: 'first-telephone-1876',
    title: 'Telephone Patented',
    year: 1876,
    description:
      'Alexander Graham Bell patented the telephone, revolutionising voice communication.',
    category: 'technology',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-motion-picture-1895',
    title: 'First Motion Picture',
    year: 1895,
    description:
      'The Lumière brothers held the first public screening of a motion picture in Paris.',
    category: 'film',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'eniac-1945',
    title: 'ENIAC Computer Built',
    year: 1945,
    description:
      'The first general-purpose electronic digital computer, ENIAC, was completed in the United States.',
    category: 'technology',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'south-africa-democracy-1994',
    title: 'South Africa First Free Election',
    year: 1994,
    description:
      'Nelson Mandela became the first black president after apartheid-era elections.',
    category: 'politics',
    region: 'africa',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'hubble-launched-1990',
    title: 'Hubble Telescope Launched',
    year: 1990,
    description:
      'The Hubble Space Telescope was launched, providing unprecedented views of the universe.',
    category: 'space',
    region: 'americas',
    difficulty: 2,
    source: 'nasa',
  },
  {
    id: 'first-mcdonalds-1940',
    title: 'First McDonald Opens',
    year: 1940,
    description:
      "Richard and Maurice McDonald opened the first McDonald's restaurant in San Bernardino, California.",
    category: 'culture',
    region: 'americas',
    difficulty: 3,
    source: 'mcdonalds',
  },
  {
    id: 'michael-jackson-thriller-1982',
    title: 'Thriller Released',
    year: 1982,
    description:
      'Michael Jackson released Thriller, which became the best-selling album of all time.',
    category: 'music',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-space-shuttle-1981',
    title: 'First Space Shuttle Flight',
    year: 1981,
    description:
      'Space Shuttle Columbia launched on STS-1, the first orbital flight of the Space Shuttle program.',
    category: 'space',
    region: 'americas',
    difficulty: 3,
    source: 'nasa',
  },
  {
    id: 'us-civil-war-ends-1865',
    title: 'US Civil War Ends',
    year: 1865,
    description:
      'Confederate General Robert E. Lee surrendered to Union General Ulysses S. Grant, ending the Civil War.',
    category: 'war',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-microprocessor-1971',
    title: 'First Microprocessor',
    year: 1971,
    description:
      'Intels 4004 became the first commercially available microprocessor, ushering in the computing age.',
    category: 'technology',
    region: 'americas',
    difficulty: 3,
    source: 'intel',
  },

  {
    id: 'waterloo-1815',
    title: 'Battle of Waterloo',
    year: 1815,
    description:
      'Napoleon Bonaparte was defeated by a coalition of European armies, ending his rule.',
    category: 'war',
    region: 'europe',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-automobile-1886',
    title: 'First Automobile',
    year: 1886,
    description:
      'Karl Benz patented the first gasoline-powered automobile, the Benz Patent-Motorwagen.',
    category: 'technology',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'mtv-launches-1981',
    title: 'MTV Launches',
    year: 1981,
    description:
      'MTV began broadcasting, transforming the music industry with the concept of music videos.',
    category: 'music',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-color-film-1939',
    title: 'Gone With the Wind Released',
    year: 1939,
    description:
      'The epic historical romance became one of the highest-grossing and most iconic films in cinema.',
    category: 'film',
    region: 'americas',
    difficulty: 2,
    source: 'imdb',
  },
  {
    id: 'iss-begins-1998',
    title: 'International Space Station Begins',
    year: 1998,
    description:
      'The first module of the ISS was launched, beginning the largest international space collaboration.',
    category: 'space',
    region: 'world',
    difficulty: 3,
    source: 'nasa',
  },
  {
    id: 'first-womens-world-cup-1991',
    title: 'First Womens World Cup',
    year: 1991,
    description:
      'The first FIFA Womens World Cup was held in China, won by the United States.',
    category: 'sports',
    region: 'world',
    difficulty: 3,
    source: 'fifa',
  },
  {
    id: 'coronavirus-pandemic-2020',
    title: 'COVID-19 Pandemic Declared',
    year: 2020,
    description:
      'The WHO declared COVID-19 a global pandemic, leading to worldwide lockdowns and health crises.',
    category: 'medicine',
    region: 'world',
    difficulty: 1,
    source: 'who',
  },
  {
    id: 'light-bulb-1879',
    title: 'Light Bulb Patented',
    year: 1879,
    description:
      'Thomas Edison patented a practical incandescent light bulb, illuminating the modern world.',
    category: 'technology',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-television-1927',
    title: 'First Television Demonstrated',
    year: 1927,
    description:
      'Philo Farnsworth successfully demonstrated the first fully electronic television system.',
    category: 'technology',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'barcelona-olympics-1992',
    title: 'Barcelona Olympics',
    year: 1992,
    description:
      'The Summer Olympics in Barcelona were the first without a boycott since 1972.',
    category: 'sports',
    region: 'europe',
    difficulty: 3,
    source: 'olympic',
  },

  {
    id: 'pepsi-cola-1898',
    title: 'Pepsi-Cola Created',
    year: 1898,
    description:
      'Caleb Bradham created Pepsi-Cola in New Bern, North Carolina, as a digestive aid.',
    category: 'culture',
    region: 'americas',
    difficulty: 4,
    source: 'pepsi',
  },
  {
    id: 'hamlet-1600',
    title: 'Hamlet Published',
    year: 1600,
    description:
      'William Shakespeare wrote Hamlet, one of the most influential works in English literature.',
    category: 'culture',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-blood-transfusion-1818',
    title: 'First Blood Transfusion',
    year: 1818,
    description:
      'British obstetrician James Blundell performed the first successful human blood transfusion.',
    category: 'medicine',
    region: 'europe',
    difficulty: 4,
    source: 'britannica',
  },
  {
    id: 'insulin-discovered-1921',
    title: 'Insulin Discovered',
    year: 1921,
    description:
      'Banting and Best isolated insulin at the University of Toronto, transforming diabetes treatment.',
    category: 'medicine',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-spacewalk-1965',
    title: 'First Spacewalk',
    year: 1965,
    description:
      'Alexei Leonov became the first person to conduct a spacewalk, lasting 12 minutes.',
    category: 'space',
    region: 'europe',
    difficulty: 3,
    source: 'nasa',
  },
  {
    id: 'beethoven-5th-1808',
    title: 'Beethovens 5th Premieres',
    year: 1808,
    description:
      'Beethovens Symphony No. 5 premiered in Vienna, becoming one of the most recognisable pieces in classical music.',
    category: 'music',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-tour-de-france-1903',
    title: 'First Tour de France',
    year: 1903,
    description:
      'The first Tour de France cycling race was held, covering six stages over 2,428 kilometres.',
    category: 'sports',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'emancipation-1863',
    title: 'Emancipation Proclamation',
    year: 1863,
    description:
      'President Lincoln declared slaves in Confederate states free, shifting the Civil War aims.',
    category: 'politics',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'snow-white-1937',
    title: 'Snow White Released',
    year: 1937,
    description:
      'Disneys Snow White became the first full-length cel-animated feature film in history.',
    category: 'film',
    region: 'americas',
    difficulty: 2,
    source: 'disney',
  },
  {
    id: 'jurassic-park-1993',
    title: 'Jurassic Park Released',
    year: 1993,
    description:
      'Steven Spielbergs dinosaur blockbuster revolutionised visual effects with CGI creatures.',
    category: 'film',
    region: 'americas',
    difficulty: 2,
    source: 'imdb',
  },

  {
    id: 'first-scuba-1943',
    title: 'First Scuba Gear',
    year: 1943,
    description:
      'Jacques Cousteau and Émile Gagnan developed the Aqua-Lung, the first modern scuba diving equipment.',
    category: 'technology',
    region: 'europe',
    difficulty: 4,
    source: 'britannica',
  },
  {
    id: 'taj-mahal-1653',
    title: 'Taj Mahal Completed',
    year: 1653,
    description:
      'The Taj Mahal was completed in Agra, built by Emperor Shah Jahan as a mausoleum for his wife.',
    category: 'culture',
    region: 'asia',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-nobel-1901',
    title: 'First Nobel Prizes',
    year: 1901,
    description:
      'The first Nobel Prizes were awarded in Stockholm in physics, chemistry, medicine, literature, and peace.',
    category: 'culture',
    region: 'europe',
    difficulty: 3,
    source: 'nobel',
  },
  {
    id: 'panama-canal-1914',
    title: 'Panama Canal Opens',
    year: 1914,
    description:
      'The Panama Canal opened, connecting the Atlantic and Pacific Oceans and transforming global trade.',
    category: 'technology',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'first-balloon-flight-1783',
    title: 'First Hot Air Balloon Flight',
    year: 1783,
    description:
      'The Montgolfier brothers launched the first manned hot air balloon flight in Paris.',
    category: 'science',
    region: 'europe',
    difficulty: 4,
    source: 'britannica',
  },
  {
    id: 'first-computer-mouse-1964',
    title: 'First Computer Mouse',
    year: 1964,
    description:
      'Douglas Engelbart invented the first computer mouse, a wooden shell with two metal wheels.',
    category: 'technology',
    region: 'americas',
    difficulty: 4,
    source: 'britannica',
  },
  {
    id: 'first-photograph-1826',
    title: 'First Photograph Taken',
    year: 1826,
    description:
      'Joseph Nicéphore Niépce captured the earliest known permanent photograph using a camera obscura.',
    category: 'technology',
    region: 'europe',
    difficulty: 4,
    source: 'britannica',
  },
  {
    id: 'marie-curie-radium-1898',
    title: 'Radium Discovered',
    year: 1898,
    description:
      'Marie and Pierre Curie discovered radium, advancing the understanding of radioactivity.',
    category: 'science',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'polo-vaccine-1955',
    title: 'Polio Vaccine Announced',
    year: 1955,
    description:
      'Dr. Jonas Salk announced the successful polio vaccine, nearly eradicating the disease worldwide.',
    category: 'medicine',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-canada-1867',
    title: 'Canadian Confederation',
    year: 1867,
    description:
      'The British North America Act united three colonies into the Dominion of Canada.',
    category: 'politics',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },

  {
    id: 'avatar-2009',
    title: 'Avatar Released',
    year: 2009,
    description:
      'James Camerons Avatar became the highest-grossing film of all time using groundbreaking 3D technology.',
    category: 'film',
    region: 'americas',
    difficulty: 2,
    source: 'imdb',
  },
  {
    id: 'usain-bolt-2008',
    title: 'Usain Bolt Triple Gold',
    year: 2008,
    description:
      'Usain Bolt won three gold medals at the Beijing Olympics with world records in all three events.',
    category: 'sports',
    region: 'asia',
    difficulty: 2,
    source: 'olympic',
  },
  {
    id: 'phelps-8-golds-2008',
    title: 'Phelps Eight Golds',
    year: 2008,
    description:
      'Michael Phelps won eight gold medals at the Beijing Olympics, the most by any athlete in a single Games.',
    category: 'sports',
    region: 'asia',
    difficulty: 3,
    source: 'olympic',
  },
  {
    id: 'google-founded-1998',
    title: 'Google Founded',
    year: 1998,
    description:
      'Larry Page and Sergey Brin founded Google in a garage, revolutionising internet search.',
    category: 'technology',
    region: 'americas',
    difficulty: 1,
    source: 'google',
  },
  {
    id: 'facebook-launched-2004',
    title: 'Facebook Launched',
    year: 2004,
    description:
      'Mark Zuckerberg launched Facebook from his Harvard dormitory, creating the largest social network.',
    category: 'technology',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'youtube-founded-2005',
    title: 'YouTube Founded',
    year: 2005,
    description:
      'Three former PayPal employees founded YouTube, transforming video sharing and online content.',
    category: 'technology',
    region: 'americas',
    difficulty: 2,
    source: 'britannica',
  },
  {
    id: 'citizen-kane-1941',
    title: 'Citizen Kane Released',
    year: 1941,
    description:
      'Orson Welles released Citizen Kane, widely regarded as one of the greatest films ever made.',
    category: 'film',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-vaccine-1796',
    title: 'First Vaccine Created',
    year: 1796,
    description:
      'Edward Jenner administered the first smallpox vaccine, founding the science of immunology.',
    category: 'medicine',
    region: 'europe',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'elvis-first-record-1954',
    title: 'Elvis First Record',
    year: 1954,
    description:
      'Elvis Presley released That All Right, marking the dawn of rock and roll music.',
    category: 'music',
    region: 'americas',
    difficulty: 3,
    source: 'britannica',
  },
  {
    id: 'first-video-game-1972',
    title: 'First Video Game Console',
    year: 1972,
    description:
      'Magnavox released the Odyssey, the first home video game console, featuring table tennis.',
    category: 'technology',
    region: 'americas',
    difficulty: 4,
    source: 'britannica',
  },
];

export const INITIAL_EVENTS: HistoricalEvent[] = [
  EVENTS.find((e) => e.id === 'columbus-1492')!,
  EVENTS.find((e) => e.id === 'ww2-ends-1945')!,
];
