#!/usr/bin/env sh

pnpm run lint --concurrency=1 --filter=...[origin/master]
pnpm run build --concurrency=1 --filter=...[origin/master]
pnpm run format --concurrency=1 --filter=...[origin/master]
git add -A
