#!/usr/bin/env sh

pnpm run lint --filter=...[origin/master] --concurrency=2
pnpm run build --filter=...[origin/master] --concurrency=2
pnpm run format --filter=...[origin/master] --concurrency=2
git add -A
