export const currencyLocaleMap: Record<string, string> = {
  USD: 'en-US',
  VND: 'vi-VN',
  JPY: 'ja-JP',
  EUR: 'de-DE',
  GBP: 'en-GB',
  AUD: 'en-AU',
  CAD: 'en-CA',
  CHF: 'de-CH',
  CNY: 'zh-CN',
  SEK: 'sv-SE',
  NOK: 'nb-NO',
  DKK: 'da-DK',
  INR: 'en-IN',
  RUB: 'ru-RU',
  BRL: 'pt-BR',
  MXN: 'es-MX',
  ZAR: 'en-ZA',
  SGD: 'en-SG',
  HKD: 'zh-HK',
  NZD: 'en-NZ',
  KRW: 'ko-KR',
  TRY: 'tr-TR',
  ARS: 'es-AR',
  PLN: 'pl-PL',
  PHP: 'en-PH',
  IDR: 'id-ID',
  MYR: 'ms-MY',
  THB: 'th-TH',
  ILS: 'he-IL',
  CLP: 'es-CL',
  COP: 'es-CO',
  SAR: 'ar-SA',
  AED: 'ar-AE',
  EGP: 'ar-EG',
  NGN: 'en-NG',
  PKR: 'en-PK',
  BD: 'bn-BD',
  KES: 'en-KE',
  CZK: 'cs-CZ',
  HUF: 'hu-HU',
  RON: 'ro-RO',
  BGN: 'bg-BG',
  HRK: 'hr-HR',
  VEF: 'es-VE',
  UAH: 'uk-UA',
  LKR: 'si-LK',
};

import { InflationResult } from './types';

export const healthConfig: Record<
  InflationResult['health'],
  { border: string; bg: string; text: string; emoji: string }
> = {
  deflation: {
    border: 'border-success',
    bg: 'bg-success',
    text: 'text-success-content',
    emoji: '🟢',
  },
  low: {
    border: 'border-warning',
    bg: 'bg-warning',
    text: 'text-warning-content',
    emoji: '🟡',
  },
  moderate: {
    border: 'border-orange-500',
    bg: 'bg-orange-400',
    text: 'text-white',
    emoji: '🟠',
  },
  high: {
    border: 'border-error',
    bg: 'bg-error',
    text: 'text-error-content',
    emoji: '🔴',
  },
};
