export const morse: Record<string, { code: string; pattern: string }> = {
  a: { code: '.-', pattern: 'di-dah' },
  b: { code: '-...', pattern: 'dah-di-di-dit' },
  c: { code: '-.-.', pattern: 'dah-di-dah-dit' },
  d: { code: '-..', pattern: 'dah-di-dit' },
  e: { code: '.', pattern: 'dit' },
  f: { code: '..-.', pattern: 'di-di-dah-dit' },
  g: { code: '--.', pattern: 'dah-dah-dit' },
  h: { code: '....', pattern: 'di-di-di-dit' },
  i: { code: '..', pattern: 'di-dit' },
  j: { code: '.---', pattern: 'di-dah-dah-dah' },
  k: { code: '-.-', pattern: 'dah-di-dah' },
  l: { code: '.-..', pattern: 'di-dah-di-dit' },
  m: { code: '--', pattern: 'dah-dah' },
  n: { code: '-.', pattern: 'dah-dit' },
  o: { code: '---', pattern: 'dah-dah-dah' },
  p: { code: '.--.', pattern: 'di-dah-dah-dit' },
  q: { code: '--.-', pattern: 'dah-dah-di-dah' },
  r: { code: '.-.', pattern: 'di-dah-dit' },
  s: { code: '...', pattern: 'di-di-dit' },
  t: { code: '-', pattern: 'dah' },
  u: { code: '..-', pattern: 'di-di-dah' },
  v: { code: '...-', pattern: 'di-di-di-dah' },
  w: { code: '.--', pattern: 'di-dah-dah' },
  x: { code: '-..-', pattern: 'dah-di-di-dah' },
  y: { code: '-.--', pattern: 'dah-di-dah-dah' },
  z: { code: '--..', pattern: 'dah-dah-di-dit' },
  '1': { code: '.----', pattern: 'di-dah-dah-dah-dah' },
  '2': { code: '..---', pattern: 'di-di-dah-dah-dah' },
  '3': { code: '...--', pattern: 'di-di-di-dah-dah' },
  '4': { code: '....-', pattern: 'di-di-di-di-dah' },
  '5': { code: '.....', pattern: 'di-di-di-di-dit' },
  '6': { code: '-....', pattern: 'dah-di-di-di-dit' },
  '7': { code: '--...', pattern: 'dah-dah-di-di-dit' },
  '8': { code: '---..', pattern: 'dah-dah-dah-di-dit' },
  '9': { code: '----.', pattern: 'dah-dah-dah-dah-dit' },
  '0': { code: '-----', pattern: 'dah-dah-dah-dah-dah' },
  '.': { code: '.-.-.-', pattern: 'di-dah-di-dah-di-dah' },
  ',': { code: '--..--', pattern: 'dah-dah-di-di-dah-dah' },
  '?': { code: '..--..', pattern: 'di-di-dah-dah-di-dit' },
  "'": { code: '.----.', pattern: 'di-dah-dah-dah-dah-dit' },
  '!': { code: '-.-.--', pattern: 'dah-di-dah-di-dah-dah' },
  '/': { code: '-..-.', pattern: 'dah-di-di-dah-dit' },
  ' ': { code: '/', pattern: 'word-space' },
};

export const SAMPLES = ['Hello world', 'SOS', 'CQ CQ DE'];
