// Package constants ...
package constants

// VietnamAPI ...
const VietnamAPI string = "https://cafesangapi.vercel.app/api"

// UsaAPI ...
const UsaAPI string = "https://usaapi.vercel.app/api"

// SportsAPI ...
const SportsAPI string = "https://sportsinsightsapi.vercel.app/api"

// ChessAPI ...
const ChessAPI string = "https://chessanalysisapi.vercel.app/api"

// GoogleAPI ...
const GoogleAPI string = "https://dashboardworldapi.vercel.app/api"

// FiatAPI ...
const FiatAPI string = "https://dashboardworldapi.vercel.app/api"

// CountriesAPI ...
const CountriesAPI string = "https://dashboardworldapi.vercel.app/api"
