name: CI - App - Native - NFC

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/native/nfc/android/**'
      - '.github/workflows/ci-app-native-nfc.yaml'
      - '.github/workflows/ci-app-native-template.yaml'

permissions:
  contents: read

concurrency:
  group: ci-app-native-nfc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-native-template.yaml
    with:
      package: packages/app/native/nfc/android
      releaseName: app-native-nfc-latest
      releaseTitle: App - Native - NFC (latest)
      artifactPrefix: nfc
