name: CI - App - Hybrid - Education - Music

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/education/music/**/*'
      - '.github/workflows/ci-app-hybrid-education-music.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-education-music-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/education/music
      filter: '@hieudoanm.github.io/music'
      releaseName: app-hybrid-education-music-latest
      releaseTitle: App - Hybrid - Education - Music (latest)
      artifactPrefix: education-music
      artifactName: music
