name: CI - App - Hybrid - Utilities - Password

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/utilities/password/**'
      - '.github/workflows/ci-app-hybrid-utilities-password.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-utilities-password-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/utilities/password
      filter: '@hieudoanm.github.io/password'
      releaseName: app-hybrid-utilities-password-latest
      releaseTitle: App - Hybrid - Utilities - Password (latest)
      artifactPrefix: utilities-password
