name: CI - App - Hybrid - Boilerplate

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/boilerplate/**'
      - '.github/workflows/ci-app-hybrid-boilerplate.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: read

concurrency:
  group: ci-app-hybrid-boilerplate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/boilerplate
      filter: '@hieudoanm.github.io/next'
      releaseName: app-hybrid-boilerplate-latest
      releaseTitle: App - Hybrid - Boilerplate (latest)
      artifactPrefix: boilerplate
