name: CI - App - Hybrid - Football

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/football/**'
      - '.github/workflows/ci-app-hybrid-football.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-football-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/football
      filter: '@hieudoanm.github.io/football'
      releaseName: app-hybrid-football-latest
      releaseTitle: App - Hybrid - Football (latest)
      artifactPrefix: football
