name: CI - App - Hybrid - Graphics Design - SVG

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/graphics-design/svg/**'
      - '.github/workflows/ci-app-hybrid-graphics-design-svg.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-graphics-design-svg-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/graphics-design/svg
      filter: '@hieudoanm.github.io/svg'
      releaseName: app-hybrid-graphics-design-svg-latest
      releaseTitle: App - Hybrid - Graphics Design - SVG (latest)
      artifactPrefix: graphics-design-svg
