name: CI - App - Hybrid - Medical - Brainbow

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/medical/brainbow/**'
      - '.github/workflows/ci-app-hybrid-medical-brainbow.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-medical-brainbow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/medical/brainbow
      filter: '@hieudoanm.github.io/brainbow'
      releaseName: app-hybrid-medical-brainbow-latest
      releaseTitle: App - Hybrid - Medical - Brainbow (latest)
      artifactPrefix: medical-brainbow
