name: CI - App - Hybrid - Sports - Chess

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/sports/chess/**/*'
      - '.github/workflows/ci-app-hybrid-sports-chess.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-sports-chess-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/sports/chess
      filter: '@hieudoanm.github.io/chess'
      releaseName: app-hybrid-sports-chess-latest
      releaseTitle: App - Hybrid - Sports - Chess (latest)
      artifactPrefix: sports-chess
      artifactName: chess
