name: CI - App - Hybrid - Markdown

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/markdown/**'
      - '.github/workflows/ci-app-hybrid-markdown.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-markdown-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/markdown
      filter: '@hieudoanm.github.io/markdown'
      releaseName: app-hybrid-markdown-latest
      releaseTitle: App - Hybrid - Markdown (latest)
      artifactPrefix: markdown
