name: CI - App - Hybrid - Productivity - PDF

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/productivity/pdf/**'
      - '.github/workflows/ci-app-hybrid-productivity-pdf.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-productivity-pdf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/productivity/pdf
      filter: '@hieudoanm.github.io/pdf'
      releaseName: app-hybrid-productivity-pdf-latest
      releaseTitle: App - Hybrid - Productivity - PDF (latest)
      artifactPrefix: productivity-pdf
