name: CI - App - Hybrid - Database

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/database/**'
      - '.github/workflows/ci-app-hybrid-database.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: read

concurrency:
  group: ci-app-hybrid-database-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/database
      filter: '@hieudoanm.github.io/database'
      releaseName: app-hybrid-database-latest
      releaseTitle: App - Hybrid - Database (latest)
      artifactPrefix: database
