name: CI - App - Hybrid - Video

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/video/**'
      - '.github/workflows/ci-app-hybrid-video.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-video-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/video
      filter: '@hieudoanm.github.io/video'
      releaseName: app-hybrid-video-latest
      releaseTitle: App - Hybrid - Video (latest)
      artifactPrefix: video
