name: CI - App - Headless - KeVIn

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/headless/kevin/languages/go/**'
      - 'packages/app/headless/kevin/languages/rust/**'
      - '.github/workflows/ci-app-headless-kevin.yaml'
      - '.github/workflows/ci-app-headless-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-headless-kevin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-headless-template.yaml
    with:
      package: packages/app/headless/kevin/languages/go
      rustPackage: packages/app/headless/kevin/languages/rust
      releaseName: app-headless-kevin-latest
      releaseTitle: App - Headless - KeVIn (latest)
      artifactName: app-headless-kevin
      artifactPath: packages/app/headless/kevin/languages/go/bin/*
      rustArtifactPath: packages/app/headless/kevin/languages/rust/target/release/kevin
      installZig: false
