name: CI - App - Native - macOS - Clipper

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/native/clipper/apple/macos/**'
      - '.github/workflows/ci-app-native-macos-clipper.yaml'
      - '.github/workflows/ci-app-native-macos-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-native-macos-clipper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-native-macos-template.yaml
    with:
      package: packages/app/native/clipper/apple/macos
      releaseName: app-native-macos-clipper-latest
      releaseTitle: App - Native - macOS - Clipper (latest)
      artifactPrefix: macos-clipper
