name: CI - App - Headless - Jack

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/headless/jack/languages/go/**'
      - 'packages/app/headless/jack/languages/rust/**'
      - '.github/workflows/ci-app-headless-jack.yaml'
      - '.github/workflows/ci-app-headless-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-headless-jack-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-headless-template.yaml
    with:
      package: packages/app/headless/jack/languages/go
      rustPackage: packages/app/headless/jack/languages/rust
      releaseName: app-headless-jack-latest
      releaseTitle: App - Headless - Jack (latest)
      artifactName: app-headless-jack
      artifactPath: packages/app/headless/jack/languages/go/bin/*
      rustArtifactPath: packages/app/headless/jack/languages/rust/target/release/jack
      installZig: true
      installRustDeps: false
