name: CI - App - Hybrid - Developer Tools - API

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/developer-tools/api/**/*'
      - '.github/workflows/ci-app-hybrid-developer-tools-api.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-developer-tools-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/developer-tools/api
      filter: '@hieudoanm.github.io/api'
      releaseName: app-hybrid-developer-tools-api-latest
      releaseTitle: App - Hybrid - Developer Tools - API (latest)
      artifactPrefix: developer-tools-api
      artifactName: api
