name: CI - App - Native - macOS - Mixer

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/native/mixer/apple/macos/**'
      - '.github/workflows/ci-app-native-macos-mixer.yaml'
      - '.github/workflows/ci-app-native-macos-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-native-macos-mixer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-native-macos-template.yaml
    with:
      package: packages/app/native/mixer/apple/macos
      releaseName: app-native-macos-mixer-latest
      releaseTitle: App - Native - macOS - Mixer (latest)
      artifactPrefix: macos-mixer
