name: CI - App - Hybrid - Social Networking - Messaging

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/social-networking/messaging/**/*'
      - '.github/workflows/ci-app-hybrid-social-networking-messaging.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-social-networking-messaging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/social-networking/messaging
      filter: '@hieudoanm.github.io/messaging'
      releaseName: app-hybrid-social-networking-messaging-latest
      releaseTitle: App - Hybrid - Social Networking - Messaging (latest)
      artifactPrefix: social-networking-messaging
