name: CI - App - Hybrid - Resume

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/app/hybrid/resume/**'
      - '.github/workflows/ci-app-hybrid-resume.yaml'
      - '.github/workflows/ci-app-hybrid-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-app-hybrid-resume-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-app-hybrid-template.yaml
    with:
      package: packages/app/hybrid/resume
      filter: '@hieudoanm.github.io/resume'
      releaseName: app-hybrid-resume-latest
      releaseTitle: App - Hybrid - Resume (latest)
      artifactPrefix: resume
