name: CI - CLI - Clap

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/cli/hieudoanm/rust/**'
      - '.github/workflows/ci-cli-clap.yaml'

permissions:
  contents: write

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/cli/hieudoanm/rust
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.11.0
        with:
          components: clippy

      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release
