name: CI - Extensions - Browser - ShopifyX

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/extensions/browser/shopifyx/**'
      - '.github/workflows/ci-extensions-browser-shopifyx.yaml'
      - '.github/workflows/ci-extensions-browser-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-extensions-browser-shopifyx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-extensions-browser-template.yaml
    with:
      package: packages/extensions/browser/shopifyx
      filter: '@hieudoanm.github.io/shopifyx'
      releaseName: extensions-browser-shopifyx-latest
      releaseTitle: Extensions - Browser - ShopifyX (latest)
      artifactPrefix: extensions-browser-shopifyx
