name: CI - Extensions - Browser - Snapshot

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'hotfix/**'
      - 'feature/**'
      - 'renovate/**'
      - 'dependabot/**'
    paths:
      - 'packages/extensions/browser/snapshot/**'
      - '.github/workflows/ci-extensions-browser-snapshot.yaml'
      - '.github/workflows/ci-extensions-browser-template.yaml'

permissions:
  contents: write

concurrency:
  group: ci-extensions-browser-snapshot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-extensions-browser-template.yaml
    with:
      package: packages/extensions/browser/snapshot
      filter: '@hieudoanm.github.io/snapshot'
      releaseName: extensions-browser-snapshot-latest
      releaseTitle: Extensions - Browser - Snapshot (latest)
      artifactPrefix: extensions-browser-snapshot
