name: CI - Themes

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**
    paths:
      - .github/workflows/ci-themes.yaml
      - themes/**

jobs:
  github-actions:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Ubuntu
            version: ubuntu-latest
        node:
          - name: Node.js 18
            version: 18.x
        project:
          - name: Next.js Profile Astronout
            working-directory: ./themes/next-profile-astronout
          - name: Next.js Profile Card
            working-directory: ./themes/next-profile-card
          - name: Next.js Profile Minimal
            working-directory: ./themes/next-profile-minimal
    name: ${{ matrix.node.name }} - ${{ matrix.os.name }} - ${{ matrix.project.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node.version }}
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
        working-directory: ${{ matrix.project.working-directory }}
      - name: Build Production
        run: yarn build
        working-directory: ${{ matrix.project.working-directory }}
      - name: Export Static
        run: yarn export
        working-directory: ${{ matrix.project.working-directory }}
