name: Continuous Integration

on:
  push:
    paths:
      - package.json
      - app/**
      - backend/**
      - frontend/**
    branches:
      - develop
      - hotfix/**
      - feature/**
      - renovate/**
      - dependabot/**

jobs:
  continuous-integration:
    strategy:
      fail-fast: false
      matrix:
        services:
          - name: App - Web
            working-directory: app/web
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
        working-directory: ${{ matrix.services.working-directory }}
      - name: Linting
        run: yarn lint --fix
        working-directory: ${{ matrix.services.working-directory }}
      - name: Build Production
        run: yarn build
        working-directory: ${{ matrix.services.working-directory }}
        env:
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      - name: Unit Tests
        run: yarn test -u
        working-directory: ${{ matrix.services.working-directory }}
        env:
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
