name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 86400000
      - name: Linting
        run: yarn lint --fix

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 86400000
      - name: Unit Test
        run: yarn test -u

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 86400000
      - name: Build Production
        run: yarn build
      - name: Disable Jekyll
        run: touch .nojekyll
        working-directory: out
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          token: ${{ secrets.GHP_TOKEN }}
          branch: gh-pages
          folder: out
          clean: true
