name: Chess - Sync Games

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        players:
          - username: hikaru
    name: Sync Games - ${{ matrix.players.username }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
        working-directory: app/chess
      # - name: Set Up Prisma
      #   run: yarn prisma format && yarn prisma generate
      #   working-directory: app/chess
      #   env:
      #     USERNAME: ${{ matrix.players.username }}
      #     POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
      #     POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
      #     POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      # - name: Sync Games
      #   run: make import-games-api
      #   working-directory: app/chess
      #   env:
      #     USERNAME: ${{ matrix.players.username }}
      #     POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
      #     POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
      #     POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
