name: Chess - Sync Titles

on:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/web/import/titles.ts'
  schedule:
    - cron: '0 0 * * 0' # "At 00:00 on Sunday."

jobs:
  sync:
    name: Sync Titled
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.6.1'
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install Dependencies
        run: pnpm install
        working-directory: languages/javascript/apps/web
      - name: Set Up Prisma
        run: pnpm prisma format && pnpm prisma generate
        working-directory: languages/javascript/apps/web
      - name: Sync Titled
        run: pnpm ts-node ./scripts/ts/chess/import/titled.ts
        working-directory: languages/javascript/apps/web
        env:
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
