export interface VideoToolConfig {
  id: string;
  title: string;
  emoji: string;
  description: string;
  category: 'convert' | 'edit' | 'audio' | 'download';
  inputFormat?: string;
  outputFormat?: string;
  outputExt?: string;
  mimeType?: string;
  accept?: string;
  platform?: string;
}

export const CATEGORIES: { key: string; label: string; emoji: string }[] = [
  { key: 'convert', label: 'Convert', emoji: '🔄' },
  { key: 'edit', label: 'Edit', emoji: '✂️' },
  { key: 'audio', label: 'Audio', emoji: '🎤' },
  { key: 'download', label: 'Download', emoji: '⬇️' },
];

export const TOOLS: VideoToolConfig[] = [
  // ── Convert ──────────────────────────────────────
  {
    id: 'video-aac-to-mp3',
    title: 'AAC to MP3',
    emoji: '🔊',
    description: 'Convert AAC audio to MP3',
    category: 'convert',
    inputFormat: 'AAC',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.aac,audio/aac',
  },
  {
    id: 'video-aac-to-mp4',
    title: 'AAC to MP4',
    emoji: '🎞️',
    description: 'Wrap AAC audio in MP4 container',
    category: 'convert',
    inputFormat: 'AAC',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.aac,audio/aac',
  },
  {
    id: 'video-aac-to-wav',
    title: 'AAC to WAV',
    emoji: '🎵',
    description: 'Convert AAC audio to WAV',
    category: 'convert',
    inputFormat: 'AAC',
    outputFormat: 'WAV',
    outputExt: 'wav',
    mimeType: 'audio/wav',
    accept: '.aac,audio/aac',
  },
  {
    id: 'video-avi-to-gif',
    title: 'AVI to GIF',
    emoji: '🎞️',
    description: 'Convert AVI video to animated GIF',
    category: 'convert',
    inputFormat: 'AVI',
    outputFormat: 'GIF',
    outputExt: 'gif',
    mimeType: 'image/gif',
    accept: '.avi,video/avi',
  },
  {
    id: 'video-avi-to-mp3',
    title: 'AVI to MP3',
    emoji: '🔊',
    description: 'Extract audio from AVI to MP3',
    category: 'convert',
    inputFormat: 'AVI',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.avi,video/avi',
  },
  {
    id: 'video-avi-to-mp4',
    title: 'AVI to MP4',
    emoji: '🎞️',
    description: 'Convert AVI video to MP4',
    category: 'convert',
    inputFormat: 'AVI',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.avi,video/avi',
  },
  {
    id: 'video-flv-to-mp4',
    title: 'FLV to MP4',
    emoji: '🎞️',
    description: 'Convert FLV video to MP4',
    category: 'convert',
    inputFormat: 'FLV',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.flv,video/x-flv',
  },
  {
    id: 'video-gif-to-mov',
    title: 'GIF to MOV',
    emoji: '🎞️',
    description: 'Convert animated GIF to MOV',
    category: 'convert',
    inputFormat: 'GIF',
    outputFormat: 'MOV',
    outputExt: 'mov',
    mimeType: 'video/quicktime',
    accept: '.gif,image/gif',
  },
  {
    id: 'video-gif-to-mp4',
    title: 'GIF to MP4',
    emoji: '🎞️',
    description: 'Convert animated GIF to MP4',
    category: 'convert',
    inputFormat: 'GIF',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.gif,image/gif',
  },
  {
    id: 'video-gif-to-webm',
    title: 'GIF to WebM',
    emoji: '🎞️',
    description: 'Convert animated GIF to WebM',
    category: 'convert',
    inputFormat: 'GIF',
    outputFormat: 'WebM',
    outputExt: 'webm',
    mimeType: 'video/webm',
    accept: '.gif,image/gif',
  },
  {
    id: 'video-m4a-to-mp3',
    title: 'M4A to MP3',
    emoji: '🔊',
    description: 'Convert M4A audio to MP3',
    category: 'convert',
    inputFormat: 'M4A',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.m4a,audio/m4a',
  },
  {
    id: 'video-m4a-to-mp4',
    title: 'M4A to MP4',
    emoji: '🎞️',
    description: 'Wrap M4A audio in MP4 container',
    category: 'convert',
    inputFormat: 'M4A',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.m4a,audio/m4a',
  },
  {
    id: 'video-m4a-to-wav',
    title: 'M4A to WAV',
    emoji: '🎵',
    description: 'Convert M4A audio to WAV',
    category: 'convert',
    inputFormat: 'M4A',
    outputFormat: 'WAV',
    outputExt: 'wav',
    mimeType: 'audio/wav',
    accept: '.m4a,audio/m4a',
  },
  {
    id: 'video-mkv-to-gif',
    title: 'MKV to GIF',
    emoji: '🎞️',
    description: 'Convert MKV video to animated GIF',
    category: 'convert',
    inputFormat: 'MKV',
    outputFormat: 'GIF',
    outputExt: 'gif',
    mimeType: 'image/gif',
    accept: '.mkv,video/x-matroska',
  },
  {
    id: 'video-mkv-to-mp3',
    title: 'MKV to MP3',
    emoji: '🔊',
    description: 'Extract audio from MKV to MP3',
    category: 'convert',
    inputFormat: 'MKV',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.mkv,video/x-matroska',
  },
  {
    id: 'video-mkv-to-mp4',
    title: 'MKV to MP4',
    emoji: '🎞️',
    description: 'Convert MKV video to MP4',
    category: 'convert',
    inputFormat: 'MKV',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.mkv,video/x-matroska',
  },
  {
    id: 'video-mov-to-avi',
    title: 'MOV to AVI',
    emoji: '🎞️',
    description:
      'Convert MOV video to AVI (outputs MKV as closest supported format)',
    category: 'convert',
    inputFormat: 'MOV',
    outputFormat: 'MKV',
    outputExt: 'mkv',
    mimeType: 'video/x-matroska;codecs=vp8,opus',
    accept: '.mov,video/quicktime',
  },
  {
    id: 'video-mov-to-gif',
    title: 'MOV to GIF',
    emoji: '🎞️',
    description: 'Convert MOV video to animated GIF',
    category: 'convert',
    inputFormat: 'MOV',
    outputFormat: 'GIF',
    outputExt: 'gif',
    mimeType: 'image/gif',
    accept: '.mov,video/quicktime',
  },
  {
    id: 'video-mov-to-mp3',
    title: 'MOV to MP3',
    emoji: '🔊',
    description: 'Extract audio from MOV to MP3',
    category: 'convert',
    inputFormat: 'MOV',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.mov,video/quicktime',
  },
  {
    id: 'video-mov-to-mp4',
    title: 'MOV to MP4',
    emoji: '🎞️',
    description: 'Convert MOV video to MP4',
    category: 'convert',
    inputFormat: 'MOV',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.mov,video/quicktime',
  },
  {
    id: 'video-mov-to-wav',
    title: 'MOV to WAV',
    emoji: '🎵',
    description: 'Extract audio from MOV to WAV',
    category: 'convert',
    inputFormat: 'MOV',
    outputFormat: 'WAV',
    outputExt: 'wav',
    mimeType: 'audio/wav',
    accept: '.mov,video/quicktime',
  },
  {
    id: 'video-mp4-to-avi',
    title: 'MP4 to AVI',
    emoji: '🎞️',
    description: 'Convert MP4 video to AVI',
    category: 'convert',
    inputFormat: 'MP4',
    outputFormat: 'AVI',
    outputExt: 'mkv',
    mimeType: 'video/x-matroska;codecs=vp8,opus',
    accept: '.mp4,video/mp4',
  },
  {
    id: 'video-mp4-to-mov',
    title: 'MP4 to MOV',
    emoji: '🎞️',
    description: 'Convert MP4 video to MOV',
    category: 'convert',
    inputFormat: 'MP4',
    outputFormat: 'MOV',
    outputExt: 'mov',
    mimeType: 'video/quicktime',
    accept: '.mp4,video/mp4',
  },
  {
    id: 'video-mp4-to-mp3',
    title: 'MP4 to MP3',
    emoji: '🔊',
    description: 'Extract audio from MP4 to MP3',
    category: 'convert',
    inputFormat: 'MP4',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.mp4,video/mp4',
  },
  {
    id: 'video-mp4-to-ogg',
    title: 'MP4 to OGG',
    emoji: '🔊',
    description: 'Convert MP4 audio to OGG',
    category: 'convert',
    inputFormat: 'MP4',
    outputFormat: 'OGG',
    outputExt: 'ogg',
    mimeType: 'audio/ogg',
    accept: '.mp4,video/mp4',
  },
  {
    id: 'video-mp4-to-wav',
    title: 'MP4 to WAV',
    emoji: '🎵',
    description: 'Extract audio from MP4 to WAV',
    category: 'convert',
    inputFormat: 'MP4',
    outputFormat: 'WAV',
    outputExt: 'wav',
    mimeType: 'audio/wav',
    accept: '.mp4,video/mp4',
  },
  {
    id: 'video-convert-to-webm',
    title: 'to WebM',
    emoji: '🎞️',
    description: 'Convert video to WebM format',
    category: 'convert',
    outputExt: 'webm',
    mimeType: 'video/webm;codecs=vp8,opus',
    accept: 'video/*',
  },
  {
    id: 'video-to-gif',
    title: 'Video to GIF',
    emoji: '🎞️',
    description: 'Convert any video to animated GIF',
    category: 'convert',
    outputExt: 'gif',
    mimeType: 'image/gif',
    accept: 'video/*',
  },
  {
    id: 'video-to-webp',
    title: 'Video to WebP',
    emoji: '🎞️',
    description: 'Convert any video to animated WebP',
    category: 'convert',
    outputExt: 'webp',
    mimeType: 'image/webp',
    accept: 'video/*',
  },
  {
    id: 'video-ogg-to-mp3',
    title: 'OGG to MP3',
    emoji: '🔊',
    description: 'Convert OGG audio to MP3',
    category: 'convert',
    inputFormat: 'OGG',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.ogg,audio/ogg',
  },
  {
    id: 'video-ogg-to-wav',
    title: 'OGG to WAV',
    emoji: '🎵',
    description: 'Convert OGG audio to WAV',
    category: 'convert',
    inputFormat: 'OGG',
    outputFormat: 'WAV',
    outputExt: 'wav',
    mimeType: 'audio/wav',
    accept: '.ogg,audio/ogg',
  },
  {
    id: 'video-webm-to-mp3',
    title: 'WebM to MP3',
    emoji: '🔊',
    description: 'Extract audio from WebM to MP3',
    category: 'convert',
    inputFormat: 'WebM',
    outputFormat: 'MP3',
    outputExt: 'mp3',
    mimeType: 'audio/mpeg',
    accept: '.webm,video/webm',
  },
  {
    id: 'video-wmv-to-mp4',
    title: 'WMV to MP4',
    emoji: '🎞️',
    description: 'Convert WMV video to MP4',
    category: 'convert',
    inputFormat: 'WMV',
    outputFormat: 'MP4',
    outputExt: 'mp4',
    mimeType: 'video/mp4',
    accept: '.wmv,video/x-ms-wmv',
  },

  // ── Edit ──────────────────────────────────────────
  {
    id: 'video-compress',
    title: 'Compress',
    emoji: '📦',
    description: 'Reduce video file size by adjusting quality',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-crop',
    title: 'Crop',
    emoji: '✂️',
    description: 'Crop video to specified dimensions',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-extract-audio',
    title: 'Extract Audio',
    emoji: '🔊',
    description: 'Extract audio track from video',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-extract-frames',
    title: 'Extract Frames',
    emoji: '🖼️',
    description: 'Extract video frames as PNG images',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-merge',
    title: 'Merge',
    emoji: '🔗',
    description: 'Merge multiple videos sequentially',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-mute',
    title: 'Mute',
    emoji: '🔇',
    description: 'Remove audio track from video',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-resize',
    title: 'Resize',
    emoji: '📐',
    description: 'Resize video dimensions',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-speed',
    title: 'Speed',
    emoji: '⚡',
    description: 'Change video playback speed',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-stabilize',
    title: 'Stabilize',
    emoji: '🎯',
    description: 'Stabilize shaky video',
    category: 'edit',
    accept: 'video/*',
  },
  {
    id: 'video-trim',
    title: 'Trim',
    emoji: '✂️',
    description: 'Trim video by start and end timestamps',
    category: 'edit',
    accept: 'video/*',
  },

  // ── Audio ─────────────────────────────────────────
  {
    id: 'audio-transcribe',
    title: 'Transcribe',
    emoji: '🎤',
    description: 'Transcribe speech from microphone',
    category: 'audio',
  },
  {
    id: 'generate-subtitle',
    title: 'Subtitles',
    emoji: '📝',
    description: 'Generate subtitles for video',
    category: 'audio',
  },

  // ── Download ──────────────────────────────────────
  {
    id: 'video-download-facebook',
    title: 'Facebook',
    emoji: '📘',
    description: 'Download Facebook video',
    category: 'download',
    platform: 'Facebook',
  },
  {
    id: 'video-download-instagram',
    title: 'Instagram',
    emoji: '📸',
    description: 'Download Instagram video',
    category: 'download',
    platform: 'Instagram',
  },
  {
    id: 'video-download-tiktok',
    title: 'TikTok',
    emoji: '🎵',
    description: 'Download TikTok video',
    category: 'download',
    platform: 'TikTok',
  },
  {
    id: 'video-download-twitter',
    title: 'Twitter / X',
    emoji: '🐦',
    description: 'Download Twitter video',
    category: 'download',
    platform: 'Twitter',
  },
  {
    id: 'video-youtube-text',
    title: 'YouTube Text',
    emoji: '📺',
    description: 'Extract text from YouTube video',
    category: 'download',
    platform: 'YouTube',
  },
  {
    id: 'video-youtube-transcript',
    title: 'YouTube Transcript',
    emoji: '📝',
    description: 'Download YouTube video transcript',
    category: 'download',
    platform: 'YouTube',
  },
];

export const CATEGORY_TOOLS: Record<string, string[]> = {};
for (const t of TOOLS) {
  (CATEGORY_TOOLS[t.category] ??= []).push(t.id);
}

let preselectedToolId: string | null = null;

export const preselectVideoTool = (id: string | null) => {
  preselectedToolId = id;
};

export const popPreselectedVideoTool = (): string | null => {
  const id = preselectedToolId;
  preselectedToolId = null;
  return id;
};
